### ISSUE TITLE
No gum on pacman

### ISSUE THREAD

**Issue by arudp** [charmbracelet/gum#100]
**Describe the bug**
Wanted to check this beautiful tool out and tried installing it, but `pacman` couldn't find it! I synced just in case (though I had synced yesterday already and this repo is older, so I figured it wouldn't help), but still couldn't find it :cry: 

**To Reproduce**
1. Just run `pacman -S gum`

**Expected behavior**
For it to be installed

**Screenshots**
```
~ $ sudo pacman -S gum
error: target not found: gum
```

**Desktop (please complete the following information):**
 - OS: Manjaro

**Comment by muesli** [comment]
Manjaro is not Arch, and it'll possibly take a bit longer for them to adopt the package. In the meantime, you can simply download and install the Arch package however:

https://archlinux.org/packages/community/x86_64/gum/

**Comment by arudp** [comment]
Thanks! I honestly thought that they used the same repos!
