### ISSUE TITLE
Add auto-confirm timeout

### ISSUE THREAD

**Issue by TiGR** [charmbracelet/gum#103]
Imagine you need to change some behavior of your script only sometimes, but generally it is fine to run in default configuration. As an example, think about grub bootloader, that boots default configuration unless you change something. 

So, it would be nice for confirm command to have a user-configurable timeout, after which default option would be selected.

**Comment by maaslalani** [comment]
This is a great idea!

**Comment by ChrHan** [comment]
I might have a working implementation on this - will reference this bug on my pull request!
