### ISSUE TITLE
Bug: gum choose variable

### ISSUE THREAD

**Issue by Simon-He95** [charmbracelet/gum#105]
**Describe the bug**
gum choose "README.md" "README_en.md" "assets" 
it is very good, but I want to a variable to equal the content after "choose", it's not good.

such as 
```
 a="\"README.md\" \"README_en.md\" \"assets\" "
gum choose $a
> "README.md" "README_en.md" "assets" # only one options
# expected output
> README.md
  README_en.md
  assets
```

**Screenshots**

![image](https://user-images.githubusercontent.com/57086651/183239315-821aa48a-3a63-4089-9019-02611bba3784.png)

**Comment by Simon-He95** [comment]
```
if (process.argv.length === '3'){ // argv[3] = "README.md" "README_en.md" "assets"
// process.argv.split(' '), Can we deal with the parameters in this way?
// we can get choices [ "README.md", "README_en.md", "assets" ]
}
```

**Comment by maaslalani** [comment]
Unfortunately the way you are assigning the variable is as a string that contains quotation marks, this will be treated as a single string and, therefore, is behaving correctly since the variable is a single option.

**Comment by maaslalani** [comment]
You can do something like this to get the effect you want to achieve:

```bash
a="README.md README_en.md assets"; echo $a | sed 's/ /\n/g' | gum choose
```

<img width="755" alt="image" src="https://user-images.githubusercontent.com/42545625/183309685-1b507953-5d48-47f1-965c-d555f6710df6.png">

**Comment by Simon-He95** [comment]
Thanks for your help
