### ISSUE TITLE
Option to control write max length

### ISSUE THREAD

**Issue by leighmcculloch** [charmbracelet/gum#109]
**Is your feature request related to a problem? Please describe.**
It appears the max length is reasonably small for the `write` text box. I'm not sure on what the limit is exactly, but I've noticed that when I'm typing out git commit messages (I use `gum write` for that) I frequently hit the limit. I don't see an option that lets me expand that.

**Describe the solution you'd like**
An option for the `gum write` command that lets the user set the maximum character limit, or disable the character limit.

**Describe alternatives you've considered**
Some alternatives exist:
- Be content with the smaller character limit. This is fine.
- Use gum write multiple times. This would feel a bit odd.

**Additional context**
N/A

**Comment by maaslalani** [comment]
Hey @leighmcculloch there is a `--char-limit` flag that you can use that defaults to 400.

Feel free to suggest a better (less arbitrary 😄) length for this value: https://github.com/charmbracelet/gum/blob/main/write/options.go#L14


What version of `gum` are you on by the way?

**Comment by leighmcculloch** [comment]
Ah, I was using v0.3.0 that didn't have the char limit control:
```
❯ gum write -h
Usage: gum write

Prompt for long-form text

Flags:
  -h, --help                 Show context-sensitive help.
  -v, --version              Print the version number

      --width=50             Text area width
      --height=5             Text area height
      --placeholder="Write something..."
                             Placeholder value
      --prompt="┃ "          Prompt to display
      --show-cursor-line     Show cursor line
      --show-line-numbers    Show line numbers
      --value=""             Initial value (can be passed via stdin)

Style Flags
  --base.foreground=""                   Foreground Color
  --cursor-line-number.foreground="7"    Foreground Color
  --cursor-line.foreground=""            Foreground Color
  --cursor.foreground="212"              Foreground Color
  --end-of-buffer.foreground="0"         Foreground Color
  --line-number.foreground="7"           Foreground Color
  --placeholder.foreground="240"         Foreground Color
  --prompt.foreground="7"                Foreground Color
```

I see it now that I upgraded to v0.4.0.

Thanks!

**Comment by maaslalani** [comment]
Nice! Thanks for using `gum` @leighmcculloch!
