### ISSUE TITLE
gum filter --reverse

### ISSUE THREAD

**Issue by caarlos0** [charmbracelet/gum#114]
**Is your feature request related to a problem? Please describe.**
fzf's default style is prompt in the bottom, list in the top... gum's is the other way around.,

**Describe the solution you'd like**
fzf also has a `--layout reverse` flag to make it the other way around... I believe we need something like that in for `gum filter` too.

**Describe alternatives you've considered**
haven't found any alternatives

**Additional context**

**Comment by maaslalani** [comment]
TIL about `fzf --layout reverse`! Yeah, we can have something similar in Gum :)

**Comment by dhruvmanila** [comment]
`fzf` offers multiple layouts:
```
*        --layout=LAYOUT
*               Choose the layout (default: default)
  
                default       Display from the bottom of the screen
                reverse       Display from the top of the screen
                reverse-list  Display from the top of the screen, prompt at the bottom
```

The default for `gum` is the `reverse` layout. By `reverse`, @caarlos0 do you mean the `default` layout?

**Comment by caarlos0** [comment]
> The default for `gum` is the `reverse` layout. By `reverse`, @caarlos0 do you mean the `default` layout?

yes, so, my suggestion is to add the "alternate" layout, do we can have a `--reverse` flag as well... but in gum's case, gum's default == fzf's `--reverse`, and gum's `--reverse` == fzf's default.l
