### ISSUE TITLE
use gum style border display is incorrect

### ISSUE THREAD

**Issue by sharpbetter** [charmbracelet/gum#115]
like this

![image](https://user-images.githubusercontent.com/16473159/183792484-ceda0515-44db-4986-b240-63eb3325a6eb.png)

- OS: Ubuntu 20.04.4 
- Version: gum 0.4.0

**Comment by maaslalani** [comment]
What terminal are you using @sharpbetter, I am unable to reproduce:

<img width="958" alt="image" src="https://user-images.githubusercontent.com/42545625/183792736-341d1c9a-45c8-471e-a83e-b51c8cc817a9.png">

**Comment by sharpbetter** [comment]
hi @maaslalani  thank you for your reply , gum is awesome
i using  Windows Terminal
im in china use chinese , i guess is system encoding length problem?
because width of the display is always half 

![image](https://user-images.githubusercontent.com/16473159/183847153-5343e1ad-6a16-4649-bf5e-071935a43df2.png)

**Comment by meowgorithm** [comment]
See https://github.com/charmbracelet/lipgloss/issues/40

**Comment by sharpbetter** [comment]
thank 
set  `export LC_CTYPE="en_US.UTF-8"`  display is normal

**Comment by olivertzeng** [comment]
You should ping this issue!

**Comment by olivertzeng** [comment]
@meowgorithm
