### ISSUE TITLE
Gum write ctrl-d ergonomics

### ISSUE THREAD

**Issue by fimdomeio** [charmbracelet/gum#121]
gum write ctrl-d to end seems a little weird in terms of ergonomics even if it makes sense in a *nix world. In the way I use the command line I don't remember the last time I used ctrl-d.

At [survey](https://github.com/AlecAivazis/survey/) they solved this if two empty lines are inserted. They obviously get removed from the output. I think the muscle memory of pressing enter twice is created very easily. Maybe this could be a flag like --quit-with-newlines or something similar

The alternative is keeping things as they are. Maybe it's not worth the added complexity.

**Comment by IllustratedMan-code** [comment]
ctrl-d is a very standard way to exit interactive input (python is a good example).
escape can also be used to exit `gum write`. Not sure what OS you use, but caps-lock can usually be remapped to either ctrl or esc making both methods very ergonomic.

**Comment by maaslalani** [comment]
I think using two new lines could be a little confusing and it seems that `ctrl+d` is the main way to represent the end of input/file (`EOF`), I wouldn't be opposed to adding more ways to quit the textarea but I don't think they should be part of the input / a special sequence (like two new lines) personally, but maybe I could be convinced.
