### ISSUE TITLE
Add `gum file` picker

### ISSUE THREAD

**Issue by IllustratedMan-code** [charmbracelet/gum#124]
**Is your feature request related to a problem? Please describe.**
There is no easy way to have a user input a file path. Some sort of file chooser dialog that supports tab autocomplete would be great.

**Describe the solution you'd like**
I am envisioning something like the `gum filter` but it would fuzzy match files within the current directory. Once the input was representative of a directory within the current directory, the fuzzy matching would be for that directory.

It would be almost like the output of `ls . | gum filter`, but once the input was another directory, the output would look like `ls ./directory | gum filter`. 

 I'm asking for something similar to the emacs function `council-find-file` , which is displayed at around 6:10 in [this video](https://www.youtube.com/watch?v=fdLCuJcS2Aw&t=372s)

**Comment by maaslalani** [comment]
I think a file finder / file tree input would be absolutely fantastic:

```bash
gum file
```

It could look something like this (based on `ssh git.charm.sh`)

<img width="473" alt="Screen Shot 2022-09-27 at 11 43 24 AM" src="https://user-images.githubusercontent.com/42545625/192572701-566049f4-df30-44eb-9fd9-68179a795081.png">
