### ISSUE TITLE
:bulb: [feature] Add a --max-length option for input

### ISSUE THREAD

**Issue by adriens** [charmbracelet/gum#125]
# :grey_question: Context

Sometimes you want the be able to put some constraints on `input` fields.

:point_right: For example for `commit` subject line to 50 characters.

:point_up: The main idea is would to put this constraint right into `gum` so the underlying call is cleaner :smile_cat: 

# :dart: Feature request

- [ ] Add the `--max-length` parameter to the `input` command
- [ ] Add this to [the conventional commit example](https://youtu.be/vtCwt-4tIto) would be pretty cool too

**Comment by maaslalani** [comment]
Hey @adriens, thanks for making this issue. You can use the `--char-limit` flag to do exactly this!

**Comment by adriens** [comment]
Awesome :heavy_heart_exclamation: Thanks a lot :clap:
