### ISSUE TITLE
Gum choose inconsistent behaviour

### ISSUE THREAD

**Issue by DanielSSilva** [charmbracelet/gum#127]
**Describe the bug**
First of all, I'm not sure if this is a bug or if it's the expected behavior, but I'm not familiar with bash scripting.
Part of the issue I believe it's related to `jq` output, but let's go through parts.

**To Reproduce**

The following code runs just fine when running from the console
```bash 
countries=$( curl 'https://restcountries.com/v2/all' | jq '.[].name')
echo $countries | gum choose
```
This outputs a list of countries, paginated, as expected.
Saving that code on a .sh file (i.e `countries.sh`) and running it 
```bash
chmod +x ./countries.sh
./countries.sh
```
`gum` considers this all to be one single string.

Below you can find a screenshot with both examples.

**Expected behavior**
Running the same code with gum choose directly on the terminal and from a script should output the same.

**Screenshots**
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/6862119/185786258-74ad9686-69ee-4ee5-b834-58b10307496b.png">

The reason why I say that `jq` output might play something here is that, for some reason that I don't know (maybe it's how bash works), 
```bash
echo $countries | gum choose # this works fine

gum choose $countries # this loads everything as 1 string with \n

gum choose $(echo $countries)  # "wraping" choose parameter on echo works fine
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 12.5.1

**Comment by DanielSSilva** [comment]
Tried the same approach with PowerShell on mac and in this case it works as expected
```powershell
$countries = (Invoke-RestMethod -Method GET 'https://restcountries.com/v2/all') | Select-Object -expandproperty name
gum choose $countries
```
This works both directly on a terminal, as well as from a script.
So, maybe it has something to do with how bash processes files?

<img width="1413" alt="image" src="https://user-images.githubusercontent.com/6862119/185786915-7b1a30c9-fcba-48c3-aeac-5b3b69dca56c.png">

**Comment by Fryuni** [comment]
This is not a problem with gum it is a quirk in how bash expands variables. Wrap the `$countries` in quotes like so:
```bash
countries=$( curl 'https://restcountries.com/v2/all' | jq '.[].name')
echo "$countries" | gum choose
```

Also, you can pass `-r` to jq to not include the quotes on the name of the countries

**Comment by DanielSSilva** [comment]
Wow... Although it's out of scope for gum, do you mind explaining why using quotes makes it working as a .sh in a different way of not using that? Or point me to any reference would be great.

Thanks for the reply!

**Comment by Fryuni** [comment]
Sure, the tl;dr; is that without quotes, bash will reinterpret any [whitespace separator](https://tldp.org/LDP/abs/html/special-chars.html#WHITESPACEREF) (space, tab, newline) as an argument separator, so to bash these are all equivalent:
```bash
echo foo bar baz

echo foo \
     bar \
     baz

value_with_space="foo bar baz"
echo $value_with_space # Becomes the first case

value_with_newline="foo\nbar\nbaz"
echo $value_with_newline # Becomes the second case
```

On interactive mode bash can sometimes skip this reinterpretation (I believe this is more aggressive on fork that comes with Mac OS), this is why it is behaving differently.

On The Linux Documentation Project there is a chapter on the Advanced Bash-Scripting Guide about quoting: https://tldp.org/LDP/abs/html/quoting.html

There is also this great blog post showing some of the problems that can happen when quoting is missing: https://nickjanetakis.com/blog/here-is-why-you-should-quote-your-variables-in-bash

**Comment by DanielSSilva** [comment]
That clarifies a lot! Thank you very much for taking the time to explain it and for the references :)
