### ISSUE TITLE
Multi-choose should maintain order of selection

### ISSUE THREAD

**Issue by FT-Labs** [charmbracelet/gum#128]
Hi, I've written a bash script but items orders are important. In gum selection, they always return the items on default order. An enumeration would be really nice, for example clicking space would write numbers in the box, then return the items with order.

**Comment by dhruvmanila** [comment]
I guess this should be done using a new flag like `--keep-order` (better suggestion?) to avoid breaking change?

**Comment by FT-Labs** [comment]
Yes definitely, a new flag could be added, which could just be a boolean.

**Comment by FT-Labs** [comment]
If anyone wants to do this, before feat is available, you can take a look at this script:
https://github.com/FT-Labs/phyOS-system-scripts/blob/master/usr/share/phyos/util-scripts/pOS-make-bar
