### ISSUE TITLE
[Docs] The pictures in README is blank

### ISSUE THREAD

**Issue by Zerokei** [charmbracelet/gum#133]
**Describe the bug**
The pictures in README is blank.

**To Reproduce**
1. Go to https://github.com/charmbracelet/gum

**Expected behavior**
Pictures display in README

**Screenshots**
![](https://zerokei-imgurl.oss-cn-hangzhou.aliyuncs.com/img/20220828112252.png)

**Comment by muesli** [comment]
Probably just a GitHub CDN hiccup. Works again now.
