### ISSUE TITLE
`--limit` doesn't actually limit the number of picks.

### ISSUE THREAD

**Issue by your-diary** [charmbracelet/gum#135]
**Describe the bug**
`gum choose --limit` doesn't actually limit the number of picks.

**To Reproduce**
1. Execute `gum choose --limit=2 a b c`.
```bash
$ gum choose --limit=2 a b c
> [•] a
  [ ] b
  [ ] c
```

2. When you press <kbd>a</kbd>, everything is selected whilst `--limit 2` is specified.
```bash
$ gum choose --limit=2 a b c
> [✕] a
  [✕] b
  [✕] c
```

3. When you press <kbd>Enter</kbd>, all are printed.
```bash
$ gum choose --limit=2 a b c
a
b
c
```

**Expected behavior**
At most `N` options can be selected when `--limit=N`.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS Big Sur, Arch Linux
 - Version [e.g. 22] 0.4.0 (131ae3b)
 - Terminal Emulator: iTerm2

**Comment by maaslalani** [comment]
I can't reproduce this issue 🤔 Can you try using the latest code on `main`?

https://user-images.githubusercontent.com/42545625/187263617-509dfe57-f5cf-4022-b740-7b74bc5a15ff.mov

**Comment by your-diary** [comment]
@maaslalani 
Thank you for trying that.

> *I can't reproduce this issue*

Did you press <kbd>a</kbd> instead of <kbd>x</kbd>? In my case, pressing <kbd>x</kbd> works as expected whilst pressing <kbd>a</kbd> unexpectedly selects all of the displayed items.

> *Can you try using the latest code on main?*

Yes. Reproduced. Here is how I tested:
```bash
git clone 'https://github.com/charmbracelet/gum'
cd gum
go build
./gum choose --limit=2 a b c
```

**Comment by maaslalani** [comment]
@your-diary Should be fixed now on the latest main!

**Comment by your-diary** [comment]
@maaslalani What a rapid fix. Worked. Thank you!
