### ISSUE TITLE
Return a different error code for ESC vs CTRL-C in filter

### ISSUE THREAD

**Issue by zachoooo** [charmbracelet/gum#138]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to differentiate between ESC and CTRL-C in the `gum filter` command. I would like for my program to be able to know. The only data I have to know is the return code which is 130 regardless of which of those two keys is pressed.

**Describe the solution you'd like**
Different exit codes should occur instead of 130 for both. You could have 130 for ESC and 131 for CTRL-C or whichever codes you'd prefer.

**Describe alternatives you've considered**
I considered trying to capture the I/O of the subprocess so I can know which key was pressed, but this seems unnecessarily complicated and like it could cause issues with rendering of the subprocess.

**Additional context**

**Comment by deicon** [comment]
I would say, this is fixed already.

**Comment by zachoooo** [comment]
@deicon That looks like its just for `gum confirm` and it also looks like the same exit code is used for both hitting escape and CTRL-C. This is different than what I was suggesting.

**Comment by deicon** [comment]
> @deicon That looks like its just for `gum confirm` and it also looks like the same exit code is used for both hitting escape and CTRL-C. This is different than what I was suggesting.

True. I must have misread it. 
Not sure if i buy into this distinction between ESC and Ctrl-c. But could be done for sure. 

For BASH Ctrl-C is defined as 130 https://tldp.org/LDP/abs/html/exitcodes.html
ESC is not really defined nor can I find a best practice for this.

**Comment by zachoooo** [comment]
If you're making an interactive application then its possible that you're several "layers" deep in the UI. The user may want a way to go back without having to fully exit the application and start over. One option would be to add a special filter list option for going back like "Back", but I don't feel like this is ideal for the developer or the user. `ESC` would be faster and more intuitive.

I do see what you mean though that using an arbitrary exit code could be confusing so it might be better to have the escape key print the escape character (ASCII 27 `\x1b` or U+001B) to stdout and then exit. This could be an option you could toggle like `--print-escape-key`. So nothing would change if this option is off. If the option is on then stdout would have this special character in the text and so the developer could handle this as a special case.
