### ISSUE TITLE
Is this not compatible with POSIX-like shells?

### ISSUE THREAD

**Issue by wael444** [charmbracelet/gum#14]
eg. mksh, dash, oksh, yash, standard sh, ash, etc etc..

**Comment by bradatgeacom** [comment]
I just tried this in oksh, seems to work quite well actually.

**Comment by maaslalani** [comment]
Thanks for testing @bradatgeacom!

@wael444 This should be compatible with all shells (see: https://github.com/charmbracelet/gum/blob/main/examples/posix.sh)

**Comment by wael444** [comment]
thanks for clarifying!

i just had thought otherwise because the README doesn't specify at first, it does `bash`.

**Comment by maaslalani** [comment]
Yeah, in hindsight I probably should have made it `#!/bin/sh`, I will fix now 🙂
