### ISSUE TITLE
gum confirm --default="yes" --timeout=3s 'delete' 

### ISSUE THREAD

**Issue by ziwen1002** [charmbracelet/gum#142]
**Describe the bug**

run command
 `gum confirm --default="yes" --timeout=3s 'delete'`
- The timer is always on the label of NO
- The default action after the overtime is NO

**To Reproduce**
1. run command  `gum confirm --default="yes" --timeout=3s 'delete'`

**Expected behavior**
- The timer is on the label of default
- The default action after the overtime is default

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Browser none
 - Version gum version v0.5.0 (0834690)

**Smartphone (please complete the following information):**
none

**Additional context**
none

**Comment by ChrHan** [comment]
If I understand correctly, you would like to set default to "yes" when timeout ends.

In that case, command should be `gum confirm --timeout=3s 'delete'` as the `--default` parameter only accept `true` for `exit code 0` or `false` for `exit code 1`

However, looking at the codebase, there can be an improvement made to not enforce `gum confirm --timeout` to `exit code 1` - I'll post the proposed PR later on

**Comment by ziwen1002** [comment]
Yes, this is what I expected.

**Comment by ziwen1002** [comment]
> If I understand correctly, you would like to set default to "yes" when timeout ends.
> 
> In that case, command should be `gum confirm --timeout=3s 'delete'` as the `--default` parameter only accept `true` for `exit code 0` or `false` for `exit code 1`
> 
> However, looking at the codebase, there can be an improvement made to not enforce `gum confirm --timeout` to `exit code 1` - I'll post the proposed PR later on

Yes, this is what I expected

**Comment by muesli** [comment]
It would also be nice to have a `--timeout` flag for commands like `choose`, `input`, and `spin`.
