### ISSUE TITLE
gum choose --no-limit "fix" "feat" "docs" "style"

### ISSUE THREAD

**Issue by ziwen1002** [charmbracelet/gum#143]
**Is your feature request related to a problem? Please describe.**

Hope to provide a "all" option

**Describe the solution you'd like**
when set "--no-limit" flag, hope to provide a "all" option.

**Describe alternatives you've considered**
- hope to provide a "all" option.
- "all" option string can set by arg,like '--affirmative="Yes"' in "confirm" command

**Additional context**
none

**Comment by maaslalani** [comment]
Hey @ziwen1002 thanks for the issue, we just added a `--selected` flag that allows you to pre-select entries which you can use here:

```bash
gum choose --no-limit fix feat docs style --selected fix feat docs style

# Or essentially --all
OPTIONS=(fix feat docs style) gum choose --no-limit $OPTIONS --selected $OPTIONS
```
