### ISSUE TITLE
Home / End key not working correctly

### ISSUE THREAD

**Issue by keevan** [charmbracelet/gum#150]
**Describe the bug**
`gum input` and `gum filter` and `gum write` don't seem to handle `home` / `end` keyboard inputs as expected.

**To Reproduce**
1. Run `gum input`
2. Type "Hello World"
3. Then tap the `Home` key
4. Then tap the `End` key
5. See `[H` and `[F` characters were displayed instead

**Expected behavior**
I'm expecting the input cursor to jump to the beginning of the current line, then back to the end.

**Screenshots**
Final output:
```
$ gum input
> Hello World[H[F
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser N/A
 - Version 22
 - Terminal kitty 0.25.2

**Comment by maaslalani** [comment]
Should be fixed on latest `@main`! Thanks again for opening this issue!

**Comment by keevan** [comment]
Tested and can confirm this works on current `main` code. Not in 0.7.0 though, so it should be in the next release for those wondering. 

Thanks again!
