### ISSUE TITLE
gum input and gum filter handle input strangely after moving cursor to the start

### ISSUE THREAD

**Issue by keevan** [charmbracelet/gum#151]
**Describe the bug**
`gum input` and `gum filter` seem to jump to the end of the line when an input is made after moving the cursor back to the start of the line. This _only_ appears to happen the cursor is at the starting character.

**To Reproduce**
1. Run `gum input`
2. Type "Hello World"
3. Go to the start of the line (e.g. hold the left key or alt + left your way back)
4. Confirm you are at the starting character
5. Proceed to type "12345"

**Expected behavior**
I'm expecting the final state to be `12345Hello World`

**Screenshots**
Final output:
```
$ gum input
> 1Hello World2345
```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser N/A
 - Version 22
 - Terminal kitty 0.25.2

**Comment by maaslalani** [comment]
Thank you for submitting this report, I was able to reproduce with your clear instructions and patch a fix in [Bubbles](github.com/charmbracelet/bubbles).

This should now be fixed in Gum (on latest `main` code) as well. Please reopen this issue if this is still an issue for you.

**Comment by keevan** [comment]
Awesome, thanks for looking into that @maaslalani

**Comment by keevan** [comment]
Tested and can confirm this works on current `main` code. Not in 0.7.0 though, so probably next release for those wondering. 

Thanks again!
