### ISSUE TITLE
Support `--limit-min` / `--limit-max` flags.

### ISSUE THREAD

**Issue by olivertzeng** [charmbracelet/gum#152]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when asking people to install at least one package with gum
**Describe the solution you'd like**
use a `--limit-max` and `--limit-min` flag

**Comment by maaslalani** [comment]
> I'm always frustrated when asking people to install at least one package with gum.

This is a similar issue to #87 and the root cause will be solved with that.
