### ISSUE TITLE
Installation via apt became apt update crowded

### ISSUE THREAD

**Issue by lcsjunior** [charmbracelet/gum#154]
**Describe the bug**
Installation via apt became apt update crowded

**To Reproduce**
1. Go to: [https://github.com/charmbracelet/gum#installation](https://github.com/charmbracelet/gum#installation)
2.
```bash
echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list
```
3.
```bash
sudo apt update && sudo apt install gum
```

**Screenshots**
![image](https://user-images.githubusercontent.com/8947621/190294047-59b466cc-8c39-42f4-8e78-185714d01bb0.png)

**Desktop:**
 - OS: Ubuntu 22.04

**Comment by vogler** [comment]
It is really annoying. I tried to make it skip all but `Packages` but didn't find a way to do it without affecting other apt packages.
Here's some documentation:
https://wiki.debian.org/DebianRepository/Format#Flat_Repository_Format
Funnily it says the Translations and Contents indices are not supported for flat repositories...
Maybe it's easier to convert the repository to the default format or add the required files to support it (`dists/` etc.)?

**Comment by lcsjunior** [comment]
I'm not currently using gum anymore.
To resolve this, I'm watching the releases and installing the .deb packages by hand.

**Comment by caarlos0** [comment]
I believe you can disable translations if you're not using them:

https://askubuntu.com/questions/74653/how-can-i-remove-the-translation-entries-in-apt

unfortunately as far as i know its not possible to disable it for a particular repository, and thus there isn't much we can do.
