### ISSUE TITLE
Translate README to multiple languages

### ISSUE THREAD

**Issue by olivertzeng** [charmbracelet/gum#156]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A man page and README.md translate support!

**Comment by maaslalani** [comment]
Hi @olivertzeng, which languages would you like supported, and would you be interested in translating the README to your preferred language?

**Comment by olivertzeng** [comment]
zh_TW

**Comment by olivertzeng** [comment]
Oh I dont mean just the README, if there is an option for translating gum's manpage, it would be awesome!

**Comment by brunoxd13** [comment]
Hello @olivertzeng , I would like to translate to PT-BR. 
Okay?

**Comment by olivertzeng** [comment]
@brunoxd13 Don't ask me

**Comment by muesli** [comment]
Outside contributions are always welcome, but I feel like this needs to be a concerted effort, otherwise translations are quickly gonna diverge, end up outdated or incorrect. We'll think about this.

**Comment by olivertzeng** [comment]
ok

**Comment by olivertzeng** [comment]
> Outside contributions are always welcome, but I feel like this needs to be a concerted effort, otherwise translations are quickly gonna diverge, end up outdated or incorrect. We'll think about this.

I’ll update my translations constantly, I promise.

**Comment by vhespanha** [comment]
Can i do portuguese?

**Comment by caarlos0** [comment]
hey! thanks for the issue!

however, we are a very small team, and can't really take on the burden of maintaining the docs in multiple languages right now.

hopefully we get there in the future!

going to close this for now!
