### ISSUE TITLE
gum choose: Hide real output

### ISSUE THREAD

**Issue by PrtmPhlp** [charmbracelet/gum#168]
Hey, I'm trying to have a simple choose TUI, to select the ssh connection, that I want. My first try was something like this:
```
host=$(cat hosts.txt | gum filter --limit 1)
ssh $host
```
Now I want to hide the real output, that I give, for example arch@12.34.56.78
And more like this
- Debian (1)
- Ubuntu (2)
- Arch (3)
So I can choose in a nix menu, but If i click on one of them, it executes the ssh command with the real user@12.34.56.78
Would like to hear from you!

**Comment by maaslalani** [comment]
Hi! This is very similar to https://github.com/charmbracelet/gum/issues/16

But, you can also achieve that with: https://github.com/charmbracelet/gum/blob/master/examples/filter-key-value.sh

Create a file `hosts.txt`
```
Arch@127.1.2.3
Debian@127.1.2.4
Ubuntu@127.1.2.5
```

```
MACHINE=$(cut -d'@' -f1 < hosts.txt | gum filter)
IP=$(grep $MACHINE < hosts.txt | cut -d'@' -f2)
ssh $IP
```

This will give you the selection menu like this:

```
$ ./ssh-hosts
> Arch
  Debian
  Ubuntu
```

and will perform `ssh 127.1.2.3` when you select.
