### ISSUE TITLE
[enhancement]: keybinds for filter command

### ISSUE THREAD

**Issue by justchokingaround** [charmbracelet/gum#17]
would it be possible to add `ctrl + j` and `ctrl + k` to do the equivalent of what `ctrl + n` and `ctrl + p` respectively, currently do?

**Comment by maaslalani** [comment]
Of course!

**Comment by maaslalani** [comment]
Here you are: https://github.com/charmbracelet/gum/commit/610e054fb51b5a3d83c554fc7583bd768f048580

**Comment by justchokingaround** [comment]
ty 🙏
