### ISSUE TITLE
gum input with a value set should place the cursor at the end of the input

### ISSUE THREAD

**Issue by keevan** [charmbracelet/gum#178]
**Describe the bug**

**To Reproduce**
1. `gum input --value="Something already"`
2. See the cursor is on the S

**Expected behavior**
I expect the cursor to be at the end of the predefined value by default, which in this case is at or just after the `y`.

I normally set a value as a prefix for an input (which the user can remove), but the majority of the time they will continue to type forward.

Note that this also adversely affects the "commit.sh" helper, since the cursor will be at the start of the predetermined commit summary `examples/commit.sh`

**Additional context**
This is happening on 0.7.0, but this issue is not happening on 0.6.0

**Comment by muesli** [comment]
Sounds like a regression in 0.7.0, I do think that's the desired behavior.

**Comment by maaslalani** [comment]
Hi @keevan, thanks so much for creating this issue, it is fixed on the latest `gum` main code! Let us know if it works correctly for you now!

**Comment by keevan** [comment]
@maaslalani awesome. Yes I can confirm this works as expected now. :rocket:

**Comment by maaslalani** [comment]
Sweet, thanks for confirming!
