### ISSUE TITLE
Unable to select alternate values when using choose and --selected flag

### ISSUE THREAD

**Issue by twelvelabs** [charmbracelet/gum#179]
**Describe the bug**

When using the new `--selected` flag (added in #112), I am unable to select alternate values.

**To Reproduce**
1. `gum choose foo bar baz --selected=baz`
2. Press up arrow to highlight "foo", then press return.
3. "baz" is printed to STDOUT

**Expected behavior**

I expected "foo" to be printed.

**Desktop (please complete the following information):**
 - OS: macOS 12.6 Monterey

**Comment by maaslalani** [comment]
Good catch! I believe I know why this is happening, I'll fix soon!

**Comment by maaslalani** [comment]
Fixed in https://github.com/charmbracelet/gum/commit/db75c218de327f7a1c642b23a627efdbfc19c2c1
