### ISSUE TITLE
Add Nix

### ISSUE THREAD

**Issue by tcmal** [charmbracelet/gum#18]
The readme mentions you can install this with `nix-env -iA nixpkgs.gum`, but there isn't an entry in nixpkgs, including the unstable branch.

Ideally, there would be both a flake and a derivation in nixpkgs.

**Comment by maaslalani** [comment]
Hey apologies it should be merged soon! https://github.com/NixOS/nixpkgs/pull/183396

**Comment by maaslalani** [comment]
Gum is now on nixpkgs! https://github.com/NixOS/nixpkgs/pull/183396
