### ISSUE TITLE
Image on click

### ISSUE THREAD

**Issue by CaedenPH** [charmbracelet/gum#185]
**Describe the bug**
When you press the gum logo image in the README, some strange nutritional facts image is shown. I'm not sure if that is intentional, I believe it probably is intentional, however it makes it quite annoying when trying to save the gum logo.

**To Reproduce**
1. Go to the `README`
2. Click on the main gum logo
3. View image

**Expected behavior**
The ability to view the gum logo image in order to save, edit, etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/23421705/194728639-edc76e12-98a6-4c66-ac2a-f10c9988b816.png)

**Comment by maaslalani** [comment]
Hi, this is intentional. You can find the gum logo by clicking "View Raw" on the README (https://raw.githubusercontent.com/charmbracelet/gum/main/README.md) and then visiting the URL of the gum logo:

https://stuff.charm.sh/gum/gum.png
