### ISSUE TITLE
Add gum range element

### ISSUE THREAD

**Issue by CaedenPH** [charmbracelet/gum#187]
**Is your feature request related to a problem?**
I can't make ranges that display how *much* of something, such as 1-100, for example "How happy are you?"

**Describe the solution you'd like**
A new element, a `range` element which can be from value a up to value b, most likely integer.

**Describe alternatives you've considered**

**Additional context**

**Comment by keevan** [comment]
Hi @CaedenPH, you may get around this limitation currently by using one of the following approaches:

`echo {1..100} | tr ' ' "\n" | gum filter --height 5 --placeholder="How happy are you from 1-100?"`

Explainer:
- `{1..100}` gives you the values in your desired range
- `tr` transforms spaces to new lines which is piped into `gum filter` which does the rest.


The shorter alternative is `gum choose {1..100}`, but that would depend on how you want to confirm the value.

**Comment by maaslalani** [comment]
Like @keevan mentioned you can get extremely close to a range element with `gum choose`:

```bash
gum choose {1..10} --height 1 --cursor "" --cursor.margin "1 6"
```


https://user-images.githubusercontent.com/42545625/195203885-d0d6c237-33ba-4094-b2b4-615519acc29b.mov

**Comment by CaedenPH** [comment]
> Like @keevan mentioned you can get extremely close to a range element with `gum choose`:
> 
> 
> 
> ```bash
> 
> gum choose {1..10} --height 1 --cursor "" --cursor.margin "1 6"
> 
> ```
> 
> 
> 
> 
> 
> https://user-images.githubusercontent.com/42545625/195203885-d0d6c237-33ba-4094-b2b4-615519acc29b.mov
> 
> 
> 
> 

Do you think this is the ideal way to make a gum range element? What about a graphically pleasing range element
