### ISSUE TITLE
Format independant Choose items

### ISSUE THREAD

**Issue by Nickiel12** [charmbracelet/gum#19]
Is there a supported way to apply different style colors to different lines in a `choose` menu? What I'm looking for is one line to have red text, and another to have blue text. I'm just asking  because I couldn't find anything in the documentation about it, did I miss it?

Edit: I am trying to pipe in filenames from another command, and it isn't a static list.

**Comment by maaslalani** [comment]
Hey! You can do something like this:

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/42545625/181634894-e8661958-d41f-485d-84b7-b106355df177.png">

**Comment by maaslalani** [comment]
Ah, I see you are trying to pipe in file names. I think the solution is to do pipe the file names into the `gum style` command before you pipe them into `gum choose`

**Comment by maaslalani** [comment]
Do you mind sharing the code you are trying to run and a description of the exact output you'd like, perhaps I may be able to help?

**Comment by Nickiel12** [comment]
Sweet! I'll see if I can make that work! Thank you for the fast response!

**Comment by Nickiel12** [comment]
```SH
formatter(){
    input=$1

    if [[ $input == "??"* ]]; then
        echo $(gum style --foreground 4 ${input:3})
    else
        echo $(gum style --foreground 11 ${input:2})
    fi
}

export -f formatter
git status --short | xargs -I{} bash -c 'formatter "{}"' _ | gum choose --no-limit
```

Here is what I got working!

**Comment by maaslalani** [comment]
Awesome stuff @Nickiel12 !

**Comment by maaslalani** [comment]
> I am making a custom git-cli/user interface for myself, and this was the first step.
> Thank you for an awesome tool! I will be using it for a lot of my scripts now!

If you make anything that you think can be useful to others please share and we will add it to the `examples/` folder or the `README` 🙂
