### ISSUE TITLE
Gum file option --all don't work as excepted

### ISSUE THREAD

**Issue by TheGuit** [charmbracelet/gum#192]
**Describe the bug**
The default value for --all/-a option is true. So when you don't set this option you'll have all hidden file showed, and when you set the option you also have all the hidden file showed.

**To Reproduce**
1. Go to a directory containing hidden file
2. Launch `gum file .`
3. See error : hidden files are displayed

**Expected behavior**
By default hidden file should not be showed. They must be displayed only if option --all/-a is set.

**Code involved**
[If applicable, add screenshots to help explain your problem.](https://github.com/charmbracelet/gum/commit/2bea4dc0301cdc3e89535a7bde078ebf4ccb4062#diff-dcded55714008b30942ff1a4091b7dfa59397337c1a79c6ba988165fdc75d01aR11)

**Desktop (please complete the following information):**
 - OS: Archlinux

**Comment by maaslalani** [comment]
Hey @TheGuit, this is intentional. We want to show hidden files by default since we imagine that it is useful (happy to change this if it is not the case). To hide hidden files you can  run:
```
gum file --all=false
```

**Comment by TheGuit** [comment]
> Hey @TheGuit, this is intentional. We want to show hidden files by default since we imagine that it is useful (happy to change this if it is not the case). To hide hidden files you can run:
> 
> ```
> gum file --all=false
> ```

So the option name is confusing. As the help say : 
> Show hidden and 'dot' files

And the short option doesn't work so (try : `gum file -a=false .`)

My opinion here is : 
- if the default is showing hidden file, the option should be --no-hidden with a documentation update accordingly 
- if the default is not showing hiddent file, the option could stay --all/-a. As pretty much every linux cli command have made the choice to have an --all/-a option that show hidden file, I think gum should have the same behavior

**Comment by maaslalani** [comment]
I believe you're right about the `--all`/`-a` matching most linux CLIs. I've changed the default behaviour of `gum file`.
