### ISSUE TITLE
Add option to return command output resulting from spin command.

### ISSUE THREAD

**Issue by h3rmit-fs** [charmbracelet/gum#20]
When using `gum spin` the output is suppressed (err and out), could you add an option to allow that output to be returned?

**Comment by derricw** [comment]
I'd also like it is `gum spin` would have the same error status as the command it calls, that way I could easily know if it failed.

**Comment by maaslalani** [comment]
👍 This is a great idea. We will definitely add this soon. Perhaps with a `--show-output` flag

**Comment by derricw** [comment]
Awesome, thanks!
