### ISSUE TITLE
Focus in and out of the search field of `gum filter`

### ISSUE THREAD

**Issue by simjnd** [charmbracelet/gum#201]
**Is your feature request related to a problem? Please describe.**
Use `gum filter`, unlike other components you can't scroll using standard keybindings (HJKL). Shortcuts like `g` or `G` don't work. `SPACE` can't be used to toggle selection when it is the only way to do it in `gum choose`.

**Describe the solution you'd like**
Mentioned in #198, enable focusing in and out of the search field of `gum filter`:
- Pressing `S` focuses in the search field
	- Letter keys and spaces are typed in the search field
	- `TAB` toggles selection
	- Arrow keys can be used for scrolling
- Pressing `ESC` focuses out of the search field
	- HJKL and Arrow keys can be used for scrolling
	- `g` for jumping to top, `G` for going to bottom
	- `TAB` and `SPACE` both toggle selection

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/gum/pull/776
