### ISSUE TITLE
gum file - `--directory.border` breaks display

### ISSUE THREAD

**Issue by rsteube** [charmbracelet/gum#203]
**Describe the bug**
`--directory border [border]` breaks `gum file` display

**To Reproduce**
1. `gum file --directory.border thick`
2. move around folder with subdirectories

**Expected behavior**
Border is correctly displayed.

**Screenshots**
[![asciicast](https://asciinema.org/a/zd8SUkkWcM1dDxw8uMzHxjbzT.svg)](https://asciinema.org/a/zd8SUkkWcM1dDxw8uMzHxjbzT)

**Desktop (please complete the following information):**
 - OS: Linux
 - Terminal: st
 - Version 0.8.0

**Additional context**

**Comment by maaslalani** [comment]
Hey @rsteube, thanks for the issue. Unfortunately, gum file won't be able to handle multi-line styles (for now). So in the meantime to avoid this change I've disabled any styles that could cause breakage such as vertical padding and margin as well as borders.

Thanks again for creating this issue!
