### ISSUE TITLE
Consistency of Escape key in input and write commands

### ISSUE THREAD

**Issue by andrewkopplin** [charmbracelet/gum#205]
**Is your feature request related to a problem? Please describe.**
Pressing Escape in the input prompt exits with error code 130, while doing the same in the write prompt exits with 0.

**Describe the solution you'd like**
I feel like Escape key should work the same in both, and should probably both exit with 130 (or 0, but that doesn't seem as logical to me).

**Comment by maaslalani** [comment]
Hey, thanks for opening up this issue. This is now fixed: https://github.com/charmbracelet/gum/commit/b4d7ebf2cb3c55400b666224a42d58b196938f7a

Both will exit with status 130.
