### ISSUE TITLE
[Feature Request] Add flag(s?) to `filter` for file and directory filtering

### ISSUE THREAD

**Issue by jalavosus** [charmbracelet/gum#21]
Currently, passing no choices to `filter` causes it to recursively list every single file, directory, subdirectory, etc. relative to `$PWD`. This is fantastic, however, in parent directories with many (sometimes hundreds or thousands of) files and subdirectories, this can cause `filter` to hang, and also produces output which may very well be useless based on the use-case. 

In light of this, flags related to filtering contents of the current directory might be useful. Some examples:

- `--list-recursive`: Only recurse and show the contents of subdirectories if this flag is passed/true
- `--directories-only`: Only show directories in results

I'll try my hand at a PR implementing the above two flags, as well.

**Comment by maaslalani** [comment]
Hey, so for these cases I'd suggest passing what you want from `stdin`:

No recursive search:
```
ls | gum filter
```

Directories only:

```
ls -d */ | gum filter
```
