### ISSUE TITLE
`gum format` does not syntax highlight code

### ISSUE THREAD

**Issue by octoshrimpy** [charmbracelet/gum#215]
**Is your feature request related to a problem? Please describe.**
I've saved valid javascript and go code in files with their respective extensions, and after `cat <file> | gum format -t code` it spits out the code, but all in grey, not with proper syntax highlight as expected (and as shown in the gif)

**Describe the solution you'd like**
Syntax-highlighted code is the expected outcome, either by using chroma's 

```go
lexer := lexers.Analyse("package main\n\nfunc main()\n{\n}\n")
```

or by passing in a language as a flag in a way [chroma expects](https://github.com/alecthomas/chroma#identifying-the-language), like

```sh
cat file.go | gum format -t code -l go

**Describe alternatives you've considered**

Alternatively, it could also take in a filepath (not contents), although that would make it more confusing:

```sh
format -t code -f ./some/file/path.go
```

**Additional context**
the [format README](https://github.com/charmbracelet/gum/blob/main/format/README.md#code) says that it is using Glamour, and Glamour is using Chroma, however Glamour is only using Chroma [when specifying code blocks](https://github.com/charmbracelet/glamour/search?q=chroma), which Gum [is not specifying language](https://github.com/charmbracelet/gum/blob/57c8c90bfd4a42c1bc58188c57cb39727c3f05d8/format/formats.go#L20).

I'm new to Go, and unsure where to start (can read, not yet write :sweat_smile:), but this issue should provide enough linkylinks for someone with more Go-fu than I to implement a language feature!

**Comment by xtherebellion** [comment]
I also do not see syntax highlighting whether I run format type code or markdown (I've tried both Go and Python), would definitely like to know a fix or workaround for this.

**Comment by maaslalani** [comment]
@octoshrimpy Can you check if this is still an issue:

```
gum format -t code < main.go
```

Is working correctly for me.

**Comment by octoshrimpy** [comment]
It appears it is still an issue, at least with python
![2023-03-15_00-39](https://user-images.githubusercontent.com/7097172/225227193-a81cd506-e0b3-4687-8d39-e36a269e622d.png)

**Comment by maaslalani** [comment]
@octoshrimpy Which version of gum are you using? Do you mind trying with the latest main code?

**Comment by octoshrimpy** [comment]
just cloned the repo (master) and ran it, same thing:
![2023-03-15_00-48](https://user-images.githubusercontent.com/7097172/225228720-5b193c55-76d0-4af5-9c55-14b20eec0972.png)

**Comment by octoshrimpy** [comment]
can this issue be re-opened? in latest stable from AUR and alpine repos it won't highlight anything still, and output comes out as gray, like the screenies above.

**Comment by octoshrimpy** [comment]
@maaslalani could you clone and test a fresh version of gum master branch, for sanity check? it's been more than 5 months..

**Comment by octoshrimpy** [comment]
![image](https://user-images.githubusercontent.com/7097172/227374627-e193612a-fb50-4c4e-a58a-f778ad4f2504.png)
it appears even the format usage within`test.sh` fails.

**Comment by maaslalani** [comment]
Hey @octoshrimpy, cloned latest `gum` on master / main branch.

<img width="1562" alt="image" src="https://user-images.githubusercontent.com/42545625/227380626-dc156a15-15a6-4770-ba52-930659716f92.png">

**Comment by maaslalani** [comment]
This is also with the `test.sh` script:

![Uploading image.png…]()

**Comment by octoshrimpy** [comment]
@maaslalani what OS and terminal are you using? I'm on arch, this has been tested with alacrity, konsole, xterm, kitty,  wezterm; none of them show the format correctly, however they do render everything else fine.

**Comment by octoshrimpy** [comment]
it works when running source directly:
![image](https://user-images.githubusercontent.com/7097172/227431384-33f68415-d72e-4a81-b50a-743e3c24d7b5.png)

**Comment by octoshrimpy** [comment]
does not work with any other filetype other than go..?
![image](https://user-images.githubusercontent.com/7097172/227431952-4d28106c-350d-423d-bb97-ab15b561506e.png)
![image](https://user-images.githubusercontent.com/7097172/227431984-fff5e371-a961-4114-b580-495674fc1966.png)

**Comment by maaslalani** [comment]
It appears as though sometimes the language autodetection doesn't work, I've added #323 to allow specifying the language so that highlighting appears correctly.

<img width="618" alt="image" src="https://user-images.githubusercontent.com/42545625/227585298-449149e8-f271-4aa9-be10-2af3cd777ee8.png">

**Comment by octoshrimpy** [comment]
![image](https://user-images.githubusercontent.com/7097172/227634230-15daaf4b-fc07-41f7-895c-9ccde6d42952.png)
![image](https://user-images.githubusercontent.com/7097172/227634262-20aee41e-5c30-4363-b150-603bc1b398a5.png)
can confirm it all works!

**Comment by maaslalani** [comment]
Awesome, thank you!
