### ISSUE TITLE
Header/footer content for gum input

### ISSUE THREAD

**Issue by neezer** [charmbracelet/gum#216]
### Request

I'd like the `--header` option (and a matching `--footer` option) from `gum write` on `gum input`.

### Why?

I have a script that collects information (usernames and tokens--all single values) from a user through a series of prompts, which sometimes contain explanatory text and/or external links to documentation in order to guide the user to enter in the correct values.

Since `gum input` clears itself on submission, I can't echo around them because the echoed messages persist and appear out-of-context. It's a very similar issue to what's outlined in #80, except that the [fix](https://github.com/charmbracelet/gum/pull/176) for that only applied to `gum write` and not `gum input` (and only provided `--header` and not `--footer`).

I'd like either of the following:

1. a way for `gum input` prompts to remain after submission so that the echo statements I place around them don't loose context
1. a way to provide multi-line header and/or footer content for `gum input` that gets cleared when `gum input` clears itself

Bonus points if I can provide fancy text from `gum style` and/or `gum format` as the content for `--header`/`--footer`.

### Workaround

For now, I'm manually re-creating the prompts after submission like so:

```bash
#!/bin/bash

echo ""

prompt="  Your Github Username: "
gh_user=$(gum input --prompt="$prompt") || exit

echo "$prompt$gh_user" # <-- manually re-creating what I saw before gum input cleared
echo ""

cat <<'EOF' | gum format
You need to create a GitHub Personal Access Token with at least the
following permissions:

- admin:public_key
- read:org
- read:user
- repo
- user:email

For details on how to create a Personal Access Token, see
https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

*NOTE*: GitHub is rolling out a Beta program for creating
"Fine-grained tokens"--for now, opt to create a "Tokens (classic)" token.
EOF

echo ""

prompt="  Your Github Personal Access Token: "
gh_pac=$(gum input --prompt="$prompt" --password) || exit

echo "$prompt$(echo $gh_pac | sed 's/./•/g')"  # <-- manually re-creating what I saw before gum input --password cleared
echo ""

# ... the rest of my script, which includes more prompts
```

This workaround is for the "don't clear inputs after submission" approach (#&#8203;1 in the list above). Without this, the explanatory text meant to accompany the prompt for the personal access token persists when the next prompt appears, which is confusing to the user.

I couldn't think of a workaround for the "`--header`/`--footer` that show multiline rich content and get cleared with the inputs" approach (#&#8203;2 from the list above). 😢

**Comment by maaslalani** [comment]
Hey, thanks for creating this issue, I've added `--header` and `--header.` styles for `gum input` so that you can add headers to this text which will disappear when submitted.

```bash
gum input --header Hello --header.foreground 240
```
