### ISSUE TITLE
Package as lib

### ISSUE THREAD

**Issue by svallory** [charmbracelet/gum#224]
**Is your feature request related to a problem? Please describe.**
It would be awesome if we could use gum as a library. That would enable CLI programs developed in any language that supports ffi to use gum

**Describe the solution you'd like**
A `gum.so` so I can call gum programmatically from the CLIs I develop using typescript and Deno

**Describe alternatives you've considered**
I've considered adding the code to export C-functions myself by it would be a hassle to maintain them up to date in a fork

**Comment by maaslalani** [comment]
Hey @svallory! Thanks for the issue. We recently released `huh?`: https://github.com/charmbracelet/huh which does allow for all of the components in `gum` to be run in Go as a library. Hopefully this is helpful to you!

**Comment by svallory** [comment]
> Hey @svallory! Thanks for the issue. We recently released `huh?`: https://github.com/charmbracelet/huh which does allow for all of the components in `gum` to be run in Go as a library. Hopefully this is helpful to you!

I know :) I follow the work you guys do closely. Every now and then I even check for job openings. Can't wait to have a charming job :)

I think you can close this issue. `huh?` does seem to give me what I need.

Btw, thank you for that!

**Comment by meowgorithm** [comment]
Closing now that Gum and Huh have converged :)
