### ISSUE TITLE
Use gum as completer in bash/zsh?

### ISSUE THREAD

**Issue by dmd** [charmbracelet/gum#225]
Is it possible to use `gum file` as the tab completer in bash/zsh? Has anyone done this?

**Comment by maaslalani** [comment]
I have this in my dotfiles:

```
      function fs() {
        BUFFER+="$(gum filter)"
        zle -w end-of-line
      }
      zle -N fs
      bindkey "^t" fs
```

Which allows me to press `Ctrl+t` to bring up a list of all files and fuzzy find for the one I want. You can definitely do something similar with `gum file`. Not entirely sure about tab completion though.
