### ISSUE TITLE
Bug: gum style

### ISSUE THREAD

**Issue by Simon-He95** [charmbracelet/gum#231]
use demo code in my terminal
<img width="494" alt="image" src="https://user-images.githubusercontent.com/57086651/200784955-037dfa19-d1b0-4dc5-b76b-05a34c2a326a.png">

**Comment by meowgorithm** [comment]
Hi! This is most likely an issue related to your encoding. See: https://github.com/charmbracelet/lipgloss/issues/40

**Comment by Simon-He95** [comment]
@meowgorithm thanks for your help, the problem has been solved.
Add into .zshrc
```
export LC_CTYPE="en_US.UTF-8"
```
