### ISSUE TITLE
encoding issue

### ISSUE THREAD

**Issue by lost22git** [charmbracelet/gum#240]
Run on powershell

--placeholder='请选择颜色'

```
$s=@('黑色','白色','红色','蓝色') | gum filter --no-limit --placeholder='请选择颜色' | Where {$_ -notmatch 'failed'}
```

![image](https://user-images.githubusercontent.com/65008815/202441242-57ff53ed-4f14-4610-895a-a0dabeceb9f5.png)

and filter text can not input unicode chars

**Comment by lost22git** [comment]
If i add  --placeholder=' 请选择颜色🤔' with \<space\> as prefix, it can show correctly.

![image](https://user-images.githubusercontent.com/65008815/202445498-e2a776a1-e4a6-4b5f-8d2a-09380365fe99.png)

But filter text still can not input unicode chars 🤔

**Comment by rm-dr** [comment]
I tried to reproduce this on linux, and the results are the same. Characters are not rendered unless a leading space is added.

This seems to be a problem in bubbles, caused by the multi-codepoint glyphs you're using. I'll try to get this patched.

**Comment by rm-dr** [comment]
As for input, how are you trying to input characters to the prompt? This may be a problem with powershell and not gum, since table-based keyboard layouts (like chinese via pinyin) don't work in all applications.

Copy-pasting chinese characters into the filter bar works perfectly well.

**Comment by lost22git** [comment]
As for chinese pinyin input, fzf works well. so maybe not a problem of powershell.
