### ISSUE TITLE
gum filter hope to support top up back to bottom

### ISSUE THREAD

**Issue by Simon-He95** [charmbracelet/gum#244]
1. The first point hopes to enhance the function:
sometimes the choice is very similar， we need to input many details to filter.
Might it is near the last option, I hope to arrow up directly to the end. It's more convenient.
2. The second point hopes to enhance the function:
In addition, when updating input, I hope to rest the current back to the top. Because the top option is the most probably needed option. It will be more comfortable to operate.

**Comment by caarlos0** [comment]
I'm not sure if I understand what you meant, but if the idea is to allow to "circle" the navigation in gum filter, that's already implemented.

If not, please clarify. 

Closing for now, though. Thanks!

**Comment by Simon-He95** [comment]
I have updated the latest version, It's nice to me, thx~
