### ISSUE TITLE
Color List Chart

### ISSUE THREAD

**Issue by BlueFalconHD** [charmbracelet/gum#245]
**Is your feature request related to a problem? Please describe.**
When using Gum, Lipgloss, Bubbletea, or others, the color styling is unclear. Using the terminal-set colors, 1-12, I believe, is difficult because I cannot find a chart that lists the standard names of the colors easily, and I am colorblind so the chart I found where it just says a number on top of a color isn't helpful because I have no idea what color it is.

**Describe the solution you'd like**
I would like a chart to be added in the README of Gum, Lipgloss, and Bubbletea

**Describe alternatives you've considered**
Another solution would be to either have an extra repository for this info, which seems a bit extra, or have a color chart markdown file somewhere in the codebase of Lipgloss, and link to that in any necessary READMEs, which seems like a good idea.

**Additional context**
- I am colorblind, and I really get annoyed when things are unclear in the sense of colors. Though I cannot enjoy the color truly myself, if I am building a TUI or shell script, I would still like others who use it to have a good experience.

**Comment by olivertzeng** [comment]
i would like it to be true! i aint colorblind but i really need this feature!

**Comment by olivertzeng** [comment]
https://github.com/muesli/termenv#color-chart @BlueFalconHD

**Comment by JKrag** [comment]
@BlueFalconHD I found this [256 Colors Cheat Sheet](https://www.ditig.com/256-colors-cheat-sheet) that lists quite descriptive names for all the 256 XTerm colours. 
I believe they match with the ones Gum uses, at least for the ones I have tried so far.

**Comment by caarlos0** [comment]
the cheat sheet provided by @JKrag solves this.

closing! thanks everyone!

**Comment by meowgorithm** [comment]
As a bonus, there's a secret little example in Lip Gloss that you can use to render a color table in your terminal as well:

https://github.com/charmbracelet/lipgloss/blob/master/examples/table/mindy/main.go

This is what it looks like:

<img width="792" src="https://github.com/user-attachments/assets/105d13f1-3c66-40ac-b330-42af34ae15ce">
