### ISSUE TITLE
Horizontal scrolling with `gum pager`

### ISSUE THREAD

**Issue by GoByeBye** [charmbracelet/gum#246]
**Is your feature request related to a problem? Please describe.**
I've been using gum heavily lately and just started using pager. One thing I've noticed is that longer lines of text (depending on font size and screen resolution) get cut off and there's no way to scroll horizontally to see what text got cut off (see image)

**Describe the solution you'd like**
I'd like to have the ability to scroll horizontally with the pager if there's any text outside of the space available instead of it getting cut off fully. Maybe a solution like ubuntu's default pager?

**Additional context**
![image](https://user-images.githubusercontent.com/33762262/204262788-4a2af4bf-b846-4248-8230-d1282639a3e7.png)

**Comment by Stoux** [comment]
Would love to see this! Alternatively / additionally: allow for a `--soft-wrap` option that wraps the lines into new lines without increasing the line numbers.

**Comment by Stoux** [comment]
@GoByeBye Might (most likely) be wrong but couldn't see a way of moving the viewport horizontally. It seems to always just truncate it. Did make a PR for the `--soft-wrap` option tho.

**Comment by GoByeBye** [comment]
> @GoByeBye Might (most likely) be wrong but couldn't see a way of moving the viewport horizontally. It seems to always just truncate it. Did make a PR for the `--soft-wrap` option tho.

Awesome that you made the pr!
Honestly, a soft wrap is more than enough, the scrolling with the arrow keys horizontally was just the first thing I could come up with. Can't wait to see this in the next version of Gum. Good job! :)

**Comment by maaslalani** [comment]
Awesome! Thanks for opening up this issue @GoByeBye. @Stoux implemented soft-wrapping which looks like solves this issue so I will close it for now. Definitely reopen this issue or open another if you ever need horizontal scrolling.
