### ISSUE TITLE
inconsistent handling of spaces which precede list items

### ISSUE THREAD

**Issue by causality-loop** [charmbracelet/gum#247]
**Describe the bug**
if an item in a list contains spaces before it, sometimes those spaces are not removed, however sometimes they are removed, but for the first item only.

**To Reproduce**
works as expected:
```
gum choose "  one"  "  two"  "  three"
```
removes spaces which precede only the first list item: 
```
echo -e "  one\n  two\n  three" | gum choose
echo -e "  one\n  two\n  three" | gum filter

echo -e "  one\n  two\n  three" > numbers.txt
cat numbers.txt | gum choose
cat numbers.txt | gum filter
```

**Expected behavior**
for the spaces not to be removed.

**Desktop (please complete the following information):**
- Fedora 37
- Gum v0.8.0

**Comment by maaslalani** [comment]
Thank you for creating this issue, it is now fixed in: https://github.com/charmbracelet/gum/commit/c8e6b4a9d5aa4c7a8d8018584d32bfde45c1dbdf

**Comment by causality-loop** [comment]
@maaslalani thank you!
