### ISSUE TITLE
[Feature] Allow filter with no limits, like `fzf --multi`.

### ISSUE THREAD

**Issue by pbnj** [charmbracelet/gum#25]
### Problem

I am trying to achieve something similar to `fzf --multi` functionality where I can pipe/filter output from one program through `gum` for (1) fuzzy-finding and (2) selecting multiple options.

I can accomplish one or the other, like:

- `gum choose --no-limit` but I cannot fuzzy search, or
- `gum filter` but I cannot select multiple options.

### Info

```shell
$ brew info gum
charmbracelet/tap/gum: stable 0.1.0
```

### Repro Steps

```shell
$ echo -e "abc\ndef\nghi\njkl\nmno\npqr\nstu\nvwx\nyz" | gum choose --no-limit
# cannot type anything
```

```shell
$ echo -e "abc\ndef\nghi\njkl\nmno\npqr\nstu\nvwx\nyz" | gum filter
# cannot select multiple options
```

### Possible Solution

Since `gum filter` already has fuzzy finding algorithm implemented, so it might be a relatively easier lift to implement multi-selection with something like `--no-limit` (similar to `gum choose`) and <kbd>TAB</kbd> (not <kbd>SPACE</kbd> since it could be part of the search pattern/string) to select the current line and move the pointer to the next line.

**Comment by Nickiel12** [comment]
I would also like a feature like this, because the fuzzy feature is awesome. 
Maybe the selected items could be stickied to the top of the search results? I don't know.

**Comment by maaslalani** [comment]
Hey, thank you for this very well written issue ❤️

The proposal sounds very reasonable to me!

**Comment by maaslalani** [comment]
This is now implemented in #130 thanks to @fedeztk!

```
gum filter --no-limit
```

**Comment by maaslalani** [comment]
Ah yes! Adding this to the README right now, thank you @miridius!

**Comment by vogler** [comment]
> Adding this to the README right now

It doesn't mention tab.

Also, it's not ideal that `gum choose` only works with space and not tab.
I use both in a script - would be nicer to just tell people in the beginning that they can select multiple items with tab.
