### ISSUE TITLE
Bug: border does not display correctly

### ISSUE THREAD

**Issue by ChloroplastYu** [charmbracelet/gum#250]
**Describe the bug**
"gum style --border" does not display correctly

**To Reproduce**
Any gum style command with flag --border

**Screenshots**
![image](https://user-images.githubusercontent.com/51773819/206379599-13a0dc49-c0bc-4f11-a4e6-2e8ab84a5298.png)

![image](https://user-images.githubusercontent.com/51773819/206379241-ef224267-0061-4399-8dc5-641662ceb63e.png)

**Desktop (please complete the following information):**
 - OS: masOS 13.0.1
 - Version: gum stable 0.8.0

**Comment by maaslalani** [comment]
Hey! This looks like an issue related to your encoding. See #115 

Try the following and rerun the command:

```
export LC_CTYPE="en_US.UTF-8"
```

**Comment by maaslalani** [comment]
Duplicate:
* https://github.com/charmbracelet/gum/issues/231
* https://github.com/charmbracelet/gum/issues/115

**Comment by polm** [comment]
I also had this issue, and `LC_CTYPE="en_US.UTF-8"` does not fix it for me, even though I have that locale on my system. Setting `RUNEWIDTH_EASTASIAN=0` works though (and the value doesn't actually seem to matter).

**Comment by ChloroplastYu** [comment]
> Hey! This looks like an issue related to your encoding. See #115
> 
> Try the following and rerun the command:
> 
> ```
> export LC_CTYPE="en_US.UTF-8"
> ```

It work! Thanks!
