### ISSUE TITLE
Support VIM Keybindings

### ISSUE THREAD

**Issue by Rawnly** [charmbracelet/gum#251]
**Is your feature request related to a problem? Please describe.**
I'd like to have support for `C-<j/k>` keybindings

**Describe the solution you'd like**
Usually, when I receive a list to choose from inside the terminal I'd expected to be able to navigate the list with `Ctrl-J` and `Ctrl-K`

**Describe alternatives you've considered**
keep the behavior as it is.

**Additional context**
Tested in `Alacritty` and `iTerm 2` with `zsh` and `tmux` (also without tmux)

https://user-images.githubusercontent.com/16429579/206684905-26991dd5-89b2-4efa-a674-4d4ae51e7653.mp4

**Comment by maaslalani** [comment]
Thanks for creating this issue, functionality is now available!

**Comment by Rawnly** [comment]
> Thanks for creating this issue, functionality is now available!

Thanks!
