### ISSUE TITLE
.csv files with long strings are hidden by "..."

### ISSUE THREAD

**Issue by olivertzeng** [charmbracelet/gum#258]
**Describe the bug**
.csv files with long strings are hidden by "..."

**Expected behavior**
Text not hidden

**Screenshots**
https://asciinema.org/a/549864

**Desktop**
 - OS: [macOS 10.15.7]
 - Browser [Brave]
 - Version [Latest]

**Comment by olivertzeng** [comment]
yes i did but it didnt work(worked for a bit)

**Comment by olivertzeng** [comment]
@rm-dr

**Comment by rm-dr** [comment]
Details?

What does your script look like?
When did it work, when did it stop?

How can I reproduce this on my machine?

**Comment by olivertzeng** [comment]
run palera1n.sh on https://github.com/olivertzeng/palera1n

**Comment by olivertzeng** [comment]
rec:https://asciinema.org/a/552781
@rm-dr

**Comment by olivertzeng** [comment]
Yes, but I am still having this but at least a little better, check my pull request in palera1n/palera1n please
Sent from Proton Mail for iOS

於 週四, 1月 19, 2023 時間 03:35, Frost ***@***.***> 寫道：

**Comment by olivertzeng** [comment]
https://camo.githubusercontent.com/db67aa20d4a36613c9e727c68cd6e1be115f8debba2ce06f63a5740e8acd24f1/68747470733a2f2f73747566662e636861726d2e73682f67756d2f7461626c652e676966

**Comment by olivertzeng** [comment]
@rm-dr for example in their own README some strings are shown hidden

**Comment by rm-dr** [comment]
Notice how `--widths` takes a comma-separated list of values. Each element in that list is the width of a column.

Any table entry wider than the column allows will be hidden. This is what is happening in the README, and this is what is happening to you. `-w 50` only sets the width of the first column.

**Comment by olivertzeng** [comment]
@rm-dr you're really helpful! but...
    https://asciinema.org/a/553822

**Comment by rm-dr** [comment]
You have three columns. You're only specifying width for two.

**Comment by olivertzeng** [comment]
oh i know what you mean now

**Comment by olivertzeng** [comment]
@rm-dr thanks, problem solved!
