### ISSUE TITLE
gum format

### ISSUE THREAD

**Issue by olivertzeng** [charmbracelet/gum#268]
`gum format` can use emojis `-t emoji` while having the list `--`

**Additional context**
[Asciinema](https://asciinema.org/a/553539)

**Alternative examples**
`gum format -- "## Made with $(gum format -t emoji ":heart: by")" "- Nebula" "- Mineek" "- Nathan" "- llsc12" "- Ploosh" "- Nick Chan" "- Oliver Tzeng" "- and charmbracelet"
`

**Comment by caarlos0** [comment]
seems to be working on main

![CleanShot 2024-12-09 at 17 08 58@2x](https://github.com/user-attachments/assets/069cd3a8-2437-4520-b529-3b89b78fdec1)


thanks for the issue!

**Comment by olivertzeng** [comment]
> seems to be working on main
> 
> 
> 
> ![CleanShot 2024-12-09 at 17 08 58@2x](https://github.com/user-attachments/assets/069cd3a8-2437-4520-b529-3b89b78fdec1)
> 
> 
> 
> 
> 
> thanks for the issue!

Glad 😊

**Comment by olivertzeng** [comment]
> seems to be working on main
> 
> 
> 
> ![CleanShot 2024-12-09 at 17 08 58@2x](https://github.com/user-attachments/assets/069cd3a8-2437-4520-b529-3b89b78fdec1)
> 
> 
> 
> 
> 
> thanks for the issue!

I'll try it out later!

Tbh I was kinda confused about this issue that I created a while ago but after reviewing the asciinema I'm glad that this issue is fixed
