### ISSUE TITLE
[Feature request] add `ctrl+@`(`ctrl+space`) keybinding for `choose` and `filter`

### ISSUE THREAD

**Issue by MuXiu1997** [charmbracelet/gum#275]
**Is your feature request related to a problem? Please describe.**

As a vim and fzf user, I like to use `ctrl+j` and `ctrl+k` to move the cursor, often holding down ctrl.
Using `tab` and `shift+tab` is great for a lot of consecutive selections, but it's not great if I need to select a few while moving, I may have to repeatedly release and press my ctrl key. So I'd like to use `ctrl+space` as a toggle selection key bind.

**Describe the solution you'd like**

Add `ctrl+@`(`ctrl+space`) keybinding for `choose` and `filter`

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by deicon** [comment]
This sounds like a more general request to allow some customization of key bindings for example.
