### ISSUE TITLE
gum spin is not working with sudo commands

### ISSUE THREAD

**Issue by matheustanaka** [charmbracelet/gum#279]
**Describe the bug**
I'm using ffmpeg to join a video with subtitle. When I try to run commands with "sudo", gum spin doesn't ask for sudo password and keep loading forever. If I try to run it without gum spin, it works. But I would like to use gum spin it if it's possible.

**To Reproduce**
- To reproduce the error you can run any command with sudo, but if you want to try it with ffmpeg you should download a .mp4 file with a subtitle .ass format.
```shell
$ gum spin --title "Juntando o Vídeo com a Legenda ..." -- sudo ffmpeg -i "$VIDEO" -vf ass="$SUBTITLE" content.mp4
```

**Expected behavior**
gum spin ask for sudo password or stop the command

**Screenshots**
- My terminal crash and I can't stop it.
![image](https://user-images.githubusercontent.com/59452094/219116998-15c65a8d-ebbb-4d6f-b309-f159d6de39ad.png)

**Desktop (please complete the following information):**
 - OS: [Pop!OS 22.04]
 - ffmpeg: [5.1.2]

**Additional context**
I'm open the issue as a bug, but i don't know exactly if gum spin can't handle with "sudo" commands. If gum spin can't work with it, sorry for my mistake

**Comment by RochaLAJ** [comment]
Any script that requires an answer (sudo, pacman -Syu/dnf update/apt update) isn't working with spin.

**Comment by caarlos0** [comment]
hey!

that's to be expected.

the command running inside spin does not have a terminal stdin. 

as a workaround, you can run sudo before calling gum spin, as the next call shouldn't ask for the password again.

that said, closing this!
