### ISSUE TITLE
[feature request] `--print-query` in gum filter

### ISSUE THREAD

**Issue by saccarosium** [charmbracelet/gum#280]
I'm writing a shell script where I need to print the query if no match is found (like the flag `--print-query` in fzf).

### Wanted behaviour
![fzf](https://user-images.githubusercontent.com/96259932/219388707-7380069f-acc4-4b88-9628-13e9093fb79f.gif)

**Comment by maaslalani** [comment]
Hey I believe we actually have that feature built-in already it's called the `--no-strict` flag.

```
ls *.md | gum filter --no-strict
```
<img width="469" alt="image" src="https://user-images.githubusercontent.com/42545625/224115830-3594505c-1ae0-4a4f-9428-004bd0d53de7.png">
