### ISSUE TITLE
[feature request] gum choose want to set defaultValue

### ISSUE THREAD

**Issue by Simon-He95** [charmbracelet/gum#282]
maybe like `gum choose --default "b" "a" "b", want to start to choose with b

**Comment by deicon** [comment]
This should do what you are looking for I guess

gum choose --selected "b" "a" "b"

<img width="363" alt="image" src="https://github.com/charmbracelet/gum/assets/3485445/bad183da-61cc-46f1-a29b-7a74cb22feb4">

**Comment by maaslalani** [comment]
Thanks @deicon! Yeah I think that should solve this issue:

```
gum choose a b c --selected b
```
