### ISSUE TITLE
In gum table, escape key does not quit

### ISSUE THREAD

**Issue by hydrargyrum** [charmbracelet/gum#286]
**Describe the bug**
In gum table, escape key does not quit

**To Reproduce**
1. run `gum table <<< "a,b" <<< "1111111111111,2222222222"`
2. press escape
3. gum did not exit :(

**Expected behavior**
gum table exits with an error, just like `gum input` or `gum choose`

**Desktop (please complete the following information):**
 - OS: debian
 - Version https://github.com/charmbracelet/gum/releases/tag/v0.9.0

**Comment by maaslalani** [comment]
Fixed by #290
