### ISSUE TITLE
the behavior of `--value` is non-obvious

### ISSUE THREAD

**Issue by masukomi** [charmbracelet/gum#29]
[edit] this was a ticket proposing the addition of a `--default` option. It turns out that that was user error / ignorance on my part BUT the documentation should still be improved to make it clear what `--value` does and how it behaves. (see comment below)

**Comment by masukomi** [comment]
for those coming from google, here's one way you could do a default value with the current `--placeholder` only version: 

```
function input_or_default () {
	local default="$1"
	local input=$(gum input --placeholder "$default")
	[ -n "$input" ] || input="$default"
	echo "$input"
}

x=$(input_or_default "foo")
echo "input: $x"
```

**Comment by masukomi** [comment]
Turns out this is actually a documentation problem, not a code problem

 `--value` serves this function and the visual choice was 

```
> default
```

# Suggested changes:
the help docs say 

```
      --value=""                           Initial value (can also be passed via stdin)
```

they fail to note 3 important things:
1.  `--value` supersedes `--placeholder`  and any placeholder will _not_ be displayed
2.  the value will be editable
3.  unlike placeholder the value will be returned if the user just hits enter. 


I still think `--default` would be a better name for this because it's more self-evident what to expect from it. Maybe we could deprecate ( support but stop mentioning ) value and replace it with `--default` as well as the suggested documentation?

**Comment by polm** [comment]
These value names and their behavior (like how `placeholder` is ignored if `value` is set) are the same as the HTML `<input>` element.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#placeholder

**Comment by maaslalani** [comment]
@polm This is a great point:

The `--value` and `--placeholder` flags behave the same as their counter parts in HTML which I think is beneficial. We might revisit this naming but I this @polm has a great point that these match HTML and I think it makes sense to keep them like this for the time being unless there is a much stronger argument to deviate.

**Comment by masukomi** [comment]
i believe this ticket has been closed prematurely:

even if you don't change anything about the naming or behavior , there's still the outstanding problems noted above of missing documentation and the example that can't possibly work.

**Comment by maaslalani** [comment]
> i believe this ticket has been closed prematurely:
> 
> 
> 
> even if you don't change anything about the naming or behavior , there's still the outstanding problems noted above of missing documentation and the example that can't possibly work.
> 
> 

We can definitely document this behaviour 👍

The example works correctly, the placeholder value will show up if the value (that is pre-filled) is deleted by the user, as shown in the example.
