### ISSUE TITLE
No Carriage Returns when writing output from Ruby (Windows Terminal)

### ISSUE THREAD

**Issue by amreus** [charmbracelet/gum#291]
I assume this is related to some of the other issues mentioning the console not being reset.

Given this Ruby script:

```ruby
puts 'What is your name?'
name = `gum input --placeholder "Your name"`
puts "result: #{name.inspect}"
# Eat the "handle is invalid" error text
err, name = name.split("\n")
puts "name: #{name.inspect}"
puts "Hello, #{name}!"
puts "Done."
```

Output produced has newlines but lacks carriage returns:

```text
result: "failed to get console mode for stdout: The handle is invalid.\nJim\n"
                                                                              name: "Jim"
                                                                                         Hello, Jim!
                                                                                                    Done.
```

**Expected behavior**

The expected output should look like this:

```text
result: "failed to get console mode for stdout: The handle is invalid.\nJim\n"
name: "Jim"
Hello, Jim!
Done.
```

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Windows Terminal 1.16.230126001 (also happens using plain old cmd.exe)
 - gum version  v0.9.0 (832c4fc) installed with `scoop`
 - ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]

**Comment by caarlos0** [comment]
not related to gum, I'm afraid.

it seems ruby is printing the strings, and ruby is not doing `\r\n` properly.
