### ISSUE TITLE
Pager doesn't render man pages properly

### ISSUE THREAD

**Issue by derricw** [charmbracelet/gum#297]
`gum pager` seems to not render the `|` on the right side properly.

Using gum 0.9.0:
```
export PAGER="gum pager"
man tar
```

![Screenshot from 2023-03-08 15-33-05](https://user-images.githubusercontent.com/2973924/223876818-38dde3fd-e446-43b3-a7a4-4025ee059e88.png)

**Comment by maaslalani** [comment]
Should be fixed by #306, thanks to @MikaelFangel!
