### ISSUE TITLE
Pager cuts off long URLs

### ISSUE THREAD

**Issue by ubuntudroid** [charmbracelet/gum#310]
**Describe the bug**
If the content contains URLs longer than a line they will be cut off somewhere in the middle of the line).

**To Reproduce**
Write a simple shell script that `echo`s a long URL. Then pipe that to `gum pager`.

**Expected behavior**
URLs should be preserved and properly soft-wrapped even if soft-wrap is switched off for the rest of the content.

**Screenshots**
From a little script I did which queries producthunt's API:

### Without pager

![CleanShot 2023-03-18 at 18 09 19](https://user-images.githubusercontent.com/519867/226122189-0f9029ea-608d-413a-96f6-789d468da8ed.png)

### With pager

![CleanShot 2023-03-18 at 18 08 56](https://user-images.githubusercontent.com/519867/226122194-bdf0771a-af62-460a-ac22-52e6d9f21f74.png)

### With pager and soft-wrap

![CleanShot 2023-03-18 at 18 11 50](https://user-images.githubusercontent.com/519867/226122275-9fb513db-f569-4be8-98fb-c6196d76ba42.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - 0.9.0

**Smartphone (please complete the following information):**
 N/A

**Comment by MikaelFangel** [comment]
Hi @ubuntudroid,
I've tested this issue with version v.0.11.0 and can't seem to reproduce it. Can you confirm if this issue persist if you upgrade?

**Comment by ubuntudroid** [comment]
@MikaelFangel doesn't seem to happen anymore indeed! 👍
