### ISSUE TITLE
Gum Table - Add --return-column & --show-columns

### ISSUE THREAD

**Issue by CaelFrost** [charmbracelet/gum#320]
**Is your feature request related to a problem? Please describe.**
Rematching data from the selected row to the source table, so that once a choice is made the script can use the full row data versus the subset shown in gum table. 

**Describe the solution you'd like**

- When sending data in as a table, I often want to include an index column but not show that column to the user in the TUI. 
     not sure if the right choice is to use --show-columns or --hide-columns, but either would solve my need
- Once the user makes the selection, having gum table return ONLY the columns specified in --return-column=0 will cause gum table to only return the first column of each row, and allows the script to use this returned data to refilter the source table for only the indexes specified.

**Describe alternatives you've considered**
currently adding a 'index' column but this is shown to the user

**Additional context**

**Comment by deicon** [comment]
#415 Should fix the request for the return value

**Comment by deicon** [comment]
I prefer to use 1 if referring to the first column in user facing command args.

**Comment by deicon** [comment]
https://github.com/charmbracelet/bubbles/pull/412 Will be needed to support the hiding feature. 
Once and If this will be merged to bubbles, I will create a PR here for the --hide-columns feature

**Comment by caarlos0** [comment]
we could probably change the table after parsing the CSV and remove the columns we don't want, or something like that...

**Comment by deicon** [comment]
The return column should be possible now. Hiding columns should also be possible by setting width to 0?

**Comment by caarlos0** [comment]
yes, you're right, columns can be hidden by providing `--widths=10,0,10` (to hide the 2nd column for example).

thanks @deicon , will close this!
