### ISSUE TITLE
Multiple style in header text.

### ISSUE THREAD

**Issue by NotReallyEight** [charmbracelet/gum#330]
**Is your feature request related to a problem? Please describe.**
I need to have multiple styles in a text, as currently I would like to use a header with a part of the text of a colour and the other part of the text of another colour, but I can't do it right now because it's not supported, as far as I could see.

**Describe the solution you'd like**
A way of adding multiple styles to text, so that for example I can divide a `--header` text in some way and with each "section" of the text being able to put the various styles.

**Describe alternatives you've considered**
I've tried to use an inline `echo`, but of course it gets automatically cleared out whenever I change the chosen option, so that is not a fix for this.

**Additional context**
![image](https://user-images.githubusercontent.com/71493060/229577831-f4e0f988-23c8-4be6-b856-152e74fc268d.png)
Here is a screenshot of a sort of implementation structure demo.

**Comment by maaslalani** [comment]
Hey there, you can do something like this:

<img width="1082" alt="image" src="https://user-images.githubusercontent.com/42545625/229581211-6dcf0655-fc6f-4e55-bcd5-59729b1159db.png">

**Comment by maaslalani** [comment]
```
gum choose --header "$(gum style --foreground "#FF0000" HELLO) $(gum style --foreground "#00FF00" WORLD)" A B C
```

**Comment by NotReallyEight** [comment]
> Hey there, you can do something like this:
> 
> <img alt="image" width="1082" src="https://user-images.githubusercontent.com/42545625/229581211-6dcf0655-fc6f-4e55-bcd5-59729b1159db.png">

Yes, that was exactly what I was searching for. Thanks!
