### ISSUE TITLE
reduce binary size

### ISSUE THREAD

**Issue by rpodgorny** [charmbracelet/gum#331]
this tool is cool! really! ...but the binary is huge. :-( ...that makes embedding it really painful.  ...is there a way to reduce the binary size?

**Comment by MikaelFangel** [comment]
Don't know if it is at any help, but you can get a small reduction by using the strip flags when building.
![screen-2023-04-07-22:39:12](https://user-images.githubusercontent.com/34864484/230675906-085f204f-37b3-4e1f-a86d-769d1c9e62fd.jpg)

**Comment by caarlos0** [comment]
we are already building with `-s -w`, see https://github.com/charmbracelet/meta/blob/main/goreleaser-full.yaml

**Comment by caarlos0** [comment]
we could run `upx` on it after the build, would shave it from 26M to ~4.5M

**Comment by caarlos0** [comment]
I'll integrate upx into goreleaser so we can easily run it on our builds :)

**Comment by rpodgorny** [comment]
this is first few lines of "goweight":

   14 MB github.com/yuin/goldmark-emoji/definition
   11 MB runtime                   
  5.2 MB github.com/alecthomas/chroma/v2/lexers                                                 
  3.8 MB golang.org/x/sys/unix            
  2.6 MB github.com/alecthomas/kong            
  2.6 MB reflect                                                                                
  2.6 MB github.com/yuin/goldmark/util    
  2.2 MB github.com/yuin/goldmark/ast                                                           
  1.9 MB math/big                           
  1.7 MB github.com/charmbracelet/lipgloss
  1.7 MB syscall            
  1.7 MB github.com/yuin/goldmark/parser                                                                                                                                                        
  1.4 MB github.com/alecthomas/chroma/v2
  1.4 MB text/template
  1.3 MB github.com/dlclark/regexp2/syntax
  1.3 MB encoding/json
  1.3 MB text/template/parse
  1.2 MB github.com/yuin/goldmark/extension/ast
  1.2 MB go/ast
  1.2 MB golang.org/x/net/html
  1.1 MB github.com/yuin/goldmark/extension
  1.1 MB internal/abi
  1.1 MB os
  1.1 MB time
  1.1 MB github.com/microcosm-cc/bluemonday/css
  1.1 MB github.com/charmbracelet/bubbletea
  1.1 MB encoding/xml
  882 kB github.com/muesli/termenv
  831 kB fmt
  806 kB go/doc
  773 kB regexp/syntax
  753 kB github.com/charmbracelet/glamour/ansi
  746 kB internal/reflectlite
  741 kB github.com/charmbracelet/bubbles/textarea
  728 kB github.com/dlclark/regexp2
  718 kB regexp
  671 kB internal/poll
  618 kB github.com/microcosm-cc/bluemonday
  617 kB go/doc/comment
  610 kB compress/flate
  595 kB math
  591 kB github.com/lucasb-eyer/go-colorful

...the question then is: do we really need 14 megabytes of emojis? ;-)

**Comment by caarlos0** [comment]
@rpodgorny I believe it is a dependency of goldmark, which we use to render markdown in `gum format` for example.

running upx helps though, from 27mb to 6.9, but it might break on some systems (I remember there's an issue open for latest macos, and a newer one is coming out soon!), so maybe we do that (and test) on linux only if we assess its safe 🤔

**Comment by reitzig** [comment]
Looking at the assets of the latest release -- all <5MB -- it seems this has been fixed! 😀 🎉

**Comment by rpodgorny** [comment]
> Looking at the assets of the latest release -- all <5MB -- it seems this has been fixed! 😀 🎉

not really sure what you're referring to but the "gum version 0.14.5 (1917023)" binary on my arch linux system is currently ~20MB. while much better than before, this is still far from ideal. :-(

**Comment by reitzig** [comment]
Oh my, you're right, my bad. I was looking at these:

![image](https://github.com/user-attachments/assets/42c6e662-f760-4158-bfa0-1f65c854a50b)

The extracted binary is, indeed, ≈20MB of size. A binary that compresses by a factor of four, was not expecting that. 🤔

**Comment by caarlos0** [comment]
i don't get why goweight says goldmark-emoji is 14mb though 🤔 

```console
$ du -hs $GOPATH/pkg/mod/github.com/yuin/goldmark-emoji@v1.0.3/
176K    /Users/carlos/Developer/Go/pkg/mod/github.com/yuin/goldmark-emoji@v1.0.3/
```

**Comment by caarlos0** [comment]
ohhh, this might be it https://github.com/yuin/goldmark-emoji/pull/8

**Comment by caarlos0** [comment]
can confirm that that PR fixes it.

**Comment by meowgorithm** [comment]
Okay cool, so once that's merged we can update accordingly.

**Comment by ccoVeille** [comment]
Dix you try ?

https://github.com/Zxilly/go-size-analyzer

(Hi @Zxilly :wave:)

**Comment by caarlos0** [comment]
should be fixed on next release

**Comment by caarlos0** [comment]
will close as its fixed on main
