### ISSUE TITLE
how to deal with choose run in subshell, to detect ESC pressed?

### ISSUE THREAD

**Issue by fragolinux** [charmbracelet/gum#335]
trying to intercept when someone presses ESC while selecting something using choose, but got nothing... my test code

```
cmnd=$(gum choose --no-limit ${menulist} --selected ${selected})
echo test
```

it never echoes test if i press ESC, i'd like to report this to the user
thanks

**Comment by MikaelFangel** [comment]
Did you mean something like this? 
`if ! gum choose --no-limit $(ls); then echo "Oh no! You interupted me"; fi`

**Comment by fragolinux** [comment]
> Did you mean something like this?
> 
> ```
> if ! gum choose --no-limit $(ls); then echo "Oh no! You interupted me"; fi
> ```

ok, nice, but how to deal with retrieving the eventual choose, assigning it to a variable as in my example?

i need something which both assign selected values to that variable, OR returns something to let the user know he aborted, if he presses ESC

**Comment by hellmouthxyz** [comment]
> > Did you mean something like this?
> > ```
> > if ! gum choose --no-limit $(ls); then echo "Oh no! You interupted me"; fi
> > ```
> 
> ok, nice, but how to deal with retrieving the eventual choose, assigning it to a variable as in my example?
> 
> i need something which both assign selected values to that variable, OR returns something to let the user know he aborted, if he presses ESC

You can do this by altering the if statement to check whether the variable assignment worked.  
  
Example:
```
intFunc()  {
  echo "Oh no!  You interrupted me!"
}

cmnd=$(gum choose --no-limit $(ls)) || intFunc
```
  
I doubt this is the best way to do it, but it works.  I'd prefer to use a signal trap for this, but I haven't yet figured out how to get the signal to be received by the parent script while in an interactive gum command.

**Comment by caarlos0** [comment]
you can check if `$?` is 130 - which is the `exit` gum does when its interrupted.

ref https://github.com/charmbracelet/gum/blob/c868aa1c6ce85e1a3c62ba47ca96e838a8ac3e34/internal/exit/exit.go#L15
