### ISSUE TITLE
using spin with cycles

### ISSUE THREAD

**Issue by fragolinux** [charmbracelet/gum#336]
hi, i've tihs code and i'd like to put it in some "spin" command, so the user knows something is going on in background... tried to put it in a function, same result, spin accepts only commands or scripts, not pieces of code or function, as it seems... hints? thanks

```
for profile in "${!profiles[@]}"; do
    PROFILE="$profile" ENABLED="${profiles[$profile]}" yq -i '.data.profiles.[env(PROFILE)].enabled |= env(ENABLED)' "$XDG_CONFIG_HOME/chezmoi/chezmoi.yaml"
done
```

**Comment by piero-vic** [comment]
This might work https://github.com/charmbracelet/gum/issues/419#issuecomment-2351679739

**Comment by caarlos0** [comment]
duplicate of #419
