### ISSUE TITLE
Since version 0.10 `gum choose --no-limit` selection of one element by `Enter` does not work

### ISSUE THREAD

**Issue by WoozyMasta** [charmbracelet/gum#339]
Since version 0.10 `gum choose --no-limit` selection of one element by `Enter` does not work

**To Reproduce**
in versions 0.7-0.9 when pressing Enter one element at a time it is selected, in version 0.10 nothing will be selected

> 0.7-0.9

```bash
> printf '%s\n' Foo Bar Baz | gum choose --no-limit; echo $?
Foo
0
```

> 0.10

```bash
> printf '%s\n' Foo Bar Baz | gum choose --no-limit; echo $?
0
```

**Desktop:**
`Linux 5.15.0-50-generic x86_64 Ubuntu 22.04.2 LTS (Jammy Jellyfish)`

**Comment by MikaelFangel** [comment]
The selection behaviour was change by https://github.com/charmbracelet/gum/commit/e6de7749b139c3ff38285437d390f5f92e1689fb referring to #140 (:

**Comment by MikaelFangel** [comment]
@ajs256 You select multiple by pressing `space`.

![screen-2023-04-26-07:54:09](https://user-images.githubusercontent.com/34864484/234482035-6ea6bfdb-0f1f-4c2d-85d9-cd22671ba5cf.jpg)

**Comment by WoozyMasta** [comment]
@MikaelFangel 
But this is not obvious behavior, if I need only one element, why should I additionally select it before use it?

Before 0.10, it seems to me there was a more logical behavior

**Comment by MikaelFangel** [comment]
@WoozyMasta imo the problem with just selecting the highlighted one was that it didn't seem obvious that it would select it if I pressed enter. But I also hear you on the issue with the additional button press. However both functionalities are wanted and I'm not in a position to make choice about this (:

**Comment by bdrnglm** [comment]
In my opinion, the current behavior is more "logical," as only the selected items are returned. If the user presses enter without selecting any item, the command should return none to signal that no items have been selected. Otherwise, it would be difficult to determine if any items were selected or not.

**Comment by WoozyMasta** [comment]
The old behavior seems more obvious

It now returns an exit status of 0 and an empty response when I hover over the second element and press enter. The element was selected by the arrows, I just don't need to mark it because I only want one element.

Naturally, if I need to select several elements, I must select each one separately.

UX looks exactly like this, and this is exactly the problem that we are facing in the current version. It might be worth making a popup here to let you know that nothing is selected, but this is a much more complex implementation than just returning logic to select one item under the cursor.

I see solutions like this:

- in case of empty choice return exit code not equal to 0
- return the logic as it was, do not make breaking changes
- return the logic as it was, make the new logic an option through the launch argument (I like this option)
- give feedback to the user that he did not select anything

**Comment by alexn-s** [comment]
@MikaelFangel  kinda stupid question but when i try to select multiple (with space) it does not select the item but adds a space to the search query.

currently i cant select multiple

am i missing something?

gum version: `0.10.0`
env: `windows powershell`

**Comment by MikaelFangel** [comment]
@alexn-s actually this is not a stupid question. I seem to have trouble selecting multiple using the example provided by the README as well.

**Comment by alexn-s** [comment]
huh... thanks for letting me know

**Comment by maaslalani** [comment]
@alexn-s In your example you would need to separate the options by newlines:

```
echo "apple\nbanana" | gum filter --no-limit
```

or:

```
echo "apple" >> choices.txt
echo "banana" >> choices.txt
cat choices.txt | gum filter --no-limit
```

To select, you can press <kbd>ctrl+space</kbd> or <kbd>tab</kbd>

**Comment by alexn-s** [comment]
@maaslalani 

comma works fine in powerhell
tab works. did not try that

ctrl+space does not work

thanks for the help

**Comment by Justinzobel** [comment]
I just came across this from another issue to figure out how to select multiple items. If this information could be added to the README in the no-limit section it would improve the user experience.

**Comment by caarlos0** [comment]
fixed on main!

thanks
