### ISSUE TITLE
FreeBSD Port

### ISSUE THREAD

**Issue by bitboss-ca** [charmbracelet/gum#340]
Just an FYI.  I have submitted [PR 271028](here: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271028) for inclusion of gum in the FreeBSD Ports collection.  Thanks for this excellent tool!

**Comment by muesli** [comment]
Much appreciated, thank you!

**Comment by bitboss-ca** [comment]
Working on this.  Here's a question for you:  How would I go about generating (zsh, etc.) completion files once I have built gum from source?

**Comment by bitboss-ca** [comment]
The port has been committed.

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=271028
https://github.com/freebsd/freebsd-ports/commit/3ab5fcc4895c753db12b08425e5cdac6cb0ebdae
https://www.freshports.org/devel/gum/

Don't update your installation instructions just yet.  I'll let you know when it's widely available.

**Comment by bitboss-ca** [comment]
The port is now widely available in the ports tree.  You can update your installation instructions to include FreeBSD:

```
# FreeBSD
cd /usr/ports/devel/gum
make install clean
```
