### ISSUE TITLE
Environment Variable of `gum format --theme`

### ISSUE THREAD

**Issue by 5ouma** [charmbracelet/gum#344]
**Is your feature request related to a problem? Please describe.**
I want to add an environment variable of `gum format --theme`.

**Describe the solution you'd like**
By running `export GUM_FORMAT_THEME="/path/to/json-file".

**Comment by maaslalani** [comment]
Hey, thank you so much for creating this issue. ❤️ 

#356 will fix this!

**Comment by 5ouma** [comment]
Thank you for creating new enshrinement variables!!
