### ISSUE TITLE
Indentation not preserved with `gum format`

### ISSUE THREAD

**Issue by basilioss** [charmbracelet/gum#347]
**Describe the bug**
Indentation not preserved with `gum format`.

**To Reproduce**

1. Create the file `test.md`:

```
# Lorem ipsum

- item 1 
  - item 2 
  - item 3 
    - item 4
  - item 5
- item 6

Curabitur blandit **tempus** ardua ridiculus sed magna. Phasellus laoreet lorem vel dolor tempus vehicula.

- [ ] task 1 
    - [ ] subtask 1 
    - [ ] subtask 2 
- [ ] task 2
```

2. Run `gum format < test.md`
3. Indentation isn't preserved:

![image](https://user-images.githubusercontent.com/71596800/235430901-05c8d97e-3087-490c-809a-488c6d4312f7.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/71596800/235431204-27be7d1a-0ac7-4665-a7ea-2d9b5f4c821a.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: 0.10.0 (0f0f8e9)

**Comment by GreatestOfAllTimee** [comment]
Any update on this issue?

**Comment by basilioss** [comment]
It seems like it doesn't work only with the default theme. `gum format --theme=dark < test.md` works for me.

**Comment by piero-vic** [comment]
Gum uses [glamour](https://github.com/charmbracelet/glamour) for formatting so this might be an issue with glamour itself since other themes work just fine.

**Comment by maaslalani** [comment]
This is now fixed on the latest version (`@main`) of gum! Thank you for reporting @basilioss!
