### ISSUE TITLE
gum choose with no limit cannot be selected when only one option

### ISSUE THREAD

**Issue by fharper** [charmbracelet/gum#361]
**Describe the bug**

If I run `echo "1\n2" | gum choose --no-limit`, gum is working properly: I can also select only one item.

If I do `echo "1" | gum choose --no-limit`, I cannot select the one item. It's working only if I remove the `--no-limit` flag.

I would prefer not having to manage the fag depending on the number of items I pass to `choose` as most of the times I have multiple. I also would like to keep the same cursor & prefixes, like `--unselected-prefix "[ ] " --cursor-prefix "[ ] " --selected-prefix "[✓] "`.

In any cases, about the prefixes & cursor, if I programmatically remove the `--no-limit` flag, it will display `>` since it's a single choice. So maybe this is also a bug that the prefixes doesn't display when the `--no-limit` flag isn't there.

**Comment by piero-vic** [comment]
I've found why the program behaves this way. When using the `--no-limit` flag the limit is set to the number of options.

https://github.com/charmbracelet/gum/blob/3609fe1da8b6d3937dcf85b15e62becb1d9c087e/choose/command.go#L46-L50

However if the limit is set to 1 the key to select an option will always be ignored.

https://github.com/charmbracelet/gum/blob/3609fe1da8b6d3937dcf85b15e62becb1d9c087e/choose/choose.go#L120-L123

I can submit a PR but I would like to know how the maintainers would like to handle this issue.

**Comment by maaslalani** [comment]
Fixed in: https://github.com/charmbracelet/gum/commit/a61f3bdc3f906114cb9d9135adbdcd65397dc487
