### ISSUE TITLE
gum filter returns stdin when no match is made

### ISSUE THREAD

**Issue by causality-loop** [charmbracelet/gum#363]
**Describe the solution you'd like**
- `gum filter` returns user input if no match is made, mimicking the behavior of [fzy](https://github.com/jhawthorn/fzy) instead of fzf.
- In the below examples, the user inputs `green`:
```sh
echo -e "red\nblue" | fzf
# no stdout
echo -e "red\nblue" | gum filter
# no stdout
echo -e "red\nblue" | fzy
# green
```

**Describe alternatives you've considered**
fzy

**Comment by maaslalani** [comment]
Hey, please use the `--no-strict` flag to mimic this behaviour!
