### ISSUE TITLE
gum choose --no-limit returns list item without selecting it with <Space>

### ISSUE THREAD

**Issue by causality-loop** [charmbracelet/gum#364]
**Describe the solution you'd like**
- For the example:
```sh
echo -e "red\nblue" | gum choose --no-limit
```
- If a user wants `red` to be outputted, they must select `red` with `Space`, then hit `Enter`
- I think I'd be more convenient (for single-item selections) for a user to simply hit `Enter` without needing to first hit `Space` (I believe this used to be default behavior)

**Comment by piero-vic** [comment]
You need to omit the `--no-limit` flag to get that behavior.

```bash
echo -e "red\nblue" | gum choose
```

**Comment by causality-loop** [comment]
@piero-vic Thank you, but I like the `--no-limit` flag.  Sometimes, I want to select multiple items, but other times, I only need one.  If I only need one, then it would be more convenient to not have to hit `Space` first.

**Comment by MikaelFangel** [comment]
This looks like a duplicate of #339

**Comment by causality-loop** [comment]
> This looks like a duplicate of #339

@MikaelFangel Yes!  Thanks so much.  After checking out #339, I now know how to modify the code myself.  Marking as closed.

**Comment by MikaelFangel** [comment]
You're welcome 😊
