### ISSUE TITLE
Make the blinking cursor optional in `input` and `write`

### ISSUE THREAD

**Issue by dbohdan** [charmbracelet/gum#367]
I dislike blinking cursors, especially blinking block cursors. I am sure I am not the only one: https://github.com/microsoft/terminal/issues/1379. It also feels jarringly inconsistent with the rest of my system in a way that, for example, a different color palette does not.

It would be nice to have a command-line option and an environment variable to disable blinking in `input` and `write`. Alternatively, you could implement a ["reduce motion"](https://support.apple.com/en-us/HT202655) mode that disabled all animations, current and future. There are upsides and downsides to being less granular.  People who want to disable one animation often want to disable all animations, but not always.

**Comment by maaslalani** [comment]
Hey this is now fixed on `main` by https://github.com/charmbracelet/gum/pull/368

```
gum input --cursor.mode static
gum input --cursor.mode hide
gum write --cursor.mode blink
```

**Comment by dbohdan** [comment]
Thanks!
