### ISSUE TITLE
[Feature] add option for `filter` command to be non-recursive

### ISSUE THREAD

**Issue by terminalPoltergeist** [charmbracelet/gum#37]
Make an option for the filter command to only show files and folders in the current folder. ie. don't show all contents of all directories within the current directory.

**Comment by maaslalani** [comment]
Hey, you can pass `stdin` input to `gum filter` and it will display what you pass in to filter through. Instead of a `--no-recursive` flag I think it is is likely more efficient and extensible to simply run:

```
ls | gum filter
```

Which will non-recursively filter through the files and folders in your current folder.

**Comment by terminalPoltergeist** [comment]
Thanks! This is awesome! Can't believe I didn't think of that haha
