### ISSUE TITLE
pager cuts some short lines depending on font size

### ISSUE THREAD

**Issue by franalbani** [charmbracelet/gum#373]
**Describe the bug**

Some short lines are cut at different places depending on terminal font size

**To Reproduce**
1. `curl cheat.sh/go/:learn | gum pager`
2. Look at line 30: `fmt.Println("Hello world!")`
3. Start increasing font size (I do it with <kbd>CTRL+ +</kbd> on `alacritty`)
4. watch out for `fmt.Println("Hello world!"`
5. Keep going...
6. watch out for `fmt.Println("Hel`

**Expected behavior**
To see the full line.

**Screenshots**

![image](https://github.com/charmbracelet/gum/assets/13975308/93ba75c2-1cf0-4378-9d90-3ab2e7bb192a)

**Desktop (please complete the following information):**
 - OS: arch linux

**Comment by MikaelFangel** [comment]
What version of Gum are you using?

**Comment by franalbani** [comment]
> What version of Gum are you using?

I'm sorry I forgot to add it before.

```
$ gum --version
gum version 0.10.0 (0f0f8e9)
```

**Comment by MikaelFangel** [comment]
Hi @franalbani,

I replicated the issue with the version you are using, but when using version v0.11.0 it looks fixed to me. I believe some of the changes I did in #321 fixed this issue. Can you confirm that this issue is resolved in version v0.11.0?
