### ISSUE TITLE
GPG Public Key Signature Failure Causes Gum Install To Fail

### ISSUE THREAD

**Issue by ideonrandy** [charmbracelet/gum#377]
**Describe the bug**
On particular Ubuntu machines, the installation steps to install gum through the apt package manager do not succeed due to a GPG error: `W: GPG error: https://repo.charm.sh/apt  InRelease: The following signatures couldn't be verified because the public key is not available`.

**To Reproduce**
```
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install gum
```

**Expected behavior**

**Screenshots**
![image](https://github.com/charmbracelet/gum/assets/95771490/fd271038-2987-4e0b-be35-7920f20b76e5)

**IOT GATEWAY 8:**
 - `Linux iot-gate-imx8 5.10.72-iot-gate-imx8-3.1+gaa91dea99095 #1 SMP PREEMPT Thu Jul 21 10:04:44 UTC 2022 aarch64 GNU/Linux`
 - [Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22]](https://www.compulab.com/products/iot-gateways/iot-gate-imx8-industrial-arm-iot-gateway/)

**Additional context**
I had run the commands as both a regular and root user and the issue persisted. On that same machine, I created a base ubuntu container and ran the following steps to try and reproduce the problem but in this case the install succeeded without issue:

```
apt-get update
apt-get install -y sudo curl gpg
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install gum
```

**Comment by ideonrandy** [comment]
Here is a simple bypass - replace:

```
sudo mkdir -p /etc/apt/keyrings
curl -fsSL https://repo.charm.sh/apt/gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/charm.gpg
echo "deb [signed-by=/etc/apt/keyrings/charm.gpg] https://repo.charm.sh/apt/ * *" | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install gum
```

With:

```
sudo mkdir -p /etc/apt/keyrings
echo 'deb [trusted=yes] https://repo.charm.sh/apt/ /' | sudo tee /etc/apt/sources.list.d/charm.list
sudo apt update && sudo apt install gum
sudo rm /etc/apt/sources.list.d/charm.list && sudo apt update
```

It does not solve the underlying key issue, but it allows for Gum to be installed by bypassing the key and then removes the package source so that the warning doesn't constantly show up afterwards

**Comment by aymanbagabas** [comment]
Hi @ideonrandy, make sure you have `gnupg` and `curl` installed

**Comment by hanbyul-kim** [comment]
I installed `ca-certificates` and finally could install gum.

```
sudo apt install ca-certificates
```

**Comment by caarlos0** [comment]
yes, you'll need ca-certificates for it to work!
