### ISSUE TITLE
gum choose: Keybindings for select all, invert selection and documentation for these keybindings

### ISSUE THREAD

**Issue by lwbt** [charmbracelet/gum#388]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to have keybindings to select all items (e.g. `a`) in `gum choose` and to invert (e.g. `i`) a selection and to have these keybindings documented in a way that I don't need to read the source code itself (requiring understanding of how the code works).

An option to **start with all items selected** would also be useful.

**Describe alternatives you've considered**
- https://github.com/charmbracelet/gum/issues/202 Would also solve the documentation problem.
- I read the source of the gum choose module and found that `a` selects all while `A` does the opposite. It's just not obvious for novice or non-programmers (and users who find vi-keybindings unintuitive, but I like vi) and I had to guess too.

**Additional context**
I'm building a script to copy files (Linux ISOs for use with Ventoy) and I keep track of files which I removed (e.g. ubuntu-desktop-12.04.iso) from my main image repository (the location, e.g. NAS, where I store all the images) and want to offer a user (me) to quickly do the housekeeping work of syncing and deleting images on the many drives of different sizes and quality in my household. Gum helps a lot of making such a thing even possible without over engineering, it just needs few more bits here and there and it will be perfect.

**Comment by caarlos0** [comment]
for choose, this should be fixed on main:

![CleanShot 2024-12-11 at 14 39 07@2x](https://github.com/user-attachments/assets/4f1ac870-0c16-4bab-93d5-910b3f1960eb)

will fix filter as well.
