### ISSUE TITLE
"Install" commands for Debian / Ubuntu & Go not working

### ISSUE THREAD

**Issue by serainox420** [charmbracelet/gum#389]
Commands from main README.md for Debian / Ubuntu via curl & apt are bit old, same goes for "Go" section. 
Could you please update?

If Debian won't be willing to update apt repo's then I personally suggest using Git.

**Comment by caarlos0** [comment]
seems to be correct to me, just tested it.

not sure which problem you had, maybe it was already fixed, if isn't, please share more details

cheers!
