### ISSUE TITLE
gum input - missing cursor when running in container images (since v0.10.0)

### ISSUE THREAD

**Issue by ThomasBuchinger** [charmbracelet/gum#391]
**Describe the bug**
I am writing a script that uses `gum input --value "default-value"`. The default value must be edited by the user.

The problem is, that there is no cursor on screen, making it hard to know where the cursor is exactly. The cursor still exists and it can be moved by pressing the arrow keys and counting the number of characters, but there is no on screen indication for the current cursor position

* The bug only exists when running inside a container image (tested on `ubuntu:22.04` and `charmcli/gum:v0.10.0`)
* Running gum v0.10.0 without a container works
* Using the older `charmcli/gum:v0.9.0` image works
* The bug seems to still exists on `main`-branch. Tested with `docker.io/golang` image and `go install github.com/charmbracelet/gum@main`

**To Reproduce**
```shell
# Produces the bug
podman run -it --rm  docker.io/charmcli/gum:v0.10.0 input
```
![gum_cursorbug_v0 10 0](https://github.com/charmbracelet/gum/assets/3862153/2e223310-697a-41d3-b9fd-4aca7baa3e65)

```shell
# Produces the bug
podman run -it --rm docker.io/golang
go install github.com/charmbracelet/gum@main
gum input
```

![gum_cursorbug_main](https://github.com/charmbracelet/gum/assets/3862153/aa928d38-181d-4373-be3a-2be90d054c63)

```shell
# v0.9.0 image works
podman run -it --rm  docker.io/charmcli/gum:v0.9.0 input
```

![gum cursorbug_v0 9 0](https://github.com/charmbracelet/gum/assets/3862153/72ff5c2f-a5a2-40de-9b99-7d4fe53a37ea)

```shell
# The native binary works
$ ./gum --version
gum version v0.10.0 (0f0f8e9)
$ ./gum input                     
```
![gum_cursorbug_native](https://github.com/charmbracelet/gum/assets/3862153/26ccfa90-580e-4f14-9493-da2897d3d091)

**Expected behavior**
There should be a blinking box, showing the current position of the cursor

**Desktop (please complete the following information):**
 - Fedora37, podman 4.5.0
 - RHEL 8.4, podman 4.4.3

**Additional context**
I don't really have access to a different Linux distro or container runtime at the moment. If there are any additional setting I can try, let me know

**Comment by caarlos0** [comment]
fwiw, could repro this with main on docker as well:

![CleanShot 2024-12-10 at 15 30 37@2x](https://github.com/user-attachments/assets/baac5804-4a9e-40ed-ade9-a5d8b949218c)

**Comment by aymanbagabas** [comment]
> cc/ @aymanbagabas do you know if this works the same way in lipgloss v2?

Good point! It would produce the same results in v2. This is related to [colorprofile](https://github.com/charmbracelet/colorprofile/blob/main/env.go#L119). `TERM=xterm` should return a `ANSI` color profile

**Comment by aymanbagabas** [comment]
@caarlos0 I've opened https://github.com/charmbracelet/colorprofile/pull/22 to resolve this issue in v2

**Comment by caarlos0** [comment]
thanks @aymanbagabas!

**Comment by caarlos0** [comment]
fixed on main 
![CleanShot 2024-12-11 at 10 19 00@2x](https://github.com/user-attachments/assets/f528f54d-4ee8-45dd-a17a-c8e25ef2450f)
