### ISSUE TITLE
gut choose --selected= displayed incorrectly

### ISSUE THREAD

**Issue by vt-alt** [charmbracelet/gum#394]
**Describe the bug**
When `--selected=` is used with `gum choose` selection is displayed incorrectly while actually correct line is selected (as result confusing users).

**To Reproduce**
```
$ seq 111 | gum choose --selected=22
  1
> 2
  3
  4
  5
  6
  7
  8
  9
  10

  ••••••••••••
```

If arrow down pressed once:
```
  11
  12
> 13
  14
  15
  16
  17
  18
  19
  20
```
One more pressing or down arrow:
```
  21
  22
  23
> 24
  25
  26
  27
  28
  29
  30
```
Finally we are at correct line.

**Expected behavior**
Correct selection fragment expected, in example, line `22`.

**Desktop (please complete the following information):**
 - OS: ALT Linux
 - Version 0.10.0

**Comment by piero-vic** [comment]
I think this is because the initial page is not being set when initializing the pagination bubble. It defaults to index 0.

https://github.com/charmbracelet/gum/blob/d1ad453ce61aeb1181e5cf86ceb28c888ab92ff2/choose/command.go#L87-L95

**Comment by maaslalani** [comment]
Fixed in: https://github.com/charmbracelet/gum/commit/6763de12e8e3ad28aa4c8baf4ce2816d564e1000

**Comment by vt-alt** [comment]
@maaslalani Thanks much!

**Comment by fharper** [comment]
Any plans to release a new version with that fix?
