### ISSUE TITLE
[bug]: gum filter empty last line

### ISSUE THREAD

**Issue by justchokingaround** [charmbracelet/gum#40]
for instance, when in a directory with several files, running
```sh
gum filter
```
will allow the user to choose one of the files present in the directory, and this would be the expected behavior
however, when piping into `gum filter`, we get a different behavior
```sh
ls | gum filter
```
will have an empty trailing last line

**Comment by maaslalani** [comment]
Ah interesting, this is definitely a bug. We should trim trailing new lines I believe. Thank you for reporting this!

**Comment by maaslalani** [comment]
Fixed: https://github.com/charmbracelet/gum/commit/c9caec2c6205ed309aeb45dc2d737f817651c7c8
