### ISSUE TITLE
gum choose/filter with multiple options

### ISSUE THREAD

**Issue by uwe-schwarz** [charmbracelet/gum#400]
**Is your feature request related to a problem? Please describe.**
I'm trying to replace dialog with gum choose/filter, because it just looks way better. dialog has the option to display a few options like --extra-button or --cancel-label.

**Describe the solution you'd like**
Basically I would like a list to be displayed and in a separate row a few options what should be done with this line:

```
gum choose --options "d:download,i:info,r:restart,q:quit" link1 link2 link3 link4
```

This could display something like this:

> d:download i:info r:restart q:quit
> [ ] link1
> [x] link2
> [ ] link3
> [ ] link4

Selected item in this case would be "link2" (just as example) and if the user presses any of the options the result could be something like:

> d:link2

The options could be selected with right/left cursor too.

**Describe alternatives you've considered**
At the moment it's a two step process for me, I first present the `gum choose` with the link-list and then another `gum choose` with the options for the selected link. (link/option just to stay in the example above)

**Comment by caarlos0** [comment]
I think this can be solved with 2 gum choose calls:

```sh
link=$(gum choose link1 link2)
action=$(gum choose download info restart)
```
