### ISSUE TITLE
`gum choose` mapped/masked/labeled values

### ISSUE THREAD

**Issue by Birdie0** [charmbracelet/gum#406]
**Is your feature request related to a problem? Please describe.**
Would be great to be able to mask values or set labels for them in `gum choose`, in case unreadable or being mapped.

**Describe the solution you'd like**
I have possible implementation on my mind: `--labeled` flag that splits every argument by `:` character in `value` and `label` parts. In case `:` is part of label/value, `--labeled.separator=X` argument can be provided.

```sh
gum choose --labeled '1:yes' '0:no'
gum choose --labeled --labeled-separator='==' '1==yes' '0==no'
> yes
  no

# [enter]

1
```

**Describe alternatives you've considered**
Currently to achieve similar approach `case` operator can be used:

```sh
abc() {
  local answer="$(gum choose 'yes' 'no')"

  case $answer in
    yes)
      echo 1
      ;;
    no)
      echo 0
      ;;
  esac
}
```

**Additional context**
It's generally inspired by select dropdown element:
![image](https://github.com/charmbracelet/gum/assets/7945905/8dcd292a-f1b9-4499-9d83-29debe3ebd49)

**Comment by quexer** [comment]
Hey @Birdie0, there's a closed feature request (https://github.com/charmbracelet/gum/issues/43) that might have a workaround for your requirement.

**Comment by Birdie0** [comment]
@quexer thanks, it looks better than mine and would be easier to manage!

**Comment by caarlos0** [comment]
Hey!

done in #783, will be available in the next release :)
