### ISSUE TITLE
Unable to select option with `gum choose --no-limit` when there is only one argument

### ISSUE THREAD

**Issue by uncenter** [charmbracelet/gum#407]
**Description**
When running `gum choose --no-limit "a"` I am unable to select the "a", and additionally pressing enter without it being selected prints "a" when it should actually print nothing (pressing enter on an item without any selected when there is more than one argument prints nothing).

**To Reproduce**
1. Run `gum choose --no-limit "a" "b"`.
- Observe how selecting (<kbd>Space</kbd>) toggles the "bullet" appearance on the left of the item.
- Observe that pressing <kbd>Enter</kbd> with nothing selected prints nothing.
3. Run `gum choose --no-limit "a"`.
- Observe how selecting *does not* toggle the bullet appearance.
- Observe that pressing <kbd>Enter</kbd> with nothing selected prints "a".

**Expected behavior**
A) I should be able to select the item when there is only one option and B) pressing enter on the only option without it selected should print nothing.

**Debug**

 - OS: macOS
 - Terminal: iTerm2, Terminal.app
 - Gum 0.11.0

**Comment by piero-vic** [comment]
Fixed on a61f3bd

**Comment by uncenter** [comment]
New release soon? Happy to close this.

**Comment by uncenter** [comment]
Woohoo! Thanks @maaslalani!

**Comment by maaslalani** [comment]
> Woohoo! Thanks @maaslalani!

No problem! Thanks for using gum and contributing too!
