### ISSUE TITLE
format - add lines for rows and columns when using csv input

### ISSUE THREAD

**Issue by danie-dejager** [charmbracelet/gum#411]
**Is your feature request related to a problem? Please describe.**
I would like to create a table from CSV input. I use `rich-cli` to format my CSV output but ideally `gum` should do that too and I will need one less tool.
Original:
![image](https://github.com/charmbracelet/gum/assets/13314239/a43596e0-e5e7-40d3-9bc3-77bf3926bd21)
using rich-cli:
![image](https://github.com/charmbracelet/gum/assets/13314239/ced26563-2008-4277-bb21-1fe4f1e6295a)

What I'm getting is a table from which I can select a specific line which will get printed to the command line.
![image](https://github.com/charmbracelet/gum/assets/13314239/24024952-d349-455c-b030-ba5a04bc8faa)

**Describe the solution you'd like**
I want gum to format csv or similar input like `rich-cli` is doing.

Why does gum work below but I cannot format CSV?
```
echo "## Test:
|Name            |Bool             | Source     |
|----------------|-----------------|------------|
|a1              |Yes              |local	|
|b1              |Yes              |local       |
|c1              |Yes              |local       |
|d1              |Yes              |remote      |
"  | gum format
```
|Name            |Bool             | Source     |
|----------------|-----------------|------------|
|a1              |Yes              |local	|
|b1              |Yes              |local       |
|c1              |Yes              |local       |
|d1              |Yes              |remote   |

**Describe alternatives you've considered**
rich-cli can format my CSV input into columns with minimal effort. 
https://github.com/Textualize/rich-cli

**Comment by piero-vic** [comment]
Hi @daniejstriata. You can use `gum table -p`. It was introduced on #436 so you will need to use the git version of gum.

I think something like this would work for you.

```bash
echo "
a1,a2,a3,a4,a5
b1,b2,b3,b4,b5
c1,c2,c3,c4,c5
d1,d2,d3,d4,d5
"  | gum table -p
```

**Comment by daniejstriata** [comment]
I built the binary from git in the main branch and it is working!
I see it assumes that the first row is a header.
![image](https://github.com/charmbracelet/gum/assets/13314239/34e56368-6fa2-4946-9174-82775a6c4060)
otherwise I can specify headers:
![image](https://github.com/charmbracelet/gum/assets/13314239/0c3d70c8-b376-4856-8b12-e32edaa4102c)

**Comment by daniejstriata** [comment]
If I give a header with no data then the table is not drawn
![image](https://github.com/charmbracelet/gum/assets/13314239/0e3c993f-6638-4bcd-ba6a-16e78c1c8f3f)

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/gum/pull/760
