### ISSUE TITLE
gum choose selected is not selected

### ISSUE THREAD

**Issue by electriquo** [charmbracelet/gum#412]
**Describe the bug**
when providing `gum choose --selected foo` with many items it automatically span the items on multiple pages, if the given selected value (`foo`) is on a different page, gum will:
1. not display the correct selection
2. pressing enter (without doing anything else), returns the given selected value (`foo`) and not the highlighted value

**To Reproduce**
```shell
$ sel=$(echo -e "1\n2" | gum choose --selected 2 --height 1)
> 1

  ••

$ echo $sel
2
```

**Expected behavior**
gum should select jump to the page where the given selected value (e.g. `foo`) appear and select the highlighted value

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version 13.5
 - Gum version: 0.11.0

**Comment by piero-vic** [comment]
I think this is the same issue as #394. It has already been fixed but there's not a new release yet.

**Comment by fharper** [comment]
Tested, and it's indeed fixed in https://github.com/charmbracelet/gum/commit/6763de12e8e3ad28aa4c8baf4ce2816d564e1000, but not released yet.

**Comment by fharper** [comment]
No idea, but until they release, you can uninstall it, clone the repository, and `go install .`. You need Go installed though.

**Comment by caarlos0** [comment]
this is fixed on main! thanks!
