### ISSUE TITLE
README Add spinner style options

### ISSUE THREAD

**Issue by Justinzobel** [charmbracelet/gum#42]
Had a look but can't find a list of all the spinner styles.

**Comment by bewuethr** [comment]
I would have liked to see them in the help text, too, but until then, they're [here](https://github.com/charmbracelet/bubbletea/blob/e2063ac1eaafd33a4fa7dfc7f386ac4cd3320381/examples/spinners/main.go#L14-L23): `line`, `dot`, `minidot`, `jump`, `pulse`, `points`, `globe`, `moon`, `monkey`.

This is what they look like (recording is slowed down for some reason...):

https://user-images.githubusercontent.com/8521043/181972054-4e5284a9-76f7-47be-85b3-cd19e141211f.mp4

**Comment by maaslalani** [comment]
Yeah, I agree the spinner types should definitely be in the README.

The spinner type is validated so if you enter an incorrect value it will tell you which values are allowed but this should definitely be in the help text also.

**Comment by maaslalani** [comment]
Added to the README: https://github.com/charmbracelet/gum#spin
