### ISSUE TITLE
gum choose chunk

### ISSUE THREAD

**Issue by a-y-u-s-h** [charmbracelet/gum#420]
**Is your feature request related to a problem? Please describe.**
Currently with gum, I'm not sure if it possible to select some chunk (or chunks) visually from within a provided larger text or a file contents. 

**Describe the solution you'd like**
I am imagining that pager would open up and show the text that is input (from either a pipe or an argument), and then allow me to put start and end markers that highlight my selected chunk, and then as I hit enter - the pager exits and I can store the highlighted chunk of text into a variable. Additionally with more flags I may want to have metadata about that chunk as well, like line number, starting and ending positions, etc so that bash scripts can insert something before or after it.  For this to work properly, pager must have a feature to toggle line numbers as well (so that it is easy to highlight with a mouse as well).

If it allows me to highlight text based on regex filtering it would be even more amazing as it'll show me in real time what I'm trying to select with my regex and will have more usecases.

**Describe alternatives you've considered**
Select the text that I want to extract out of a variable / file with a regex or some bash command chained (but it doesn't allow for visual selection on the fly and must be hardcoded).

**Additional context**
As a reference, git allows you to add certain chunks of changes called 'hunks' with `git add -p` command. But it is very specific to git. If I could operate on parts of file instead of the whole file, and could select which part to operate on/before/after live, as the script is being run - it would enable me to create more creative scripts.

**Comment by caarlos0** [comment]
hey!

sorry, this is out of the scope of what we want in this project.
