### ISSUE TITLE
`gum spin --show-output` no longer prints anything 

### ISSUE THREAD

**Issue by gz-95** [charmbracelet/gum#429]
**Describe the bug**

`gum spin --show-output` no longer prints anything upon `gum` command completion in v0.11.0 (where as v0.10.0 works as expected).

**To Reproduce**

`gum spin --show-output -- echo hello`

**Expected behavior**

The message `hello` is printed when `gum` command completes. This works in v0.10.0 but not in the latest v0.11.0 release.

**Desktop (please complete the following information):**
 - Linux Mint 21.2
 - Terminal 3.44.0 for GNOME 42
 - `gum` v0.11.0

**Comment by MikaelFangel** [comment]
I can't replicate the problem using gum v0.11.0 on NixOS Unstable. @gz-95 Can you confirm if this is still a problem?

![Screenshot_20231004_040646](https://github.com/charmbracelet/gum/assets/34864484/08a7f93e-1b9b-424f-89ae-bccd0a2b296c)

**Comment by MikaelFangel** [comment]
This issue has been fixed by: a63ea30
