### ISSUE TITLE
[Feature Request] Ability to map `choose` values to keys

### ISSUE THREAD

**Issue by dector** [charmbracelet/gum#43]
This is not a suggested syntax - snippet if purely for demonstration purposes:

```
gum choose --with-mapping "foo:My foo value" "bar:My bar value"

switch $result
    "foo" -> ...
    "bar" -> ...
```

Motivation: in many cases it would be nice to use some id-values for `choose` command instead of duplicating human-readable values two times: in command and in control script.

_P.S. Thanks for the tool - it's awesome. Yesterday I integrated in some of my fish functions for administration and it's so much nicer to use now!_

**Comment by maaslalani** [comment]
Hey!

> P.S. Thanks for the tool - it's awesome. Yesterday I integrated in some of my fish functions for administration and it's so much nicer to use now!

Thank you for the kind words!

You can actually accomplish this with pure shell scripting, here is an example:

https://github.com/charmbracelet/gum/blob/main/examples/filter-key-value.sh

```bash
export LIST=$(cat <<END
Cow:Moo
Cat:Meow
Dog:Woof
END)

ANIMAL=$(echo "$LIST" | cut -d':' -f1 | gum filter)
SOUND=$(echo "$LIST" | grep $ANIMAL | cut -d':' -f2)

echo "The $ANIMAL goes $SOUND"

```

**Comment by dector** [comment]
😢 That's not really the same and MUCH LESS readable. But thanks for the suggestion.

**Comment by maaslalani** [comment]
> That's not really the same

Hmm, I may have misinterpreted your original example then. Could you elaborate on what you are trying to do and I can try and put together a more readable example for you?

**Comment by dector** [comment]
No, it seems that your interpretation was correct. :)

However, `gum choose` doesn't have search bar and have multi-selection and it "feels" different than `gum filter`.

I'll implement new behavior for myself anyway and then I can show the code - maybe you'll reconsider. :)

Thanks.
