### ISSUE TITLE
gum choose incorrectly displaying choices when they contain spaces

### ISSUE THREAD

**Issue by deepakgrewal** [charmbracelet/gum#435]
**Describe the bug**
When feeding in choices to gum choose through a variable and the choices contain spaces, then gum interprets the space as a delimiter and incorrectly displays the values

**To Reproduce**

This works fine:
`  gum choose "choice 1" "choice 2"`
Output:
> choice 1
  choice 2

This doesnt work correctly:
```
  local choices=(
    "choice 1"
    "choice 2"
  )
  gum choose ${choices[@]}
```
> choice
  1
  choice
  2

**Expected behavior**
When feeding in values to gum using variables, it should not interpret spaces between values as start of new value

**Desktop (please complete the following information):**
> gum --version
gum version 0.11.0

**Comment by piero-vic** [comment]
Hi @deepakgrewal. You need to wrap `${choices[@]}` in double quotes. Try this.

```bash
  local choices=(
    "choice 1"
    "choice 2"
  )
  gum choose "${choices[@]}"
```

You can use shellcheck to find bugs these kind of bugs on shell scripts. Here's the entry I found for this case in particular. https://www.shellcheck.net/wiki/SC2068

**Comment by bashbunni** [comment]
Thank you @piero-vic for your help on this!
