### ISSUE TITLE
`x gum` -- A new way to use gum

### ISSUE THREAD

**Issue by edwinjhlee** [charmbracelet/gum#442]
Hello, friends.

  I have recently included gum as a package in x-cmd. Now, users can simply type "x gum" and x-cmd will automatically download and execute the binary. You can check out the demo at https://www.x-cmd.com/pkg/gum.
  
  Installing x-cmd is extremely easy. Just run `eval "$(curl https://get.x-cmd.com)"` and the process should be quick since x-cmd only uses shawk (shell/awk) and curl.
  
  For more information on installation, please visit https://www.x-cmd.com.
  
  We highly recommend using x-cmd as the preferred method for using gum.

**Comment by MikaelFangel** [comment]
To quote the [x-cmd repo](https://github.com/x-cmd/x-cmd)

> Currently in alpha testing (v0.1.15), please do not use it in production environments.

**Comment by bashbunni** [comment]
Hey @edwinjhlee correct me if I'm misreading this, but this issue seems to be unrelated to Gum and is purely self-promotion of your own project. **Users should install Gum as directed in the README of this project.** Please refrain from using issues to self-promote - that is not what this space is for.

**Comment by edwinjhlee** [comment]
Hi @bashbunni.

  The x-cmd is currently in its alpha stage and not in beta. We have plans to promote it in the coming months, but it won't happen immediately. If we were to promote it, we would announce it on the forum and discord channels.
  
  This issue aims to extend a warm welcome to the charmbracelet community.

---

Notice the installation method that the README provided, requires priviledge.
x-cmd project is simply like apt, brew, without priviledge(install and usage).

That makes using gum much easier. Same to glow and other tools in your community.
