### ISSUE TITLE
Provide an API to gum functionality

### ISSUE THREAD

**Issue by ITler** [charmbracelet/gum#444]
**Is your feature request related to a problem? Please describe.**
I would like to use the magic of gum (`filter`, `choose`, ...) from my own go application and bring back the user's 'choice' into my go application.

**Describe the solution you'd like**
Hence I am asking, if you have plans to provide an API to the gum functionality.

**Describe alternatives you've considered**
From within my own app, calling `os.Exec` on the gum executable and eval the gum output within my application again. Seems  hacky.

**Comment by bashbunni** [comment]
Hey @ITler I think what you're looking for is  [Bubbles](https://github.com/charmbracelet/bubbles). Gum is just a wrapper for these components that can be used with [Bubble Tea](https://github.com/charmbracelet/bubbletea) for Go applications. 

That being said, if there's something more specific that you're looking for, I'd be happy to help facilitate. Let me know your thoughts!

**Comment by ITler** [comment]
Thanks @bashbunni  for pointing this out. My question was due to the fact, that I am not that familiar with this bubbletea ecosystem, yet. However, with the help of your input, I was able to get an idea of what I would need to do to on my codebase.
By now, there is nothing specific to look at.
Thanks so much for your answer.

**Comment by maaslalani** [comment]
Hey @ITler, we just released https://github.com/charmbracelet/huh which is very similar to gum components but useful as a go library.

**Comment by ITler** [comment]
Yeah, I checked it out, yesterday. I think this would help me and addresses my needs. Thanks for following up
