### ISSUE TITLE
bash script passed to stdin fails after first gum call, unless wrapped in other control flow

### ISSUE THREAD

**Issue by taigrr** [charmbracelet/gum#447]
**To Reproduce**
put the following into `script.sh`:
```bash
#!/usr/bin/env bash

A=$(gum input --prompt='AAA: > ' --value='aaa')
B=$(gum input --prompt='BBB: >' --value='bbb')
```
then run `cat script.sh | bash` and see that only the first prompt runs.
(if you just run `./script.sh` the script behaves as expected.)

**Expected behavior**
Both prompts should run, and the script should behave the same way when piped as when executed directly.

Similarly:
```bash
#!/usr/bin/env bash

A=$(gum input --prompt='AAA: > ' --value='aaa')
echo $A
echo "you won't see $A or this line print out"
```

**Desktop (please complete the following information):**
 - OS: Linux

**Additional context**
The script will work if you wrap it in additional control flow:
```bash
#!/usr/bin/env bash
if true; then
A=$(gum input --prompt='AAA: > ' --value='aaa')
B=$(gum input --prompt='BBB: >' --value='bbb')
fi
```

[Relevant discord thread](https://discord.com/channels/1032368467246075914/1166162302005936210)

**Comment by piero-vic** [comment]
This happens because `gum input` also reads from stdin to set the value. In this case it's reading the part of the content of `script.sh`. Try run the script without setting the value of `gum input`.

```bash
#!/usr/bin/env bash

A=$(gum input --prompt='AAA: > ')
B=$(gum input --prompt='BBB: >')
```

You will probably see this.

![out](https://github.com/charmbracelet/gum/assets/71156605/b6146aef-1a91-48c2-ae32-0768fb3d9f60)

You can use process substitution if you really need the redirection. It works for me.

```bash
bash <(cat script.sh)
```

**Comment by taigrr** [comment]
Thanks, but I think you might be describing a  different issue. I'm not seeing STDIN eaten. In the coming days I can post a gif.

**Comment by caarlos0** [comment]
seems to be working on main 

![CleanShot 2024-12-09 at 17 00 07@2x](https://github.com/user-attachments/assets/828819c1-f29e-41e7-981a-147d54a08a55)


thanks @taigrr!

**Comment by taigrr** [comment]
I can try for myself later (I forgot about this issue tbh)

But does it work if you run:


cat foo.sh | bash

**Comment by taigrr** [comment]
confirmed, fixed!
