### ISSUE TITLE
[bug] gum filter can't use backspace to delete chars

### ISSUE THREAD

**Issue by GeekMasher** [charmbracelet/gum#45]
It seems that if you use `gum filter` doesn't allow for back spaces to delete chars.

*Test Case:*

```bash
echo "The Fellowship of the Ring" >> books.txt
echo "The Two Towers" >> books.txt
echo "The Return of the King" >> books.txt

cat books.txt | gum filter
```

![image](https://user-images.githubusercontent.com/2772944/181926057-5ddded41-050b-42fb-9018-aba47dfdcf9c.png)

Write `test` and then hit backspace to delete chars to then select Two Towers.

![image](https://user-images.githubusercontent.com/2772944/181926107-0e1ee231-8c98-4b04-a640-0357fdf7c0aa.png)

This is inarticulacy important when we make a typo while writing (happens to me far too much 🤣 ).

**Comment by maaslalani** [comment]
Hmm, I can't seem to reproduce this issue:

https://user-images.githubusercontent.com/42545625/181926329-79def197-0699-4d44-b6be-22c8c7da1e65.mov

**Comment by maaslalani** [comment]
@GeekMasher What machine are you using, I wonder if something is different with Windows vs Mac or potentially different keyboard keys, etc...

**Comment by GeekMasher** [comment]
@maaslalani Using a Linux Debian machine and installed Gum via `apt`.

When I pause, I am pressing backspace. Seems that `gum input` is the exact same but "sometimes" it works.

![dev](https://user-images.githubusercontent.com/2772944/181932057-4e29422f-6bd3-4efb-b622-811d1b863c0e.gif)

**Comment by maaslalani** [comment]
Ah I see, that makes sense as `gum input` and `gum filter` are using the same `textinput` so at least it is consistent. We definitely will try to debug and fix this. Does `Ctrl+W` or `Ctrl+U` work for you for deleting words / deleting all text?

**Comment by GeekMasher** [comment]
@maaslalani Yes, both of these work perfectly. I can use these for now but it would be great to see the backspace issue being fixed.

**Comment by maaslalani** [comment]
Totally, we will definitely fix the backspace issue! Just wanted to see if the problem was with deleting text in general or just the backspace key.

**Comment by GeekMasher** [comment]
@maaslalani I don't know if this helps but when I use [`fzf`](https://github.com/junegunn/fzf) (also written in Go) it works fine.

![dev-2](https://user-images.githubusercontent.com/2772944/181933966-31528eab-1da5-4137-af5d-1a2aa44b326c.gif)

**Comment by maaslalani** [comment]
Oh interesting gotcha! That's good news! Do you mind trying this example and seeing if backspace works for you in here https://github.com/charmbracelet/bubbletea/tree/master/examples/textinputs

Just trying to pinpoint whether the issue is in `gum` or deeper in the stack.

**Comment by maaslalani** [comment]
@GeekMasher We _think_ we may have found the issue (shoutout to @muesli), can you try the latest code on `main` and see if the backspacing issue is fixed for you?

**Comment by GeekMasher** [comment]
@maaslalani I just installed the main branch version and now works perfectly 🚀 :octocat: ! When will this change be released?

**Comment by maaslalani** [comment]
Awesome, @GeekMasher! Thank you for testing. I'll release `v0.3.0` this week for sure!

**Comment by maaslalani** [comment]
Actually, released it just now! https://github.com/charmbracelet/gum/releases/tag/v0.3.0

**Comment by GeekMasher** [comment]
@maaslalani After updating to v0.3.0 I can confirm it works 🚀  Thanks for all the hard work and amazing tools!

**Comment by maaslalani** [comment]
@GeekMasher Awesome! Glad to hear that fixed it! Thank you for reporting this issue and using our tools ❤️
