### ISSUE TITLE
spin output can not be piped

### ISSUE THREAD

**Issue by Ajnasz** [charmbracelet/gum#453]
**Describe the bug**
I can not pipe the output of the spin command to file or another command

**To Reproduce**
1. Execute a command with `gum spin --show-output` and redirect the output to a file, for example: `gum spin --show-output -- ls -l > files`
2. Check the content of the file `cat files` will be empty

**Expected behavior**
Be able to redirect the output of the command to a file

**Desktop (please complete the following information):**
 - OS: Debian Linux
 - Version: dd557baf6a935bd0aa0f98a8084f64da166d3bc5

**Additional context**
If I remove the [isTTY check](https://github.com/charmbracelet/gum/blob/dd557baf6a935bd0aa0f98a8084f64da166d3bc5/spin/command.go#L49) from the spin command.go, it works as I expect

I'm happy to open a pull request if it's a suitable fix

**Comment by piero-vic** [comment]
Hi @Ajnasz. The changes on #405 will fix this.

**Comment by jh-devv** [comment]
Yea, this is still an issue, for me; this makes `gum spin` basically unusable!

**Comment by Tschimmy** [comment]
Yes, the problem exists in version 0.12.0 for me as well.

**Comment by joshmedeski** [comment]
Yes, I can confirm it does not work on `v0.12.0` for me either.

**Comment by joshmedeski** [comment]
It's working on `gum version v0.12.1-0.20231207115433-c9afacc74b4b`, thanks!

**Comment by willian** [comment]
Yeah, same issue on `0.12.0` here, installed with Homebrew.

**Comment by willian** [comment]
Any plans to release `v0.12.1` soon?

**Comment by maaslalani** [comment]
We just released v0.13.0!

**Comment by willian** [comment]
Thanks!
