### ISSUE TITLE
--selected doesn't work properly when value not on first page

### ISSUE THREAD

**Issue by HairyMike** [charmbracelet/gum#455]
**Describe the bug**
When I use `--selected` with `gum choose`, it doesn't populate with the correct value when its not on the first page.

**To Reproduce**
```
choice=$(gum choose {1..20} --selected=12) && echo $choice
```

**Expected behavior**
I would expect to see 2nd element selected on 2nd page

**Screenshots**
![Screenshot 2023-11-27 at 16 07 15](https://github.com/charmbracelet/gum/assets/7034234/6e7ddc1d-7b21-4f2a-a07c-88d87d9559ab)

**Desktop (please complete the following information):**
 - OS: MacOS (intel)
 - Browser n/a
 - Version 0.11.0

**Comment by maaslalani** [comment]
Hi @HairyMike, thanks so much for the issue report, this is now fixed on main!

<img width="467" alt="image" src="https://github.com/charmbracelet/gum/assets/42545625/550b1016-a5f3-4bf9-969c-d36a4f46f2cf">

https://github.com/charmbracelet/gum/commit/6763de12e8e3ad28aa4c8baf4ce2816d564e1000
