### ISSUE TITLE
Docker image output is missing (sometimes vital) coloring.

### ISSUE THREAD

**Issue by ZOrfeas** [charmbracelet/gum#471]
**Describe the bug**
When using gum through the docker image, some colors are missing from the ouput.
This makes it basically non-functional in some cases, for example for `gum confirm` where the background of the currently chosen option is not visible:
<img width="612" alt="image" src="https://github.com/charmbracelet/gum/assets/65095699/57a1f3dd-39df-4fa9-ab1c-4be7e9dc8b42">

(I know this may also be on the docker side, but I'm hoping it's not, since this way I can introduce gum functionality for my team without having them install it manually)

**To Reproduce**
just running `docker run --rm -it -v "${PWD}":/workdir -w "/workdir" charmcli/gum:v0.11.0 confirm` should be enough

**Expected behavior**
Normal output

**Desktop:**
 - OS: macOS & Ubuntu 
 - Version: 0.11.0

**Comment by caleb-sb** [comment]
Hey, found this: https://stackoverflow.com/questions/33493456/docker-bash-prompt-does-not-display-color-output

Maybe it helps you?

**Comment by ZOrfeas** [comment]
Oh wow, it seems to fix it, very interesting. I'll need to see what this is actually doing.

Thanks a lot!
