### ISSUE TITLE
Change the color of gum filter placeholder message

### ISSUE THREAD

**Issue by Pouyeh** [charmbracelet/gum#475]
Hello

I am new to GitHub and I do not know where to find the answer to my question.  I have this code in my script, but I do not know how to change the color of "Gender". It shows up barely gray and I want to make it more readable, Blue mayb?

gender=$(echo -e "Male\nFemale" | gum filter --placeholder "Gender?")

I have read manual and tried examples, but none would change this color. 

Thank you for your help.

**Comment by maaslalani** [comment]
Hi @Pouyeh, thanks for opening this issue, it is solved by https://github.com/charmbracelet/gum/pull/480

To change the placeholder, you can install the latest `gum`:

```bash
go install github.com/charmbracelet/gum@main
```

And then use the `--placeholder.foreground` flag:

```
gum filter --placeholder "Whatever you want" --placeholder.foreground 212
```


Let us know if you have any more questions!
