### ISSUE TITLE
Combining format and style doesn't work as expected

### ISSUE THREAD

**Issue by MindfulMinun** [charmbracelet/gum#476]
**Describe the bug**
It's impossible to combine the output of `gum format` with `gum style`. The latter overrides the styles set by the first.

**To Reproduce**
```
gum style --border=rounded --padding="0 1" "$(gum format -t template '{{ Underline "Hello world" }}')"
```

**Expected behavior**
I expected the text "Hello world" to be underlined, while also surrounded by a border.

**Screenshots**
![image](https://github.com/charmbracelet/gum/assets/15158256/6d747023-1346-4032-ab39-0614f11cdeeb)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: gum version 0.13.0 (b0e5f32)

**Comment by maaslalani** [comment]
Hi @MindfulMinun, thanks so much for creating this issue!

It should be solved by #481 

<img width="878" alt="image" src="https://github.com/charmbracelet/gum/assets/42545625/55b49c44-7e2f-44e6-a4b6-528e8cd0c7af">

To get the latest changes (before we cut a release) you can install from the latest `main`:

```bash
go install github.com/charmbracelet/gum@main
```

And then retry your reproduction command:

```bash
gum style --border=rounded --padding="0 1" "$(gum format -t template '{{ Underline "Hello world" }}')"
```
