### ISSUE TITLE
huh forms using gum ? 

### ISSUE THREAD

**Issue by lgersman** [charmbracelet/gum#485]
I really love gum. But i also love huh forms (https://github.com/charmbracelet/huh) 😅 ! 

Are there any plans to integrate huh forms int gum ? 

I would really love to just use gum to huh render terminal forms.

One idea to provide a declarative form description to gum/hue would be using a provided JSON Schema (just like https://rjsf-team.github.io/react-jsonschema-form/ does for rendering JSON Schema forms to HTML).

Just an idea...

**Comment by maaslalani** [comment]
Hey @lgersman, we love `huh` forms and `gum` as well! We definitely want to integrate `huh` and `gum` together. First, we will swap out `gum` internals to use `huh` inputs:

* https://github.com/charmbracelet/gum/pull/484

And, then we will likely also provide some way to build forms using `gum` as well!

**Comment by lgersman** [comment]
Huh (:joy_cat:)  - sound promising !

Can't wait for it :heart:

**Comment by caarlos0** [comment]
so, we reverted back the huh integration.

in the end, gum and huh have two different goals, and the integration introduced too many breaking changes, some of which we couldn't fix without breaking huh as well.

that said, probably won't have huh forms integrated in gum... we might have a similar functionality in the future, but I do not know how that would look like yet.

all that being said, closing, but feel free to comment :)
