### ISSUE TITLE
Change Usage: gum confirm

### ISSUE THREAD

**Issue by zen0bit** [charmbracelet/gum#488]
I'm always frustrated if gum confirm button color don't respect my stylling

**Describe the solution you'd like**
Add option to change button color from default pink to anything else
`--button.color = 5`

**Describe alternatives you've considered**
Don't use gum confirm

**Comment by jacobshu** [comment]
@zen0bit I had this same problem. I was able to solve it this way:

`gum confirm --selected.background 5`

You can see the specific confirm option in [confirm/options.go](https://github.com/charmbracelet/gum/blob/7caf7d44ff5094e47c7795f2ded353185fc19cef/confirm/options.go#L17C10-L17C11) and the style reference in [style/options.go](https://github.com/charmbracelet/gum/blob/main/style/options.go).

**Comment by zen0bit** [comment]
Add to gum confirm help message:
--selected.background $GUM_CONFIRM_SELECTED_BACKGROUND
--unselected.background $GUM_CONFIRM_UNSELECTED_BACKGROUND

**Comment by zen0bit** [comment]
Change gum confirm usage message to something like this?

Usage: gum confirm [<prompt>]

Ask a user to confirm an action

Arguments:
  [<prompt>]    Prompt to display.

Flags:
  -h, --help                 Show context-sensitive help.
  -v, --version              Print the version number

      --default              Default confirmation action
      --affirmative="Yes"    The title of the affirmative action
      --negative="No"        The title of the negative action
      --timeout=0            Timeout until confirm returns selected value or default if provided ($GUM_CONFIRM_TIMEOUT)

Style Flags
  --prompt.foreground=""           Foreground Color ($GUM_CONFIRM_PROMPT_FOREGROUND)
  --selected.foreground="230"      Foreground Color ($GUM_CONFIRM_SELECTED_FOREGROUND)
  --unselected.foreground="254"    Foreground Color ($GUM_CONFIRM_UNSELECTED_FOREGROUND)
  --selected.background="1"        Selected Background Color ($GUM_CONFIRM_SELECTED_BACKGROUND)
  --unselected.background="2"      Unselected Background Color ($GUM_CONFIRM_UNSELECTED_BACKGROUND)

**Comment by zen0bit** [comment]
If anyone can point me where I can find it that USAGE: message for gum confirm, I could try my first commit in go...
Maybe
