### ISSUE TITLE
Using gum input the response if a single blank if the user just uses Enter

### ISSUE THREAD

**Issue by lbdyck** [charmbracelet/gum#493]
**Describe the bug**
Doing `ANS=$(gum input....)` and if the user just presses Enter the `$ANS` variable is a single blank and not null

**To Reproduce**
see above

**Expected behavior**
I would expect on an Enter with no response that the variable would be null and not a single blank.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows
 - Browser [e.g. chrome, safari] n/a
 - Version [e.g. 22] 11

**Comment by luciorq** [comment]
This is the default behavior for Shell Scripting, an empty string is the same as null in other languages.

if you wanna test if your output is empty use a test like:

```bash
ANS="$(gum input  --placeholder="Type something...")";
if [[ -n ${ans} ]]; then
  echo 'Not Empty';
else
  echo 'Empty';
  exit 1;
fi
```

**Comment by lbdyck** [comment]
Thank you - that is what I've done but thought I'd report in case it was a bug.

Love this tool
