### ISSUE TITLE
gum file - Options for show permissions and size. 

### ISSUE THREAD

**Issue by dzonekl** [charmbracelet/gum#494]
Using gum file would be nice to hide OS "noise" like file mode and sizes 

I notice latest filePicker  v0.18.0 has a new showPermissions  and showSize 

It would look like this: 

<img width="826" alt="image" src="https://github.com/charmbracelet/gum/assets/295240/2d1d8ca4-e39a-4050-8d97-ec9f8aaf0933">

<img width="616" alt="image" src="https://github.com/charmbracelet/gum/assets/295240/ff32487d-822c-4e91-9ebf-f45c17f058e5">

**Comment by caarlos0** [comment]
`--[no-]permissions` and `--[no-]size` are implemented on main.

thanks!
