### ISSUE TITLE
gum file - support --header

### ISSUE THREAD

**Issue by lbdyck** [charmbracelet/gum#497]
**Is your feature request related to a problem? Please describe.**
When using `gum file` I would like to provide instructions on how/what to select but there is no `--header` option. Using `echo` somewhat works but not as nice and using `gum style` also is not perfect.

**Describe the solution you'd like**
Support `--header` along with related color (foreground/background) options on `gum file`

**Describe alternatives you've considered**
Tried `echo` and `gum style` with minimal success.

**Additional context**
LOVE `gum`

**Comment by jamesbvaughan** [comment]
This would be great! A useful part of this behavior for me would be to have the header disappear after a file has been chosen, or at least to have an option to enable that behavior.

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/gum/pull/768
