### ISSUE TITLE
gum produces 11;rgb:1e1e/1e1e/1e1e in GNU/screen

### ISSUE THREAD

**Issue by ckujau** [charmbracelet/gum#498]
**Describe the bug**
Just installed v0.13.0 and wanted to show the help menu, all while running in a [GNU/screen](https://www.gnu.org/software/screen/) session and a string `11;rgb:1e1e/1e1e/1e1e` is printed to stdout.

**To Reproduce**

```
# Start GNU/screen w/o any local configuration

$ screen -c /dev/null -US test
$ gum --help | wc -l
^[]11;rgb:1e1e/1e1e/1e1e^[\24
 11;rgb:1e1e/1e1e/1e1e                          <== press ENTER again
-bash: 11: command not found
-bash: rgb:1e1e/1e1e/1e1e: No such file or directory
```

**Expected behavior**
`gum` should not display garbage to stdout when running in GNU/screen :-)

The same, w/o GNU/screen:

```
$ gum --help | wc -l
24
```
=> OK

**Desktop (please complete the following information):**
 - OS: Fedora 39
 - gum version v0.13.0 (a11d1ff)

**Additional context**

Running in [tmux](https://github.com/tmux/tmux) doesn't show this behaviour, so I guess it's some weird interaction with `screen`.

**Comment by ckujau** [comment]
Turns out the `TERM` variable makes a difference here (this [screen commit](https://git.savannah.gnu.org/cgit/screen.git/commit/?id=ad76d90 "terminfo goodness for 256-color support") tipped me off). Usually it's set to `xterm`:
```
$ echo $TERM
xterm

$ gum --help | wc -l
^[]11;rgb:1e1e/1e1e/1e1e^[\24

$ export TERM=screen-256color
$ gum --help | wc -l
24
```
Much better, no more garbage on the screen. Maybe this issue can be closed, but I've never seen such behaviour from other applications, so I'll just leave it open for a while.

**Comment by caarlos0** [comment]
this seems to be working on latest 0.14.5 and on main. 

will close, let me know if it still happens for you.

cheers!
