### ISSUE TITLE
gum has the right version on windows (scoop) ?

### ISSUE THREAD

**Issue by khengyun** [charmbracelet/gum#51]
### Discussed in https://github.com/charmbracelet/gum/discussions/27

<div type='discussions-op-text'>

<sup>Originally posted by **khengyun** July 29, 2022</sup>
it would be great if it combined with oh-my-posh</div>

**Comment by michaeltlombardi** [comment]
See #32 for some current limitations on windows.

I have a chocolatey package worked out and ready to publish, but held off for the moment since it can't be used in the current release for storing values without unexpected behavior. 😖

**Comment by caarlos0** [comment]
gum is not in scoop yet.

the `gum` available there is a maven wrapper: https://scoop.sh/#/apps?q=gum&s=0&d=1&o=true

**Comment by maaslalani** [comment]
Thanks for creating this issue @khengyun, we'll track this in #32 while we figure out Windows support and possibly create a scoop package after that is closed.
