### ISSUE TITLE
`gum spin` show output only when failed

### ISSUE THREAD

**Issue by devonpmack** [charmbracelet/gum#512]
**Is your feature request related to a problem? Please describe.**

Gum spin is great when nothing goes wrong we can hide all the output. But if it fails it currently swallows the error message.

**Describe the solution you'd like**

Show the output when gum spin fails.

**Describe alternatives you've considered**

**Additional context**

**Comment by maaslalani** [comment]
Hey @devonpmack, nice to see you here! 😄

Have you tried the `--show-output` flag? It will output both `stderr` and `stdout` while using `gum spin`. If I'm understanding correctly you only want the output on error though right? Perhaps we want a similar `--show-error` flag as implemented in:

* https://github.com/charmbracelet/gum/pull/440

**Comment by devonpmack** [comment]
Hiii @maaslalani 😲😲 Yes the --show-error will be perfect here! Thank you!

**Comment by maaslalani** [comment]
Fixed in #518!
