### ISSUE TITLE
`GUM_LOG_MINLEVEL` so that if this is set, only MINLEVEL+ status will be shown

### ISSUE THREAD

**Issue by hanoii** [charmbracelet/gum#519]
I think this might be a nice so that one could create different verbose levels without the need of adding a bunch of ifs on the scripts.

so if `export GUM_LOG_MINLEVEL=warn`

only `gum log --level warn|error|fatal` will be shown, and so on.

and you have gum log --level debug|info they won't show anything.

I think the default `none` should likely be a special case and that it has to be shown all the time.

**Comment by reitzig** [comment]
Similar: #519

**Comment by maaslalani** [comment]
Hey! Thank you for the issue! Closing this as it's a duplicate of #490 and we'll keep track of the issue there!
