### ISSUE TITLE
pager: add env variable for SoftWrap?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [charmbracelet/gum#526]
**Is your feature request related to a problem? Please describe.**
i'm trying to use `gum pager` from the `PAGER` variable, but had trouble passing the `--soft-wrap` option there in a straight-forward manner. moreover, i would rather set using the soft wrap as my default option, rather than having to explicitly pass it when invoking the program myself as well.

**Describe the solution you'd like**
adding/documenting an environment variable for the pager's SoftWrap option

**Describe alternatives you've considered**
returning to `PAGER=less`

**Comment by caarlos0** [comment]
refs #744
