### ISSUE TITLE
gum choose fails over ssh

### ISSUE THREAD

**Issue by iconoclasthero** [charmbracelet/gum#528]
**Describe the bug**
the ssh protocol allows for the use of commands over ssh.  gum choose fails.

**To Reproduce**

```
$ ssh 192.168.1.3 gum choose 1 2 3 
failed to start tea program: open /dev/tty: no such device or address
```

**Expected behavior**
I expect things to work over ssh...but since I don't do it a whole lot, I'm not sure what the limitations are.

**Desktop (please complete the following information):**
This is all on ubuntu/ubuntu derivatives, 22.04/24.04, gnu bash, openssh...the standard tools for ubuntu.

**Comment by caarlos0** [comment]
you'll need to request a TTY:

```sh
ssh 192.168.1.3 -t -- gum choose 1 2 3 
```
