### ISSUE TITLE
filter/choose: output the chosen index(s) **or** add display name support

### ISSUE THREAD

**Issue by MattSturgeon** [charmbracelet/gum#530]
**Is your feature request related to a problem? Please describe.**
If choices are kinda complex or verbose, I may wish to provide a display name instead just the raw value. Currently I would have to then map my display name back to the actual value.

**Describe the solution you'd like**
An option flag, such as `--indexed`, which causes the selection's index to be printed, instead of its value.

```shell
$ gum choose --indexed \
     "display name one" "display name two" "display name three" "display name four"

  display name one
> display name two
  display name three
  display name four

# Prints:
1
 ```

Note: the index should refer to the supplied arguments, not necessarily the order they are displayed in. Unless `--ordered` is used.

**Describe alternatives you've considered**
- Allowing a list of display names to be supplied in addition to the values to return.
- Allowing a list of displayname+value pairs to be supplied.

**Additional context**
It would also be nice to show additional context on hover; perhaps if one of the alternatives is used, then the raw value could be displayed below the display-name while that option is selected?

```shell
$ gum choose \
    --preview-value \
    --display-names "display name one" "display name two" "display name three" "display name four" \
    "actual_value_1" "actual_value_2" "actual_value_3" "actual_value_4"

  display name one
> display name two
      (actual_value_2)
  display name three
  display name four

# Prints:
actual_value_2
 ```
 
 This could be awkward to work with, since you'd need to assume half the arguments are display names and the other half are values...
 
 An alternative:

```shell
$ gum choose \
    --no-preview-value \
    --deliminator "=" \
    "display name one=actual_value_1" "display name two=actual_value_2" "display name three=actual_value_3" "display name four=actual_value_4"

  display name one
> display name two
  display name three
  display name four

# Prints:
actual_value_2
 ```

This would require additional data-processing on the user's part though... At that point it probably makes more sense to use the indexed approach? Or go all-out and use JSON instead of custom deliminator.

**Comment by maaslalani** [comment]
I personally prefer the deliminator approach. We can do this quite easily now that we use `huh` for the choose command.

**Comment by dikesh** [comment]
Should this issue be reopened as the implementation is reverted?

**Comment by MattSturgeon** [comment]
> Reverting this for now as there's a typo in the help text. We'll fix and re-add after the next release.

Seems a little heavy handed to revert a feature over a documentation typo,[^1] but regardless if the intention is to immediately un-revert after a release is branched off then hopefully we won't need this re-opened for long enough for it to be worth worrying about :slightly_smiling_face: 

[^1]: I would've suggested either just fixing the typo, or reverting on a "release candidate" branch, so that the "main" branch is left unaffected.

**Comment by MattSturgeon** [comment]
I was a bit upset to come back to this issue 8 months later only to find that a) the PR wasn't re-applied and b) it now has merge conflicts.

However, looking a bit closer, it seems a very similar feature request already existed in #406, which was picked up much later in #783.

So this is available as the `--label-delimiter` option.
