### ISSUE TITLE
Gum outputs random characters

### ISSUE THREAD

**Issue by TobiZehPanda** [charmbracelet/gum#532]
**Describe the bug**
Gum outputs some random characters when running some commands when using rxvt-unicode terminal

**To Reproduce**
Run 'gum filter' or 'gum write' or 'gum *'

**Expected behavior**
Expected gum to run with placeholder text, but it shows random characters.
Only applies to rxvt-unicode

**Screenshots**
![2024-04-04_15-45](https://github.com/charmbracelet/gum/assets/10318171/4af8b746-72b4-4311-b383-aa8427f87bfb)
![2024-04-04_15-45_1](https://github.com/charmbracelet/gum/assets/10318171/a9d08161-068f-495c-a2cc-2eba3f6f886d)

**Desktop (please complete the following information):**
OS: Archlinux
Terminal: rxvt-unicode
![2024-04-04_15-46](https://github.com/charmbracelet/gum/assets/10318171/6098212c-2084-403c-adf4-96963f3e8243)

**Comment by piero-vic** [comment]
Hi @TobiZehPanda.

I think this is an issue with the terminal configuration. Maybe you need to enable support for 256 colors. Try adding this line to `~/.Xresources` and see if anything changes.

```
URxvt.termName: screen-256color
```

**Comment by meowgorithm** [comment]
@TobiZehPanda, mind testing this with the latest release of Gum? We're not able to reproduce it over here, but if you're still experiencing it I believe we can apply a workaround in the codebase.

**Comment by TobiZehPanda** [comment]
@meowgorithm it is fixed in the latest version of gum!
