### ISSUE TITLE
Filter and/or select `gum choose` options via fuzzy search

### ISSUE THREAD

**Issue by EconomicTouristsArmLate** [charmbracelet/gum#539]
**Is your feature request related to a problem? Please describe.**
Given many choice options in a `gum choose` prompt, i want to quickly navigate to my desired option.
Pressing arrows or j/k becomes tedious quickly.

**Describe the solution you'd like**
(Fuzzy-) filter the available options from keyboard input, quickly reducing the available options to 1.

Applied to the conventional-commits example from the readme, this would mean entering `ref<return>` is enough  to choose the type of change.

This clashes with the j/k keybinds for cursor movement.
Consider putting those on `ctrl+j`/`ctrl+k` instead.

**Describe alternatives you've considered**
Instead of moving j/k keybinds elsewhere, put the fuzzy match feature behind a mode toggle, eg binding to `/`.

**Additional context**
I expected this to work, coming from other modern CLI prompt tools: 
- https://github.com/junegunn/fzf-git.sh
- https://github.com/AlecAivazis/survey

**Comment by EconomicTouristsArmLate** [comment]
I just realized there is `gum filter` which basically implements my usecase. Feel free to close

**Comment by maaslalani** [comment]
Awesome, thanks for following up!
