### ISSUE TITLE
Pressing Ctrl+C in gum filter doesn't exit as expected

### ISSUE THREAD

**Issue by Amolith** [charmbracelet/gum#54]
Pressing <kbd>Ctrl</kbd> + <kbd>C</kbd> when in a `gum filter` dialogue doesn't actually quit anything at the moment, it just exits and continues with whatever line the cursor was on.

I have a short script that, *in theory*, would allow me to open a terminal, run a command, get a list of all my guitar tabs, select one, open it in my document reader, close the document reader, get the selection dialogue back, and repeat until I press <kbd>Ctrl</kbd> + <kbd>C</kbd> to quit.

```bash
#!/bin/bash
set -e

cd "$HOME/Documents/Music/Guitar" || exit 1

while :; do
    FILE="$(gum filter --placeholder="Choose a song…")" || exit
    devour zathura "$FILE"
done
```

In practise, the only way to quit is closing the entire terminal because `filter` doesn't behave as expected when sent `SIGINT`

**Comment by muesli** [comment]
Thanks for the issue, @Amolith. Should be fixed in v0.2.0!

**Comment by Amolith** [comment]
Pfft I read the release notes, apparently skimmed over them way too quickly, didn't see it mentioned, and opened the issue.

Thanks and sorry for the noise! :sweat_smile:

**Comment by muesli** [comment]
No worries! Please do confirm it's working as intended for you!

**Comment by Amolith** [comment]
I just did and it works exactly as expected :)
