### ISSUE TITLE
add (shift) tab keybindings

### ISSUE THREAD

**Issue by KiaraGrouwstra** [charmbracelet/gum#543]
**Is your feature request related to a problem? Please describe.**
quite some applications offer (shift) tab keybindings to navigate choices

**Describe the solution you'd like**
have gum similarly offer (shift) tab keybindings to navigate choices

**Describe alternatives you've considered**
be more conscious about what kind of application i'm in before activating muscle memory

**Comment by caarlos0** [comment]
we already use tab to check an item if many options could be checked, so I don't think we can implement this, unfortunately.
