### ISSUE TITLE
0.14.0 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [charmbracelet/gum#549]
👋 it looks like 0.14.0 release was not completed, ie the github release did not get created as 0.13.0, raise this issue for some awareness. Thanks! 🙏 

relates to https://github.com/Homebrew/homebrew-core/pull/170227

**Comment by chenrui333** [comment]
ping @maaslalani thanks!

**Comment by maaslalani** [comment]
Thanks so much @chenrui333, release is now complete!

**Comment by Dominiquini** [comment]
The binaries for the version 0.14.0 don't appear on the GitHub releases page!

Thanks.

**Comment by maaslalani** [comment]
Thanks for the catch @Dominiquini!

@caarlos0 is there a way to attach GoReleaser binaries retroactively to a release or would I have to cut a new one.

**Comment by caarlos0** [comment]
in this particular case I think you could have re-run it https://github.com/charmbracelet/gum/actions/runs/8854306023/job/24317076808


that said, will make fury retry on 5xx
