### ISSUE TITLE
Pressing `a` to select all in `gum choose` no longer works

### ISSUE THREAD

**Issue by annervisser** [charmbracelet/gum#550]
**Describe the bug**
Previously, pressing `a` on a multi-select `gum choose` prompt would select all items.
This behaviour was broken in `0.14`, I'm assuming because of this PR: https://github.com/charmbracelet/gum/pull/521

**To Reproduce**
1. Run `gum choose --no-limit x y z`
2. Press `a`
5. Nothing happens

**Expected behavior**
1. Run `gum choose --no-limit x y z`
2. Press `a`
5. All items are selected

**Screenshots**
N/A

**Desktop:**
 - OS: Pop!OS 22.04 (based on Ubuntu 22.04)
 - Gum 0.14.0

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/huh/pull/325
