### ISSUE TITLE
Release 0.14.0 does not contain any release assets

### ISSUE THREAD

**Issue by nicholasdille** [charmbracelet/gum#551]
The release workflow failed to upload the release assets. See https://github.com/charmbracelet/gum/actions/runs/8854306023/job/24317076808

**Comment by 5ouma** [comment]
Assets were added to [v0.14.0](https://github.com/charmbracelet/gum/releases/tag/v0.14.0) but tar can't extract the specified files from the `tar.gz`.
If I change to `v0.13.0`, tar correctly extracts the files.

```shell
> curl -sL 'https://github.com/charmbracelet/gum/releases/download/v0.14.0/gum_0.14.0_Linux_x86_64.tar.gz' | tar -x 'gum'

tar: gum: Not found in archive
tar: Error exit delayed from previous errors.
```

**Comment by nicholasdille** [comment]
The contents have changes but apart from the subdir everything stay the same:

```
$ curl -sSLf https://github.com/charmbracelet/gum/releases/download/v0.14.0/gum_0.14.0_Linux_x86_64.tar.gz | tar -tvzn
-rw-r--r-- runner/docker  1080 2024-04-30 14:55 gum_0.14.0_Linux_x86_64/LICENSE
-rw-r--r-- runner/docker 12685 2024-04-30 14:55 gum_0.14.0_Linux_x86_64/README.md
-rw-r--r-- runner/docker 25877 2024-04-30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.bash
-rw-r--r-- runner/docker 18518 2024-04-30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.fish
-rw-r--r-- runner/docker 14755 2024-04-30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.zsh
-rw-r--r-- runner/docker  5061 2024-04-30 14:56 gum_0.14.0_Linux_x86_64/manpages/gum.1.gz
-rwxr-xr-x runner/docker 27279512 2024-04-30 14:56 gum_0.14.0_Linux_x86_64/gum
```

**Comment by 5ouma** [comment]
Yes, that's right. But it occurred not only on my machine but also on [GitHub Actions](https://github.com/5ouma/dotfiles/actions/runs/8903612023/job/24451636200#step:5:8).
Is it probably related to https://github.com/charmbracelet/gum/issues/551#issue-2270747928? GoReleaser couldn't add assets, which might have made Tarball strange.

**Comment by nicholasdille** [comment]
In my opinion, the behaviour of goreleaser has changed between the time when v0.13.0 and v0.14.0 was released. Rerunning the release workflow does not mess with the tarball.

But, IMHO, this is fixed.
