### ISSUE TITLE
Unnecessary whitespace output

### ISSUE THREAD

**Issue by tralce** [charmbracelet/gum#554]
**Describe the bug**
`gum choose` outputs six blank lines after the chooser now, as of v0.14.0

**To Reproduce**
```
gum choose x y z
 > x
   y
   z






```

**Expected behavior**
```
gum choose x y z
 > x
   y
   z
```
**Screenshots**
![image](https://github.com/charmbracelet/gum/assets/11371119/53a028dc-186d-417c-b134-ae9299b470e7)

**Desktop (please complete the following information):**
 - OS: Arch Linux, untested elsewhere
 - Browser: Firefox but irrelevant
 - Version: irrelevant

**Additional context**
This started with the upgrade to 0.14.0.

**Comment by meowgorithm** [comment]
Thanks for flagging this. So what it basically looks like here is now we're respecting the height (which defaults to 10) whereas we were formerly trimming empty lines if there were fewer than the height.

Gum v0.13.x:
<img width="204" src="https://github.com/user-attachments/assets/441b5ff3-dcf6-4b61-af9e-0845b97612a9">
<img width="251" src="https://github.com/user-attachments/assets/1e681612-5cf7-4b13-b823-4316c4b005a5">


Gum v0.14.x:
<img width="329" src="https://github.com/user-attachments/assets/75be2075-1fc6-4ca1-a5d6-ae4566c4e859">

I _think_ what we're seeing in v0.14.0 is correct behavior, however it's worth considering whether to trim empty lines if `--height` isn't set.

**Comment by bashbunni** [comment]
@meowgorithm fwiw I think we should trim whitespace if height isn't set

**Comment by tralce** [comment]
> @meowgorithm fwiw I think we should trim whitespace if height isn't set

I wholeheartedly agree with this. Thanks @bashbunni

**Comment by meowgorithm** [comment]
Sounds good to me; this was the former behavior after all.

**Comment by caarlos0** [comment]
I think `--height 0` fixes it... maybe it should be the default?

same thing with `--width 0` 🤔

**Comment by tralce** [comment]
@caarlos0 indeed it does; thank you. I do not see this trick in the documentation.

I agree it should be the default.
