### ISSUE TITLE
gum write completion (intended?)

### ISSUE THREAD

**Issue by NQMVD** [charmbracelet/gum#555]
**Describe the bug**
Pressing enter now completes the prompt.

**Expected behavior**
Pressing ctrl + d should complete the prompt, while enter should jump to a new line.

**Desktop:**
 - OS: Arch Linux

**Comment by polm** [comment]
This is also affecting me on Arch. I tried downloading the binaries from here directly but they have the same issue.

**Comment by polm** [comment]
This seems to be intentional, see #572.
