### ISSUE TITLE
gum confirm no longer lets you disable negative message

### ISSUE THREAD

**Issue by txotxopue** [charmbracelet/gum#559]
**Describe the bug**
Prior to v0.14.0 you could execute:
`gum confirm --affirmative="OK" --negative="" "Warning!"`
And get a dialog with just the affirmative button. That's no longer the case. Now you get an empty negative button too.

**To Reproduce**
Just execute:
`gum confirm --affirmative="OK" --negative="" "Warning!"`

**Expected behavior**
Get a dialog with just the affirmative button.

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v0.14.0

**Comment by maaslalani** [comment]
Hey @txotxopue, thanks for the issue. This is fixed in huh and will be fixed in gum soon as well after we bump the dependency!

**Comment by caarlos0** [comment]
I think this is fixed on main
