### ISSUE TITLE
:memo: Document --password  option in the README.md :baby: 

### ISSUE THREAD

**Issue by adriens** [charmbracelet/gum#56]
:bulb: Hi, could you document the [recently released](https://github.com/charmbracelet/gum/releases/tag/v0.2.0) (very useful ) [`--password ` option ](https://github.com/charmbracelet/gum/commit/5b7d0064874e732957525e9030402be1043695c5) in the README :point_right:  so people are aware it exists :grey_question: 

![image](https://user-images.githubusercontent.com/5235127/182047417-1d135ba1-4ba9-452f-a22f-41f36bc8b8c9.png)

**Comment by yadunandanbhat** [comment]
I can work on this and open a pr?

**Comment by adriens** [comment]
> I can work on this and open a pr?

In fact the main thing is to find the most appropriate place.. that's why I did not open a PR :sweat_smile:

**Comment by maaslalani** [comment]
The most appropriate place would likely be here: https://github.com/charmbracelet/gum#input

**Comment by yadunandanbhat** [comment]
yes that seems a sensible place to put it!

**Comment by maaslalani** [comment]
Fixed! https://github.com/charmbracelet/gum/commit/cdd7b7b6ba8ac721cfd76687770a5a1788ab9d78

**Comment by adriens** [comment]
:point_down: 
![image](https://user-images.githubusercontent.com/5235127/182507558-f492b7ba-fd30-4d7d-979b-9ac01e4dacd5.png)
