### ISSUE TITLE
Gum spin only accepts a hard-coded command

### ISSUE THREAD

**Issue by Tazi0** [charmbracelet/gum#564]
**Is your feature request related to a problem? Please describe.**
I have created a function which passes a command which the gum spin needs to execute:
```bash
repo_update() {
....
}

spin() {
  local TITLE="${*: -1}"
  local COMMANDO="${*:1:$(($#-1))}"
  gum spin "$COMMANDO" --spinner="dot" --title="$TITLE"
}
```
Usage:
```bash
spin repo_update "Updating repo"
```

But this only gives me an error, it does not execute it

**Describe the solution you'd like**
that the gum spin command runs as expected and accepts strings which it runs.

**Comment by patelharsh9797** [comment]
Did you found any solution?

**Comment by Tazi0** [comment]
> Did you found any solution?
@patelharsh9797 

yes, this is the current function i have:
```sh
# param 1: command to execute
# param 2..x: command argument(s)
# param x+1: title
spin() {
  local TITLE="${*: -1}"
  local COMMANDO="${*:1:$(($#-1))}"
  local PARAMS=()

  # if [[ $DEBUG == true ]]; then
  #   PARAMS+=("--show-output")
  # fi

  output debug "Executing: $COMMANDO"
  gum spin --spinner="jump" --title="$TITLE" --show-output "${PARAMS[@]}" -- bash -c "source $SCRIPT_DIR/_git-pre.sh && $COMMANDO"
}
```
