### ISSUE TITLE
gum choose v0.14.0: timeout no longer working

### ISSUE THREAD

**Issue by daviehh** [charmbracelet/gum#565]
**Describe the bug**
`gum choose --selected="foo" --timeout=3s "a" "b" "foo" "d"`
timeout no longer working

**To Reproduce**
1. `gum choose --selected="foo" --timeout=3s "a" "b" "foo" "d"`
2. No progress

**Expected behavior**
timeout after 3s

**Desktop (please complete the following information):**
 - OS: macos 14.4.1

Incidentally

https://github.com/charmbracelet/gum/blob/4222e59c25dbd25423285e5d088b8c66d758c87b/choose/options.go#L27

typo for `GUM_CCHOOSE_TIMEOUT`?

**Comment by MrOggy85** [comment]
I think this change broke the timeout: https://github.com/charmbracelet/gum/pull/522
It seems like the timeout functionality was not implemented when using the new framework @maaslalani
