### ISSUE TITLE
gum choose does not center Yes and No in a centered manner like the previous gum versions

### ISSUE THREAD

**Issue by D3vil0p3r** [charmbracelet/gum#566]
**Describe the bug**
In the previous gum version, `gum confirm` command placed the buttons Yes and Not in a centered manner with respect to the length of the prompt string. For example, I had:

![image](https://github.com/charmbracelet/gum/assets/83867734/547d1e63-d293-4e70-b02e-efaa42247d32)

By the latest version, I don't get it anymore but the choices are aligned to left:

![image](https://github.com/charmbracelet/gum/assets/83867734/40fc454e-35d2-4ddb-9532-2b28eeff3b48)

**Comment by aymanbagabas** [comment]
Fixed in https://github.com/charmbracelet/huh/commit/24a367485f6b1d5941c9ac88a65bb41543ec5f34

**Comment by meowgorithm** [comment]
This is now on `main` and will be available in the next release.
