### ISSUE TITLE
Can't extract with `tar -x`

### ISSUE THREAD

**Issue by 5ouma** [charmbracelet/gum#567]
**Describe the bug**
Tar can't extract the specified files from the tar.gz.
If I change to v0.13.0, tar correctly extracts the files.

**To Reproduce**
```shell
> curl -sL 'https://github.com/charmbracelet/gum/releases/download/v0.14.0/gum_0.14.0_Linux_x86_64.tar.gz' | tar -x 'gum'

tar: gum: Not found in archive
tar: Error exit delayed from previous errors.
```

**Expected behavior**
Extract only specified files.

**Additional context**
It occurred not only on my machine but also on [GitHub Actions](https://github.com/5ouma/dotfiles/actions/runs/8903612023/job/24451636200#step:5:8).
Is it probably related to https://github.com/charmbracelet/gum/issues/551#issue-2270747928? GoReleaser couldn't add assets, which might have made Tarball strange.

**Related**
https://github.com/charmbracelet/gum/issues/551
https://github.com/charmbracelet/gum/issues/549

**Comment by ptrcnull** [comment]
have you actually looked at the archive?
```
$ curl -sL https://github.com/charmbracelet/gum/releases/download/v0.14.0/gum_0.14.0_Linux_x86_64.tar.gz | tar tv 
-rw-r--r--  0 runner docker   1080 Apr 30 14:55 gum_0.14.0_Linux_x86_64/LICENSE
-rw-r--r--  0 runner docker  12685 Apr 30 14:55 gum_0.14.0_Linux_x86_64/README.md
-rw-r--r--  0 runner docker  25877 Apr 30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.bash
-rw-r--r--  0 runner docker  18518 Apr 30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.fish
-rw-r--r--  0 runner docker  14755 Apr 30 14:56 gum_0.14.0_Linux_x86_64/completions/gum.zsh
-rw-r--r--  0 runner docker   5061 Apr 30 14:56 gum_0.14.0_Linux_x86_64/manpages/gum.1.gz
-rwxr-xr-x  0 runner docker 27279512 Apr 30 14:56 gum_0.14.0_Linux_x86_64/gum
```

**Comment by 5ouma** [comment]
Ah, that's completely my fault...
I'm sorry to confuse you guys...
