### ISSUE TITLE
:lady_beetle: Minor bug > misalignment issue on gum style with emojis

### ISSUE THREAD

**Issue by adriens** [charmbracelet/gum#57]
When playing with the following code : 

```
clear
gum style \
	--foreground 212 --border-foreground 212 --border double \
	--align center --width 50 --margin "1 2" --padding "2 4" \
	'📦 Colis-nc 📦' 'Suivre son colis avec RapidAPI et httpie'
```

I felt on a minor alignment bug (probably due to emoji) : 

![image](https://user-images.githubusercontent.com/5235127/182047956-3ab21fa5-01e5-4dc0-a4a4-1daf757dfd8c.png)

**Comment by muesli** [comment]
I'm afraid this might be something we're not able to solve. Calculating emoji widths is to a certain degree guesswork, as we don't know

1. the font your terminal is using
2. how your terminal's cell rendering behaves with that specific font

As an example, this is how it looks on my system (Konsole):

![image](https://user-images.githubusercontent.com/146378/182048074-be71fa78-3dd8-4aa6-9e48-6facb0c68677.png)

**Comment by adriens** [comment]
>  Calculating emoji widths is to a certain degree guesswork, 

Indeed :sweat_smile: 

:point_right: Looks perfectly clean on my local terminal too : 

![image](https://user-images.githubusercontent.com/5235127/182048774-597a16fe-b4f3-46f4-a4ad-9cc6b7c33169.png)


I could produce the bug on Killercoda :+1:

**Comment by adriens** [comment]
This issue should probably tagged as a `wontfix` :thinking:

**Comment by maaslalani** [comment]
Thanks @adriens for opening this issue! We should have a solution for this (better guess work in the future).
