### ISSUE TITLE
Gum write can no longer add new lines

### ISSUE THREAD

**Issue by jscarrott** [charmbracelet/gum#572]
**Describe the bug**
Pressing enter completes the prompt

Previously esc or ctrl-d would complete the prompt
**To Reproduce**
Use gum 0.14.0

**Expected behavior**
A way of doing multi-line strings

**Comment by MikaelFangel** [comment]
Apparently huh is breaking change when it comes to keybindings and the help message for `gum write` is:
> alt+enter / ctrl+j new line • ctrl+e open editor • enter submit

**Comment by maaslalani** [comment]
Hey, apologies for the breaking change. `Alt+Enter` or `Ctrl+J` would add new lines as @MikaelFangel  mentioned!

**Comment by jscarrott** [comment]
Aha the help text was overwritten in the scripts that use it so I didn't see that change.

**Comment by mojodna** [comment]
FWIW, the README still references `ctrl+d` as the way to complete text entry.
