### ISSUE TITLE
gum input header flags can output an incorrect render

### ISSUE THREAD

**Issue by ndsizeif** [charmbracelet/gum#582]
**Describe the bug**
Setting some of the header properties of `gum input` including, `--header.align` and `--header.height`, can cause rendering over subsequent lines of the output.

**To Reproduce**
This simple bash script sets a header and aligns it inside a border.
```sh
#!/bin/bash

term_width=$(tput cols)
WIDTH=$((term_width / 2))

gum input \
	--header="example header" \
	--header.width=$WIDTH \
	--header.align="center" \
	--header.border="thick"
```
![border14 0](https://github.com/charmbracelet/gum/assets/84802637/bfd8d664-4081-42b5-8a5b-110290425649)

Using a border makes the behavior apparent, but output is also affected without a border. Setting header height to more than 2 obscures the placeholder.
```sh
gum input \
	--header="example header" \
	--header.height="4"
```
![height14 0](https://github.com/charmbracelet/gum/assets/84802637/2597cff6-1327-4e7c-8642-aa2f461aedc7)

**Expected behavior**
The above commands should render as they do using `gum v0.13.0`

![border13 0](https://github.com/charmbracelet/gum/assets/84802637/00fd2315-146d-423f-a4ae-ddc00d7f5405)

![height13 0](https://github.com/charmbracelet/gum/assets/84802637/1ebc799c-7d46-41d1-b94f-05dd8933fa3e)

```
gum version 0.14.0 (295a671)

Description:    Manjaro Linux
Release:        24.0.0
Codename:       Wynsdey
```

**Comment by caarlos0** [comment]
this should be fixed by #634

**Comment by caarlos0** [comment]
good find, seems to be related to the height, not sure how yet, though

**Comment by caarlos0** [comment]
should be fixed on main!
