### ISSUE TITLE
`--cursor.foreground` not respected for `gum input` or `gum write`

### ISSUE THREAD

**Issue by lachholden** [charmbracelet/gum#583]
**Describe the bug**
Setting different values for `--cursor.foreground` with `gum write` or `gum input` doesn't change the cursor colour - it remains the default cyan.

**To Reproduce**
- Run `gum input --cursor.foreground='1"` in the shell
- The cursor flashes cyan

**Expected behavior**
The cursor should flash ANSI red

**Screenshots**
![image](https://github.com/charmbracelet/gum/assets/4650587/9c02e0b6-0516-4a71-a622-be02ebddcc47)

**Desktop (please complete the following information):**
- Windows 11 running gum v0.14.0 in git bash after installation with winget
- Using the Windows Terminal app

**Comment by meowgorithm** [comment]
Hi! This is now available in [Gum v0.14.2](https://github.com/charmbracelet/gum/releases/tag/v0.14.2).
