### ISSUE TITLE
Helping hand

### ISSUE THREAD

**Issue by Tazi0** [charmbracelet/gum#585]
**Is your feature request related to a problem? Please describe.**
`gum write` is now based upon `huh` as well as other commands. This changed the keyboard shortcuts for closing and starting a new line. While I was diving myself into this `huh` repo, I saw some help shortcuts which looked really nice!

**Describe the solution you'd like**
Technically called `tea.KeyMsg`, I would like to request an addition to (most likely) all commands to add a key + message at the bottom. Like in bubble tea: https://github.com/charmbracelet/bubbletea/tree/master/examples/help

**Additional context**
![image](https://github.com/charmbracelet/gum/assets/45716542/ea19ac0e-81d2-4c34-bfb1-193cd5019b19)
^ the bottom row

**Comment by maaslalani** [comment]
Hey! This is a great idea! We'll add this to `gum`, thanks for the reminder / idea.

**Comment by maaslalani** [comment]
Thanks so much for the issue, we've added it to #587!
