### ISSUE TITLE
`gum input` mangling prompt (docs need updated)

### ISSUE THREAD

**Issue by tj-smith47** [charmbracelet/gum#586]
**Describe the bug**
Previously functional `gum input` blocks in a script my company uses are now mangled - r

**To Reproduce**
Consider the following block in a script:
```bash
#!/usr/bin/env bash

REPO_NAME=$(gum input --prompt "Enter the name (title case) of the repository to add a devcontainer files (e.g., Some API): ")
[[ -z "${REPO_NAME}" ]] && (echo "No repository name provided. Exiting."; exit 1)
```

The input received is correct if typed, but it's a poor user experience not being able to see text when typing in a field that isn't a password.

**Expected behavior**
No random newlines, all prompt text shows, input visible as I type.

**Screenshots**
Given the above excerpt from the script, this is the output (before it was on a single line, text was visible):
<img width="677" alt="Screenshot 2024-05-20 at 17 32 24" src="https://github.com/charmbracelet/gum/assets/114961514/701fdf11-9a14-4b5e-9a75-f4b1c9678c65">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A
 - Version: 14.5

**Additional context**
Nothing changed in the script since it last worked flawlessly, so it seems to be the recent upgrade to gum.

**Comment by tj-smith47** [comment]
I just figured out setting `--width` resolves this - it seems unintentional to push the burden of counting the length of each line to the user when previously this wasn't necessary. If not, it was not listed in the changelog, nor is `--width` used in a single example.

**Comment by caarlos0** [comment]
you can also use `--width 0` to use the terminal size
