### ISSUE TITLE
gum confirm: Handling exit code 130 isn't working anymore

### ISSUE THREAD

**Issue by mylinuxforwork** [charmbracelet/gum#588]
Just tried to test the handling of the exit code 130 CTRL+C on a gum confirm script.
When I press CTRL-C the following message appears: unable to run confirm: user aborted and below :: Update canceled.

This is my script:

```
if gum confirm "DO YOU WANT TO START THE UPDATE NOW?" ;then
    echo ":: Update started."
elif [ $? -eq 130 ]; then
        exit 130
else
    echo ":: Update canceled."
    exit;
fi
```

Is it possible that the exit code 130 is not supported anymore on gum confirm?

**Comment by MikaelFangel** [comment]
The exit-code for both "No" and `CTRL+C` is now 1. You can check this with the following snippet:

```
gum confirm; echo $?
```

**Comment by MikaelFangel** [comment]
Okay, I investigated it a bit more and the issue you are experiencing is actually linked to the implementation of huh? not handling the user aborted properly. So, it should be fixed by the PR I've linked to the issue now.
