### ISSUE TITLE
Add preselected options when using filter command

### ISSUE THREAD

**Issue by sestegra** [charmbracelet/gum#593]
**Is your feature request related to a problem? Please describe.**
I'm using gum to let the user to select from a list of options with some of them are defaults.
To ease the selection, I need to have a list of preselected options using filter command.

**Describe the solution you'd like**
Add `--selected` flag when using `gum filter` command to preselect options.

**Describe alternatives you've considered**
No alternative found yet.

**Additional context**
N/A

**Comment by caarlos0** [comment]
see https://github.com/charmbracelet/gum/pull/777
