### ISSUE TITLE
Input placeholder behavior inconsistent with readme

### ISSUE THREAD

**Issue by leighmcculloch** [charmbracelet/gum#60]
The readme shows the following:
<img width="714" alt="Screen Shot 2022-07-31 at 9 32 45 PM" src="https://user-images.githubusercontent.com/351529/182074690-a6b1c008-99e8-490c-a67e-65a9a1f46067.png">

However, using v0.2.0 the following happens when running the same command:

<img width="867" alt="Screen Shot 2022-07-31 at 9 56 48 PM" src="https://user-images.githubusercontent.com/351529/182075279-8906085b-6cd1-4e20-968f-fc8463030ea6.png">

<img width="867" alt="Screen Shot 2022-07-31 at 9 56 55 PM" src="https://user-images.githubusercontent.com/351529/182075256-f5259b81-327f-4644-b415-5659dc952bb5.png">
 
The example appears to suggest the placeholder will be like a prompt on the left, but then that isn't the case.

**Comment by maaslalani** [comment]
Yes you're right the command in the README is not the same as the command typed out in the GIF

**Comment by leighmcculloch** [comment]
Ah! So it is. I copy-pasted the command above the screenshot. They were very similar. Thanks for pointing that out.
