### ISSUE TITLE
gum choose --selected=: cursor do not appear

### ISSUE THREAD

**Issue by vt-alt** [charmbracelet/gum#606]
**Describe the bug**
With `gum choose --selected=` when selected item is out of the screen cursor do not appear nor item is selected.

**To Reproduce**
```
$ seq 22 | gum choose --selected=11
┃ Choose:
┃   1
┃   2
┃   3
┃   4
┃   5
┃   6
┃   7
┃   8

↑ up • ↓ down • / filter • enter submit
```

**Expected behavior**
Version (0.12.0) had it working correctly:
```
$ seq 22 | gum choose --selected=11
> 11
  12
  13
  14
  15
  16
  17
  18
  19
  20
```

**Desktop (please complete the following information):**
 - OS: ALT Linux
 - gum version 0.14.1

**Comment by bashbunni** [comment]
fwiw it's not working with huh's multi select either (when choose's `limit` > 1)

**Comment by caarlos0** [comment]
fixed on main

thanks!

**Comment by vt-alt** [comment]
That was a major bug for me. Thanks for fixing! (Untested).
