### ISSUE TITLE
gum spin messes the screen

### ISSUE THREAD

**Issue by vt-alt** [charmbracelet/gum#607]
**Describe the bug**
gum started to mess the screen when showing output (regression).

**To Reproduce**
This is minified example:
```
$ gum spin --show-output -- seq 22 | less
1
 2
  3
   4
    5
     6
      7
       8
        9
         10
           11
             12
               13
                 14
                   15
                     16
                       17
                         18
                           19
                             20
                               21
                                 22
```
Actual use case is `curl`ing log files and piping it to `less` causing total screen mess after `less` exits **while** spinner was still active: `gum spin --show-output -- curl -sSf -L https://git.altlinux.org/tasks/347163/build/100/x86_64/log | less`

**Expected behavior**
0.12.0 worked better:
```
$ gum spin --show-output -- seq 22 | less
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
```
`curl` example worked good too.

**Desktop (please complete the following information):**
 - OS: ALT Linux
 - gum version 0.14.1

**Comment by meowgorithm** [comment]
Thanks for the heads up, @vt-alt! This is fixed in `main` and’ll be available in the next release.

**Comment by meowgorithm** [comment]
Hi again! Just a note that this fix is now available in [Gum v0.14.2](https://github.com/charmbracelet/gum/releases/tag/v0.14.2).

**Comment by aymanbagabas** [comment]
https://github.com/charmbracelet/gum/pull/621 has been reverted because it introduced another bug, reopening

**Comment by hanoii** [comment]
I am noticing also that on long lines, it's not truncating the lines to $COLUMNS as the normal command would.
