### ISSUE TITLE
0.14: navigation by page via arrow keys no longer works

### ISSUE THREAD

**Issue by iconoclasthero** [charmbracelet/gum#609]
with the advent of 0.14 my scripts stopped working properly because gum choose no longer moves a page at a time via the arrow keys.

**Comment by MikaelFangel** [comment]
Sounds related to #499. If not, please elaborate on the issue you're experiencing. (:

**Comment by iconoclasthero** [comment]
is it going to be fixed or is this where i part ways with this repo?

**Comment by maaslalani** [comment]
Hey @iconoclasthero. Yes, this will be fixed!

**Comment by caarlos0** [comment]
should we fix this in huh?

the previous implementation had a pagination... I'm thinking we could add it as an option to huh, but maybe disabled by default as it would conflict with the form keymap I guess 🤔

**Comment by mathomp4** [comment]
I think I might be encountering this as well. j/k works, but up/down doesn't...

**Comment by caarlos0** [comment]
fixed in main! thanks!
