### ISSUE TITLE
Consistent escaping of prompt

### ISSUE THREAD

**Issue by leighmcculloch** [charmbracelet/gum#61]
I've noticed that the way to escape a prompt appears to be different for the different types of prompts. This can be a little non-obvious and confusing.

For example, if I display a `write` prompt, the ESC key will escape out and continue on.

And then, if I display a `choose` prompt, the ESC key does nothing, but CTRL-C can circumvent it.

For consistent UX allowing the ESC key to escape prompts may be beneficial.

(P.S. `gum` is awesome and so handy.)

**Comment by maaslalani** [comment]
Fixed: https://github.com/charmbracelet/gum/commit/197e52a362e541e4f899f17ecb11c0d50d6c50f6

**Comment by leighmcculloch** [comment]
Thanks!
