### ISSUE TITLE
`gum choose --item.foreground` has no effect

### ISSUE THREAD

**Issue by JacobKochems** [charmbracelet/gum#614]
**Describe the bug**
`gum choose --item.foreground` has no effect. I tried several color codes but none had any effect on the colorization of the list items.

**To Reproduce**
1. Type `gum choose 1 2 3` into a terminal emulator with color support
2. Type `gum choose 1 2 3 --item.foreground 12` into a terminal emulator with color support
3. Notice that there is no difference in the colorization of the non-selected list items.

**Expected behavior**
The non-selected list items should be displayed in the specified color (Blue (System)).

**Screenshots**
Kitty (theme: Gruvbox Material Dark Soft)
![selected foreground](https://github.com/charmbracelet/gum/assets/41692189/4336c528-b9b4-4436-a429-00d1b93ed19f)
![item foreground](https://github.com/charmbracelet/gum/assets/41692189/bfc9131a-195e-4876-87b9-4758705534df)
![item foreground_subshell](https://github.com/charmbracelet/gum/assets/41692189/977ccd7a-36a7-4cfa-bf88-0d02c8c6f024)

Kitty (theme: Github Light High Contrast)
![light_item foreground](https://github.com/charmbracelet/gum/assets/41692189/583f5356-7ecc-4a0b-9962-dec831d1c003)
![light_item foreground_subshell](https://github.com/charmbracelet/gum/assets/41692189/4a8dc3f0-6580-4fa8-9bbc-45f53056e247)

**Desktop (please complete the following information):**
 - OS: Debian 12 (bookworm); also tested with: Arch Linux (2024-07-01) in VM
 - Terminal: Kitty (version: 0.35.2); also tested with:  gnome-terminal
 - Version: 0.14.1

**Additional context**
As one can see from the last screenshot `gum choose` behaves differently with respect to styling if called from within a subshell, which is especially unfortunate if one really needs to use a light theme (because of lighting conditions), in which case the list items are very hard to read.

**Comment by meowgorithm** [comment]
Just a note that this is fixed in [`huh`](https://github.com/charmbracelet/huh) and will hit `gum` after we do a point release and bump the dependency.

**Comment by JacobKochems** [comment]
Thanks for the information. I guess we leave this issue open until the version bump and then close it?

**Comment by meowgorithm** [comment]
Yeah. Well do it soon to fix a few issues.

**Comment by meowgorithm** [comment]
Released! Find this in [Gum v0.14.2](https://github.com/charmbracelet/gum/releases/tag/v0.14.2).
