### ISSUE TITLE
`gum file` does not respect `esc` key binding

### ISSUE THREAD

**Issue by marcransome** [charmbracelet/gum#626]
**Describe the bug**

The key bindings shown in the help message of the `gum file` command suggest that the `esc` key will close the command:

```shell
$ gum file
> drwxr-xr-x choose
  drwxr-xr-x completion
  drwxr-xr-x confirm
  drwxr-xr-x cursor
  drwxr-xr-x examples
  drwxr-xr-x file
  drwxr-xr-x filter
  drwxr-xr-x format
  drwxr-xr-x input
  drwxr-xr-x internal

↑ up • ↓ down • esc close • enter submit
```

However, pressing `esc` results in the file listing being redrawn with a single entry for the current working directory:

```yaml
$ gum file
/src










enter submit
```

**To Reproduce**

1. Run `gum file <path>`
2. Press `esc`

**Expected behavior**

Pressing the `esc` key should result in the `gum file` command returning the user to the shell.

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Version: 0.14.1

**Comment by caarlos0** [comment]
https://github.com/charmbracelet/huh/pull/323 this should fix it
