### ISSUE TITLE
the previous verison: `gum confirm` supports key y for yes, n for no. but now it doesn't work

### ISSUE THREAD

**Issue by RuneScaping** [charmbracelet/gum#628]
can you please fix this? it's very awkward now

**Comment by meowgorithm** [comment]
Hi! Dup of #568. This is fixed on `main` and will be available in the next release.

We'll cut a release soon, but if you have Go and would like the new version immediately you can `go getgithub.com/charmbracelet/gum/issues/628`.

**Comment by meowgorithm** [comment]
Just a note that this is now available in [Gum v0.14.2](https://github.com/charmbracelet/gum/releases/tag/v0.14.2).
