### ISSUE TITLE
gum input showing enter submit

### ISSUE THREAD

**Issue by tweetysat** [charmbracelet/gum#642]
I'm running Debian 12 bookworm(on the Windows Subsystem for Linux) and gum version v0.14.3 (5d96f84).

I don't know what could be happened but since a few weeks the input do not works as before. 
It adds a blank line and a second with : enter submit.  After entering a value those 2 lines disappears.

```
$gum input
> Type something...

enter submit 
```

```
> hello 

enter submit
```

`hello`

**Comment by piero-vic** [comment]
New defaults I think. You can use the flag `--no-show-help` or set the enviroment variable `GUM_INPUT_SHOW_HELP=flase`.

```bash
gum input --no-show-help
```

**Comment by tweetysat** [comment]
Great.  It is working now.  Thanks. 
But be careful there is a typo : GUM_INPUT_SHOW_HELP=**false**
