### ISSUE TITLE
Allow reordering of list with choose

### ISSUE THREAD

**Issue by emsaks** [charmbracelet/gum#644]
I use `choose` to allow multiselect on a list, but the order is also important

It would be nice to allow a keybinding to move items up/down on the list, and respect the new order when outputting the result

**Comment by caarlos0** [comment]
hey, this is probably out of scope, if you need to reorder, you can probably pipe the options into a text editor or something like that.

closing, cheers!

**Comment by meowgorithm** [comment]
@emsaks For your particular use case, is it choosing _and_ reordering? Or just reordering?

**Comment by emsaks** [comment]
Both, but it could be done as two steps - choose then order. But either
way, ordering with a text editor (as suggested) is not very convenient,
especially if it needs to be repeated multiple times throughout a job.
