### ISSUE TITLE
`gum spin` can only executes a single command

### ISSUE THREAD

**Issue by btbf** [charmbracelet/gum#648]
What we most want to achieve with spin is a feature that informs the user of the wait time while multiple commands are running in the background.

I would like to have a feature implemented that allows spinning, so that it will continue spinning until the commands within the function are completed.

Related Issues
#419
#336

**Comment by piero-vic** [comment]
Here's a possible solution https://github.com/charmbracelet/gum/issues/419#issuecomment-2351679739

**Comment by caarlos0** [comment]
@piero-vic's comment is the way to go, I believe.

you may also do something like `gum spin -- sh -c "several && commands && here"`
