### ISSUE TITLE
VS Code extension

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [charmbracelet/gum#649]
Hi! I've [created](https://github.com/EmilyGraceSeville7cf/fish-tui-gum/releases/tag/v1.0.0) a VS Code extension for `gum` for Fish shell. Any ideas or suggestions are welcome. 😄 

![image](https://github.com/user-attachments/assets/ac8e9d0f-2fc0-4b4c-b049-adf551518476)

**Comment by caarlos0** [comment]
hey! Thanks for sharing, keep up the good work!
