### ISSUE TITLE
gum write height being capped at 7

### ISSUE THREAD

**Issue by octoshrimpy** [charmbracelet/gum#657]
**Describe the bug**
gum write height is being capped at 7

**To Reproduce**
```
gum write --height 13 --show-line-numbers
```

**Expected behavior**
`--height` respects values passed in, or 0 for full terminal height like others

**Screenshots**

```
gum write --height 13 --show-line-numbers
```
![image](https://github.com/user-attachments/assets/c94ce23f-035c-4baf-adde-6fa1cd5349d7)

and for sanity check:
```
gum write --height 3 --show-line-numbers
```
![image](https://github.com/user-attachments/assets/1e4d4c77-f1b9-483c-81db-61e311c3f6bf)

**Desktop (please complete the following information):**
 - OS: arch linux
 - Gum Version `0.14.3`
![image](https://github.com/user-attachments/assets/fb0e19c8-f23e-4983-b3ec-374cc55cf6b4)

**Comment by murkl** [comment]
I can confirm this. With the new version v0.14.4 the help text is now shown after the given height, but the content is still limited after 6 lines.

![grafik](https://github.com/user-attachments/assets/57176fd0-7157-4f8e-8261-99d293ab49ac)
