### ISSUE TITLE
gum --choose text colours not having effect

### ISSUE THREAD

**Issue by gennaro-tedesco** [charmbracelet/gum#66]
Thank you for the great work you do with these terminal libraries, they are awesome!

### Problem

```
gum --chose --selected.foreground
```
and similar options on colouring of the text items seem to have any effect: see example below (copied and pasted from the docs, where I first use the default command and then I try to enhance it with colour options).

### Demo

https://user-images.githubusercontent.com/15387611/182197404-669fe2f6-b51e-420d-bc69-e251271f8cd8.mov

### Config

I am using

- iTerm2 (Version 3.4.16)
- zsh 
- macOS 12.4.0 Monterey

is it a problem of my terminal (not to properly obey the colour options) or am I trivially passing the wrong values?

**Comment by maaslalani** [comment]
I think the issue is that the `--selected` styling value is used with the `--no-limit` flag.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/42545625/182207468-766dfd3b-2c58-422a-8201-a0bd63b2148d.png">

**Comment by maaslalani** [comment]
I think you're looking for the `--cursor.foreground` styling as that is what is used for the item that the cursor is currently on.

**Comment by gennaro-tedesco** [comment]
You are right, using `--no-limit` ensures the proper colouring and so does `--cursor.foreground` when it comes to the actual cursor arrow colours.

Thank you for the prompt response!
