### ISSUE TITLE
Use `gum file` to find specific file types/using wildcards to narrow down

### ISSUE THREAD

**Issue by fearlessgeekmedia** [charmbracelet/gum#669]
**Is your feature request related to a problem? Please describe.**
I've created a bash script for Void Linux using gum called xbpsman. One of the things I want to do with it is install packages locally. `gum file` would theoretically help with this, but I can't search specifically for the .zst file type

**Describe the solution you'd like**
gum file *.zst
gum file ../*.zst for starting in a different directory
or maybe something like
gum file --type *.zst

or some way to use wildcards to narrow down the files.

**Describe alternatives you've considered**
I can use ls `*.txt | gum filter`, but then it won't list the directories. And I want it to be able to do that, too.

**Comment by piero-vic** [comment]
I think `gum filter **/*.txt` should do the trick. Issue #622 also mentions something similar.

**Comment by fearlessgeekmedia** [comment]
That works! Thanks!
