### ISSUE TITLE
Gum choose doesn't exit on `esc` anymore

### ISSUE THREAD

**Issue by aymanbagabas** [charmbracelet/gum#675]
**Describe the bug**
[Gum v0.13](https://github.com/charmbracelet/gum/blob/v0.13.0/choose/choose.go#L135) used to quit on <kbd>esc</kbd>

**To Reproduce**
1. Run `gum choose ...`
2. Press <kbd>esc</kbd>
3. Gum choose should exit

**Expected behavior**
Gum choose should exit on <kbd>esc</kbd>

**Comment by meowgorithm** [comment]
I think that makes sense (_probably_ for all TUI subcommands), however in this case I think the workflow should be:

* If the user is actively typing in a filter <kbd>esc</kbd> sets the filter (as it works currently)
* If a filter is set <kbd>esc</kbd> clears the filter (as it works currently)
* If no filter is set <kbd>esc</kbd> exits the TUI

**Comment by caarlos0** [comment]
fixed on main
