### ISSUE TITLE
gum filter --sort gives unexpected results

### ISSUE THREAD

**Issue by hxlnt** [charmbracelet/gum#676]
**Describe the bug**
`gum filter --sort` returns an unexpected sort (reverse of as-authored order instead of alphabetical).

**To Reproduce**
1. Run sample filter script after adding `--sort` flag and with the following entries: "Cow," "Cat," "Dog," "Aog," and "Cyg"
2. Filter by typing "c," "a," and/or "g"

**Expected behavior**
1. Results are sorted alphabetically when `--sort` flag is used.

**Screenshots**
![Screenshot from 2024-09-13 23-52-22](https://github.com/user-attachments/assets/c87e561b-42a0-4b15-b998-2be856d9d1f4)

**Desktop (please complete the following information):**
 - OS: Linux Mint

Sorry if I am misunderstanding the purpose of this flag; I assumed `--sort` would sort alphabetically rather than reversing the as-authored order.

**Comment by piero-vic** [comment]
It seems like the `--sort` flag is set to [true by default](https://github.com/charmbracelet/gum/blob/c00c2e416acd374423c5661341cff2e50ce23214/filter/options.go#L37C1-L37C113). So there's no difference between running `gum filter` or `gum filter --sort` in this case.

`gum filter` also depends on [fuzzy](https://github.com/sahilm/fuzzy) for the fuzzy finding. And for what I've read it sorts the results by matching quality not alphabetically.

If you would like to disable sorting you can use the `--no-sort` flag and it will preserve the as-authored order.

 You can also sort the input alphabetically with the `sort` command before piping the output to `gum filter`.

```bash
cat input.txt | sort | gum filter --no-sort 
```

**Comment by hxlnt** [comment]
@piero-vic I did think of that, but setting `fuzzy` to false and `sort` to true doesn't sort the results, either. 

Also, when fuzzy matches are of equal quality and `--sort` is true/unset, the results return in *reverse-authored order.* That seems quite strange.

So, I'm just not sure what `--sort` is supposed to do and if it's working as intended or not. At minimum, some documentation might help folks like myself understand the intended behavior. 

Here is a table to summarize some testing I did. 

| Sort flag | Fuzzy flag | Filter behavior | Expected or unexpected? |
|--------------|---------------|-----------------------|---------------------------------------|
| `--sort` | `--fuzzy` | Matches are in fuzzy order, but when fuzzy match quality is equal**, results are in *reverse-authored* order | Unexpected |
| `--sort` | `--no-fuzzy` | Matches are in *as-authored* order | Unexpected |
| `--no-sort` | `--fuzzy` | Matches are in *as-authored* order | Expected |
| `--no-sort` | `--no-fuzzy` | Matches are in *as-authored* order | Expected |

** *e.g.,* First-letter match on words of equal length

My word list for testing:
```
Cow
Cat
Cry
Dad
Doo
Dog
Catty
Crybaby
Cattail
Crate
```

**Comment by caarlos0** [comment]
@hxlnt I think your remarks make sense, but as far as I looked, there's no way to do it with the library we use

it does sort by score, not alphabetically... and the flag help isn't specific, so I can see why you assume alphabetically... 

For now I'm clarifying the help, not sure if we should actually fork fuzzy and implement what we need there or not, will chat with the team about it though :)

**Comment by meowgorithm** [comment]
Just chiming in here for some more context. To start, we're going to clarify what `--help` looks like:

```
--[no-]fuzzy         Enable fuzzy matching; otherwise match from start of word ($GUM_FILTER_FUZZY)
--[no-]fuzzy-sort    Sort fuzzy results by their scores ($GUM_FILTER_FUZZY_SORT)
```

`--sort` will continue to exist but be deprecated in favor of the more aptly named `--fuzzy-sort`.

To sort alphabetically the `sort` command  can be used with a pipe as @piero-vic suggest, however I'd love to know if sorting filtered results would also be useful.

**Comment by caarlos0** [comment]
Agreed! I think this can be closed then, let me know otherwise.
