### ISSUE TITLE
`gum log` is always outputted to stderr

### ISSUE THREAD

**Issue by MokkaCicc** [charmbracelet/gum#677]
**Describe the bug**
The output of `gum log` is always outputted to stderr, this can be frustrating to work with inside bash scripts as error handling is polluted with logs.
Also, other bash feature don't work as expected: `gum log` cannot be manipulated with `|`, `>`, `>>`, `1>`, ... 

To redirect to a file, the `-o` flag is here (or we can use `2>`/`2>>`) but this is not flexible enough for some scripting usages.

**To Reproduce**
1. Run the command `gum log "This is a test" > out` (Log level don't change anything)
2. Nothing inside the `out` file and the log was outputted in the TTY

**Expected behavior**
The output of `gum log` should be manipulable with `|`, `>`, `>>`, `1>`, ...

**Desktop (please complete the following information):**
 - OS: Debian 12
 - Gum: v0.14.5 (1917023)

**Comment by piero-vic** [comment]
You can redirect to `/dev/stdout` with the `-o` flag.

```bash
gum log "This is a test" -o /dev/stdout > out
```

**Comment by MokkaCicc** [comment]
> You can redirect to `/dev/stdout` with the `-o` flag.
> 
> ```shell
> gum log "This is a test" -o /dev/stdout > out
> ```

Another solution I am using in my script is using `2>&1` after each `gum log` to redirect the stderr to stdout. But either your solution and my solution is not very practical when scripting. And not very logical, I lost a couple hours bashing my head on why my script wasn't working, while it was just the log that was not outputted were I was expecting them to go.

**Comment by pythoninthegrass** [comment]
> I lost a couple hours `bash`ing my head

Amusing choice in diction haha (emphasis mine).

Agreed that it'd be nice if it automatically chose the right stdout/stderr path. Both `2>&1` and `-o /dev/stdout > out` are sufficient for my purposes 🙌

**Comment by aymanbagabas** [comment]
Yes, this is intentional, logging by default outputs to stderr. Use redirection or `--output` to change that. Closing...
