### ISSUE TITLE
Unexpected handling of ascii input text

### ISSUE THREAD

**Issue by dekimsey** [charmbracelet/gum#682]
**Describe the bug**
Text emitted by curl when printing headers appear to break line processing. Even after stripping, it's not handled well

**To Reproduce**
This example has embedded terminal handling, and at first I thought this was the problem.
1. `curl -I -i -s http://example.com | gum style --border=normal`

However [stripping](https://superuser.com/a/380778) terminal escapes don't appear to help which is confusing:
1. `curl -I -i -s http://example.com | perl -pe 's/\e\[[0-9;]*m(?:\e\[K)?//g | gum style --border=normal'

**Expected behavior**
Text is formatted correctly.

**Screenshots**
![image](https://github.com/user-attachments/assets/a31e2d1f-f6b5-4a1e-9f2f-5cce1035d506)

**Desktop (please complete the following information):**
 - OS: OSX
 - Version: 14.5
 - Terminal: Alacritty

**Additional context**
Terminal escape stripping is sufficiently complicated I kinda would love to see `gum style --strip-input` as a possible feature!

**Comment by caarlos0** [comment]
its a little bit less broken on main, still broken though

![CleanShot 2024-12-09 at 16 53 10@2x](https://github.com/user-attachments/assets/e4d87b14-b8a6-4ec3-a1c4-7ec2d408c376)

**Comment by caarlos0** [comment]
I think the reason for this is that curl is finishing lines with `\r\n`:

```
❯ curl -I -i -s  http://example.com | cat -v
HTTP/1.1 200 OK^M
Content-Encoding: gzip^M
Accept-Ranges: bytes^M
Age: 435782^M
Cache-Control: max-age=604800^M
Content-Type: text/html; charset=UTF-8^M
Date: Tue, 10 Dec 2024 19:47:56 GMT^M
Etag: "3147526947+gzip"^M
Expires: Tue, 17 Dec 2024 19:47:56 GMT^M
Last-Modified: Thu, 17 Oct 2019 07:18:26 GMT^M
Server: ECAcc (mid/875E)^M
X-Cache: HIT^M
Content-Length: 648^M
^M
```

**Comment by caarlos0** [comment]
not sure if we should automatically fix these, but in the meantime, this can be worked around with:

```sh
curl -I -i -s http://example.com | dos2unix | gum style --border=normal
```

**Comment by caarlos0** [comment]
oh, never mind, found the issue: https://github.com/charmbracelet/gum/pull/761
