### ISSUE TITLE
[BUG] Gum Choice did not work properly when using with alias

### ISSUE THREAD

**Issue by rhzs** [charmbracelet/gum#69]
Hi,

I tried to use Gum with kubernetes CLI command and AWK.

The following command is working without alias:
```
$ kubectl get pod | awk 'NR != 1{split($0,a," "); print a[1]}' | gum choose | xargs -I {} kubectl logs po/{} -f
```

However when I added this command to alias:
```
$ alias klogs="kubectl get pod | awk 'NR != 1{split($0,a," "); print a[1]}' | gum choose | xargs -I {} kubectl logs po/{} -f"
$ klogs
*
*
*
```

See screenshot
<img width="953" alt="Screen Shot 2022-08-02 at 02 36 15" src="https://user-images.githubusercontent.com/5300674/182231295-c42f4269-a184-41f6-a90a-66e03c211ef0.png">

## Env:
1. iTerm 2
2. ZSH
3. Go 1.18

Any help would be appreciated!

Thank you

**Comment by maaslalani** [comment]
I think the `$0` is causing issues for you as it is not properly escaped in the alias.

**Comment by rhzs** [comment]
@maaslalani any help please?

**Comment by rhzs** [comment]
nvm.. solved. Sorry for false positive!
