### ISSUE TITLE
Child process of "gum spin" keeps running after ctrl-c if output is redirected

### ISSUE THREAD

**Issue by ctn-malone** [charmbracelet/gum#690]
**Describe the bug**

When killing `gum spin -- xxx` with `ctrl-c`, child process keeps running if stdout is redirected

**To Reproduce**

- `ping` process will be killed when doing `ctrl-c`
```
gum spin --show-output -- ping -c 20 www.google.com
```

- `ping` process will keep running when doing `ctrl-c`
```
gum spin --show-output -- ping -c 20 www.google.com >/tmp/log
```

**Expected behavior**

Child process should be killed when doing `ctrl-c`

**Context**

We have a [QuickJS wrapper](https://github.com/ctn-malone/qjs-ext-lib/blob/master/src/gum.js#L1226) which relied on a spinner being displayed while a JS promise was executed. Since hitting  `ctrl-d` does not stop the child program (which is `tail -f` in our case) anymore, when redirected, the cancellation is not detected when using gum >= 0.14 (except for 0.14.2)

The first [gum example](https://github.com/ctn-malone/qjs-ext-lib/blob/master/examples/gum/example1.js) ported to QuickJS used to work fine and is now stuck once the spinner has disappeared, because the child process is still running

- with gum `0.12`
![Peek 2024-10-19 16-41](https://github.com/user-attachments/assets/32c011dd-7434-4daa-afd1-9e0e102a772f)
- with gum `0.14.5`
![Peek 2024-10-19 16-42](https://github.com/user-attachments/assets/68230b8f-93fd-4bb2-8560-bc8cb0049136)

**Desktop**

- OS: Ubuntu
- Terminal: Konsole
- Version: gum version 0.14.3,0.14.4,0.14.5  (0.14.2 and < 0.14 are ok)

**Comment by ctn-malone** [comment]
At first glance, it looks promising, thanks a lot !. I'll run more tests in the next few days.

 I also opened https://github.com/charmbracelet/gum/pull/733 to update the hash in `default.nix`

**Comment by ctn-malone** [comment]
All good on my side. I noticed that when the output is redirected, content is buffered until the command is finished, even when `--show-output` is used. It's perfectly fine to me but it may be a problem for other users, since in `0.14.5`, content was streamed even when redirecting output

![Peek 2024-11-27 23-26](https://github.com/user-attachments/assets/df220564-b54e-406f-ac7b-4bab2fee3d34)

**Comment by caarlos0** [comment]
thanks @ctn-malone! Fixed it as well!
