### ISSUE TITLE
`confirm` command is ignoring its `--timeout` option

### ISSUE THREAD

**Issue by dpritchett** [charmbracelet/gum#698]
**Describe the bug**

`gum confirm --timeout` never times out despite having a documented `--timeout` option.

Relevant excerpts from `gum confirm --help`

```
Usage: gum confirm [<prompt>] [flags]

Ask a user to confirm an action

Arguments:
  [<prompt>]    Prompt to display.

Flags:
     --default              Default confirmation action
     --timeout=0            Timeout until confirm returns selected value or default if provided ($GUM_CONFIRM_TIMEOUT)
```

**To Reproduce**

This never times out:
```console
❯ gum confirm --timeout=1s && echo "timed out"
```

Repro but it's a `.tape` file:
```vhs
Set TypingSpeed 0.1
Output broken-main.gif
Set Shell zsh
Sleep 500ms
Type "git checkout main && git fetch upstream main && git rev-parse HEAD"
Enter
Type "date +%H:%M:%S.%1N && go run . confirm --timeout=1s --default='Yes' && echo 'Success'"
Enter
Sleep 4s
Ctrl+C
Type "date +%H:%M:%S.%1N"
Enter
Sleep 4s
Ctrl+D
```

**Expected behavior**
Confirm times out after the specified duration as described in the docs.

```console
❯ ./gum confirm --timeout=1s && echo "timed out"
┃  Are you sure?
┃
┃     Yes        No

timed out
```

**Screenshots**

### Before

Gum timeout wrapped in an external `timeout` command. See that it does not stop at 1 second but stops at 5 per the wrapping command:

<img width="505" alt="image" src="https://github.com/user-attachments/assets/b5d06b42-6b44-4011-bfac-e3b5bb4f11b9">

### After (using fix from #697)

Same call as before but gum times out at 1 second as expected:

<img width="506" alt="image" src="https://github.com/user-attachments/assets/fcf4f991-93b1-488c-8c65-fdfafd84ee14">

**Desktop (please complete the following information):**
 - OS: MacOS 
 - Browser: uhh.. `alacritty` is my terminal emulator, `fish` my shell
 - Version: MacOS 15.0.1 (24A348)

**Additional context**

I have a unit tested fix up in #697.

**Comment by agilesteel** [comment]
The timeout works now, but a countdown used to be displayed and now it's not. Is this intended?

**Comment by pmarreck** [comment]
A timeout of 0 is just ignored (no matter which gum command I try). It also doesn't return the default option when it times out. This makes manipulation of these options useless for unit tests, where they would otherwise be extremely useful.
