### ISSUE TITLE
Up and down cursor navigation doesnt work with many choices on choose

### ISSUE THREAD

**Issue by mamazinho** [charmbracelet/gum#703]
**Describe the bug**
When we have multiple items on screen in choose command, it's not possible change the "page" (scroll up and down) to see more items with cursor, the cursor dissappears and the options are resized according terminal size. The cursos has the behavior of a ghost cursor, navegating through options not showed on screen.

**To Reproduce**
1. Create a choose with 200 items
2. Executing
3. Navegating with cursor

**Expected behavior**
The list must scroll up and down according cursor.
Follow cursor

**Screenshots**
![image](https://github.com/user-attachments/assets/50e2d509-f771-49a2-944d-e29ec542eb7e)

**Desktop (please complete the following information):**
 - GUM version: v0.14.5
 - SO Info:
Distributor ID: Ubuntu
Description:    Ubuntu 24.04.1 LTS
Release:        24.04
Codename:       noble

**Additional context**
In the video is possible to see how the list adjusts according screen/terminal size instead follow the cursor
https://youtu.be/XXqJXxv98VA

**Comment by caarlos0** [comment]
fixed on main.

thanks!
