### ISSUE TITLE
Colors not appearing on ZSH startup

### ISSUE THREAD

**Issue by LGgameLAB** [charmbracelet/gum#709]
**Describe the bug**
When I link a shell script that runs `gum style \ ...` in my .zshrc, the colors don't work when my terminal opens. 
The colors do work if I run the command at any other time and if I use escape codes with `echo -e` on startup 

**To Reproduce**
1. Make a shell script that uses `gum style` and any sort of color
2. put `~/path-to-script/script.sh` in your zsh config
3. Your terminal
4. No colors

**Expected behavior**
Expected colors
![2024-11-08-13:30:24-screenshot](https://github.com/user-attachments/assets/bed91e64-b51c-49b0-a0b9-7d040d62aba6)

**Comment by caarlos0** [comment]
i think color profile detection might not work during the shell startup...

cc/ @aymanbagabas

**Comment by LGgameLAB** [comment]
![Screenshot_2024-11-21_09-47-17](https://github.com/user-attachments/assets/58e3df5b-7816-47bc-85b1-023e2cd31d8c)

Maybe it is something to do with powerlevel10k? The terminal I'm using is xfce4-terminal but the same thing happens in kitty. 

I'll back up my zshrc and see if it is something I have installed that is making it not work.
