### ISSUE TITLE
Inconsistent behavior of `choose --height 0` when using an empty `--header`

### ISSUE THREAD

**Issue by yolocat-dev** [charmbracelet/gum#714]
**Describe the bug**
When running `gum choose --header "" "a" "b" "c"` the `--count 0` (default) flag draws one option too little.

**To Reproduce**
1. Execute `gum choose "a" "b" "c"` and you'll see the three options displayed correctly.
2. Execute `gum choose --header "" "a" "b" "c"` and you'll see that you have to navigate down to see option `"c"`.

**Expected behavior**
Setting the `--header` flag to an empty string should still display all options when `--height` is set to `0` (default).

**Screenshots**
<img width="312" alt="image" src="https://github.com/user-attachments/assets/43a03d97-7601-4d5f-a0d4-cc66debba576">

**Desktop (please complete the following information):**
 - OS: `macOS 14.7.1 23H222 arm64`
 - Version: `gum version 0.14.5`

**Comment by caarlos0** [comment]
fixed on main! thanks!
