### ISSUE TITLE
Filter panics when moving the cursor in empty selection

### ISSUE THREAD

**Issue by etiennebarrie** [charmbracelet/gum#715]
**Describe the bug**
When `gum filter` is used, and the entered value filters all options, trying to move the cursor with the up or down arrow keys or ctrl-j or ctrl-k panics.

**To Reproduce**

```console
gum filter a --value=d
# click up or down or type ctrl-j or ctrl-k
```

**Expected behavior**
Nothing happens.

**Screenshots**
https://asciinema.org/a/lAjxemyCevVPRAdHGuRxifFgM

**Comment by caarlos0** [comment]
thanks! fixed on main!
