### ISSUE TITLE
[feature] Preselected entries in gum choose

### ISSUE THREAD

**Issue by aa-ko** [charmbracelet/gum#72]
Hey everyone!

I just encountered a case where I'd want `gum choose` to display a list of item that **are already selected**. The user is thus prompted to **deselect** some of these items while the default behaviour (just pressing _Enter_) would include all listed items as selected.

This could of course be implemented in the surrounding shell script and by labeling the items something like _Disable XY_ or _Omit XY_, but this results in bad UX, because you're now dealing with a list of negated items.

I have two proposals right now on how to implement this in `gum choose`:

### Escape characters
Introduce some escape character in the item name that is then parsed and leads to this item being preselected.
This allows for fine-grained control, but is error prone due to additional parsing.

### CLI option
Simply add an option like `gum choose --selected` that simply displays all the given items as preselected.

For example, given the command `gum choose --no-limit "foo" "bar" "baz"`, we expect this output:
```
> [•] foo
  [ ] bar
  [ ] baz
```
With an additional CLI option, we could turn this into the following output by calling `gum choose --preselected --no-limit "foo" "bar" "baz"`:
```
> [✕] foo
  [✕] bar
  [✕] baz
```

I'd love to hear some feedback from the maintainers on this. Thanks in advance for your time!

**Comment by maaslalani** [comment]
Hey! This is a really good idea. I think what I would change is making the `--preselected` flag able to take arguments so that you can preselect _some_ entries without selecting others.

```bash
gum choose foo bar baz --default-selected foo bar
```
> [✕] foo
  [✕] bar
  [ ] baz
```

```

**Comment by aa-ko** [comment]
Good call! I have very little Go knowledge, but I'll try to come up with a prototype.
