### ISSUE TITLE
`--placeholder` will limit the number of lines entered

### ISSUE THREAD

**Issue by liveforning** [charmbracelet/gum#725]
Hello! In the image below, I've tried to set the window and word limit to 500*20 and 400 `--width 500 --height 20 --char-limit 400`

But it always shows 6 lines to my `--placeholder` prompt. Is that a limit?

![image](https://github.com/user-attachments/assets/9f4a3dd2-7504-48ab-b4ae-5e3210542508)

**Comment by caarlos0** [comment]
should be fixed on main.

thanks for reporting!
