### ISSUE TITLE
Can't install by brew

### ISSUE THREAD

**Issue by liestherub** [charmbracelet/gum#74]
**Describe the bug**
I can't install by brew

**To Reproduce**
`brew install gum`

**Expected behavior**
Got a error:
```
Warning: No available formula or cask with the name "gum". Did you mean gom, gdm, glm or gpm?
==> Searching for similarly named formulae...
These similarly named formulae were found:
gumbo-parser        gom                 gdm                 glm                 gpm
To install one of them, run (for example):
  brew install gumbo-parser
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Screenshots**
<img width="754" alt="图片" src="https://user-images.githubusercontent.com/4531076/182274459-c5e29b5a-b706-4ea2-8079-14c9960c6a3b.png">

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] macOS 12.2.1 (21D62)
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] -

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] -
 - OS: [e.g. iOS8.1] -
 - Browser [e.g. stock browser, safari] -
 - Version [e.g. 22] -

**Additional context**
-

**Comment by maaslalani** [comment]
Can you try `brew update` and check if that works and then `brew install gum`

**Comment by liestherub** [comment]
> Can you try `brew update` and check if that works and then `brew install gum`

Now it can be installed thanks!
