### ISSUE TITLE
gum table: add an option to select row by an index instead have to select

### ISSUE THREAD

**Issue by HyperChaser** [charmbracelet/gum#740]
Can we have a feature to select by row index, I saw a similar feature to select collum by collum index, can we have something similar for row selection

**Comment by caarlos0** [comment]
sorry, I didn't understand what you mean... can you clarify?

**Comment by HyperChaser** [comment]
i mean gum table allow us to choose a row from an csv table by select in interact TUI, can we have an option like "gum table data.csv --row 5" then it will print line 5 of the table

**Comment by rahji** [comment]
I think gum is focused on interactive choices. You should look at csvkit for what you are describing... https://csvkit.readthedocs.io/en/latest/

**Comment by HyperChaser** [comment]
Got it
