### ISSUE TITLE
refactor: remove huh as a dependency

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/gum#741]
`gum choose`
- add header
- add filter
combine `gum choose` and `gum filter`
- full screen option
- select/unselect all

bash to check what bugs have been fixed in prev versions of huh and gum to test against this new branch

**Comment by bashbunni** [comment]
bug fixes in previous gum versions - for reference when doing validation on the changes (I can help with this)

## Impacted commands

Use Huh for Gum Choose by @maaslalani in https://github.com/charmbracelet/gum/pull/521
Use Huh for Gum Confirm by @maaslalani in https://github.com/charmbracelet/gum/pull/522
Use Huh for Gum File by @maaslalani in https://github.com/charmbracelet/gum/pull/523
Use Huh for Gum Input by @maaslalani in https://github.com/charmbracelet/gum/pull/524
Use Huh for Gum Write by @maaslalani in https://github.com/charmbracelet/gum/pull/525

## Features

Show help with Huh? by @maaslalani in https://github.com/charmbracelet/gum/pull/587

## Fixes (gum)

### v0.14.1

Handle huh? user aborted error by @MikaelFangel in https://github.com/charmbracelet/gum/pull/578
Cursor styling by @MikaelFangel in https://github.com/charmbracelet/gum/pull/592
Re-introduce ESC for gum write by @MikaelFangel in https://github.com/charmbracelet/gum/pull/579
    
### v0.14.2

drop left padding in choose in https://github.com/charmbracelet/gum/pull/597
fix race conditon where spinner could mis-render in https://github.com/charmbracelet/gum/pull/621
fix a bug where choose could crash when spacebar is pressed twice https://github.com/charmbracelet/gum/pull/587
fix a bug where the foreground color could not be set in choose https://github.com/charmbracelet/gum/issues/614
fix a bug where foreground could not be set in write https://github.com/charmbracelet/gum/issues/583
fix a bug where keypresses could crash choose https://github.com/charmbracelet/gum/issues/580
restore y/n keybindings to confirm https://github.com/charmbracelet/gum/issues/568
restore centering to buttons in confirm https://github.com/charmbracelet/gum/issues/566
    
### v0.14.4

https://github.com/charmbracelet/gum/commit/e095a9142b740b08b2252df7c96e2c9571518751: fix(input): wrong height when using borders in the header (@caarlos0)
https://github.com/charmbracelet/gum/commit/d722a2f1b811581125911a7e1a61b4dc8e9a1ec7: fix: height 0 by default (https://github.com/charmbracelet/gum/pull/640) (@caarlos0)
https://github.com/charmbracelet/gum/commit/046a4d361eb12ffc0fd1b7ea5fec697ba1fe118e: fix: use 0 as default width (https://github.com/charmbracelet/gum/pull/634) (@caarlos0)
https://github.com/charmbracelet/gum/commit/9db5c7fbbabad605e763925eeb9e24ec836616db: fix: select all keybindings (https://github.com/charmbracelet/gum/pull/639) (@caarlos0)
https://github.com/charmbracelet/gum/commit/96448e08e575c5ccd3bdc7b30fc09c67775e2847: fix: show background style help (https://github.com/charmbracelet/gum/pull/641) (@caarlos0)
    
## Fixes (huh)

### v0.5.0

Resolve conflict between select and filter by @MikaelFangel in https://github.com/charmbracelet/huh/pull/252

### v0.5.2

improve distinction in field select by @csandeep in https://github.com/charmbracelet/huh/pull/304

### v0.5.3

fix: group varying heights by @bashbunni in https://github.com/charmbracelet/huh/pull/350
fix: group size when height is 0 by @caarlos0 in https://github.com/charmbracelet/huh/pull/363
fix(filepicker): not closing on close by @caarlos0 in https://github.com/charmbracelet/huh/pull/323
fix(select): wrapping selects by @caarlos0 in https://github.com/charmbracelet/huh/pull/324
fix(select): select all/none by @caarlos0 in https://github.com/charmbracelet/huh/pull/325
fix(multiselect): contextual 'select all' help text by @meowgorithm in https://github.com/charmbracelet/huh/pull/342
fix(spinner): light color in title by @hyorigo in https://github.com/charmbracelet/huh/pull/346
fix (multiselect): set filterable not working by @caarlos0 in https://github.com/charmbracelet/huh/pull/335
    
Also
    
refactor: use a selector type to select items by @aymanbagabas in https://github.com/charmbracelet/huh/pull/328
refactor: make item selector into a slice container by @aymanbagabas in https://github.com/charmbracelet/huh/pull/334

**Comment by MikaelFangel** [comment]
@bashbunni - Just to understand this issue correctly. Does it concern only removing huh as a dependency for `gum choose` or from `gum` in general? Also is the goal to recreate the behavior from before huh was introduced to `gum`.

**Comment by meowgorithm** [comment]
Hey, @MikaelFangel. We’re planning on removing Huh in Gum across the board, so `choose`, `confirm`, `write`, `input`, and `file`.

After the switch we noticed that we lost some really good functionality and behavior, and found that working on Gum was harder because Huh needed to support use cases specific to Gum in addition to its main purpose. The original Bubble Tea applications in Gum are pretty simple and are much easier to maintain.

Anyway, while we’re reverting to pre-Huh code, we’re also on adding some of the features added post-Huh. We’d love to hear is if there’s any functionality that Huh added that you like to see preserved.

**Comment by MikaelFangel** [comment]
Thank you for explaining it to me. The plan seems solid, and I don't have any specifics about the features I'd like to see preserved. Please let me know if there's anything I can do to help 😄

**Comment by meowgorithm** [comment]
@MikaelFangel Awesome, that's great to get your vote of confidence. With regard to help, will do. Thanks for all your contributions so far!
