### ISSUE TITLE
Shell Functions

### ISSUE THREAD

**Issue by WoMspace** [charmbracelet/gum#75]
I'm trying to use bash/shell functions (i.e. `function myFunc { doSomething }` with `gum spin` but it's always failing.

Support shell functions as commands in `gum spin`?

I can't think of any other way to do this besides moving the functions to really long one-liners behind the `spin` command.

_excuse my awful gif quality; ffmpeg is a PITA for gifs_
![gum_spin](https://user-images.githubusercontent.com/22845656/182274809-032de0fd-5636-40c4-814a-ca404a20394c.gif)

**Comment by maaslalani** [comment]
Because `gum spin` does not execute in your current shell session (that is where the function exists) it will not have that function defined.

**Comment by WoMspace** [comment]
ah yes ok that makes sense. I'm a bit of a shell noob, are there any workarounds *besides* a one-liner?

**Comment by maaslalani** [comment]
You can move the shell script to a script file and then execute it with `gum spin`:

<img width="453" alt="image" src="https://user-images.githubusercontent.com/42545625/182275435-f7b16159-efcf-4497-aace-8adbfc6f6a7d.png">

You'll need to:
```
touch <file>.sh
# edit the file with the contents / code you want
chmod +x <file>.sh # make the file executable
gum spin -- ./<file>.sh
```

**Comment by WoMspace** [comment]
oh excellent, many thanks!
