### ISSUE TITLE
Hex/Truecolor Coloring

### ISSUE THREAD

**Issue by BlueFalconHD** [charmbracelet/gum#79]
**Describe the solution you'd like**
A truecolor implementation with hex support.

**Additional context**
maybe add autodetection of hex versus standard color names, and add rgb/cmyk support if needed.

**Comment by maaslalani** [comment]
@BlueFalconHD could you expand on this, what is the behaviour you are looking for and do you have an example?

**Comment by BlueFalconHD** [comment]
Oh. I have missed the #hex feature.

**Comment by maaslalani** [comment]
Sweet! Sounds good 🙂 Thanks for checking!
