### ISSUE TITLE
Introduce a way to have descriptive text before or after `gum write` UI

### ISSUE THREAD

**Issue by markjaquith** [charmbracelet/gum#80]
I would like a way to provide header and/or footer text around the `gum write` UI. The other input commands let you provide a prompt of some sort. But with `gum write`, the prompt is repeated for each line, and isn't useful as informative text.

My specific use case is that it isn't obvious that you have to send an EOF (ctrl-D) to indicate when you're done editing the text. So I wanted to have some text either before or after the editing area (maybe using `--faint` and `--italic`) to tell people to ctrl-d when done. Other uses could be having some descriptive text that tells them what they're editing.

I could just `print` it out before calling `gum write` but then it'll hang around in the terminal history which is ugly. I like how the other prompts like for `gum input` and `gum choose` go away.

My current solution is to abuse `gum choose` with an empty choice as an "interstitial" they have to pass through before being shown `gum write`:

```
gum choose --cursor.italic --cursor.faint --cursor="
Press return to edit your script, and ctrl-d to save" ""
```

Not ideal, as it introduces another step.

Ideally I'd be able to do `gum write --intro "Press ctrl-d to save" --intro.faint --intro.italic`

(Really don't care what it's called... `intro` and `outro` could work. `header` and `footer` could work.

**Comment by maaslalani** [comment]
Hey! This is a good idea and we'll look at adding this to make it easier to do this sort of thing but in the meantime you should try this code which will achieve what you want:

```
gum style --foreground 240 "Press ctrl+d to submit" && gum write > test && printf "\33[A[2K\r"
```

https://user-images.githubusercontent.com/42545625/182413973-ec3e575e-a193-4bcf-968a-e0448bc47b4f.mov


The main change is the `printf "\33[A[2K\r"` which moves your terminal cursor up one and then clears the line which gives you the effect you want I believe.

**Comment by markjaquith** [comment]
Great workaround! Thanks for that. Man, I was trying to figure out how to do that via `man printf` on an airplane and was not having a good time.
