### ISSUE TITLE
Print the output of the command after the spinner is finished

### ISSUE THREAD

**Issue by HoangTuan110** [charmbracelet/gum#81]
**Is your feature request related to a problem? Please describe.**
I am currently working on a simple wrapper of `curl`, and I wanted to return the result of the `curl`ing after a spinner, like this:

```sh
gum spin --spinner moon --title "Buying Bubble Gum..." -- curl -fsSL curl.se
```

But gum doesn't return the output of the `curl` after the spinner exits.

**Describe the solution you'd like**
I want the spinner to print the output of the command after the command (and the spinner) exits.

**Describe alternatives you've considered**
I am not aware of any alternatives at the moment. I have also considered using a `sleep` command instead, then actually do the `curl`:

```sh
gum spin --spinner moon --title "Buying Bubble Gum..." -- sleep 2
curl -fsSL curl.se
```

But I think this isn't genuine.

**Additional context**
No additional context.

**Comment by maaslalani** [comment]
On the latest version of `gum` there is a `--show-output` flag for `gum spin`

**Comment by HoangTuan110** [comment]
Oh, thank you! Not aware of that. Will close this issue.
