### ISSUE TITLE
Add keybinding to choose all options in a `gum choose`

### ISSUE THREAD

**Issue by dlvhdr** [charmbracelet/gum#85]
**Is your feature request related to a problem? Please describe.**
I have a script to update all packages on my mac.

```sh
function update_choose() {
  cmds=("brew update && brew upgrade" "brew upgrade --cask --greedy" "npm update -g --fetch-timeout 3000" "yarn global upgrade" "gh extensions upgrade --all" "gup update" "rustup update")
  chose=$(gum choose --no-limit $cmds)
  for cmd in $chose
  do
    eval "$cmd"
  done
}
```

**Describe the solution you'd like**
- I want to be able to easily select everything.
- If I missed a keybinding, then I want the ability to see what keys do what on each gum command (either in `--help` or in the rendering itself.

**Describe alternatives you've considered**
I tried using `gum --help` to see if I'm missing anything.

**Additional context**
Awesome tool, love this!

**Comment by maaslalani** [comment]
Oh, this is an interesting idea! How about <kbd>a</kbd>/<kbd>A</kbd> selects all options?

**Comment by dlvhdr** [comment]
yeah that was my intuition as well!

**Comment by maaslalani** [comment]
Cool, I say `a` selects everything and then `A` unselects everything? or maybe `u` 🤔

**Comment by maaslalani** [comment]
I think the `a`/`A` select/unselect combo is good, I can make a PR for it (unless you want to?)

**Comment by dlvhdr** [comment]
I can do it! :)
