### ISSUE TITLE
Ability to set maximum height for `gum filter`

### ISSUE THREAD

**Issue by dlvhdr** [charmbracelet/gum#86]
**Is your feature request related to a problem? Please describe.**
I have a script to cd into a repo, but when starting to filter, the list is very long and it will be more aesthetic to limit the search results' height.

**Describe the solution you'd like**
A `--height` flag or `--max-height` or something like that.

**Describe alternatives you've considered**
Non really, using fzf you can do this.

**Additional context**
Navigating with j/k will go off screen if there are too many results

**Comment by maaslalani** [comment]
👍 Totally agree!
