### ISSUE TITLE
Add --optional flag to `choose` command

### ISSUE THREAD

**Issue by WisdomWolf** [charmbracelet/gum#87]
**Is your feature request related to a problem? Please describe.**
Not totally sure if this is a bug or if this should be a feature request.  When using the `choose --no-limit` command it always sends through whichever row is highlighted regardless of whether it has been selected.  

**Describe the solution you'd like**
Add a `--optional` flag and only return options that are selected (as denoted by an X in the box with default style) when this flag is used.  If no options are selected then return an empty string.

**Describe alternatives you've considered**
The alternative is to bake a blank option into the choices and then add logic to look for result to match this option after `gum choose` operation.

**Additional context**
```
cat ~/choice_example.txt | gum choose --no-limit
> [•] one
  [ ] two
  [ ] three
one
```
Example of it returning whatever the line lands on without explicit selection.

**Comment by maaslalani** [comment]
Yeah, we might take this out later but it is so that the `gum choose` returns at least one option if the user presses enter on any selection (if you explicitly choose one then it doesn't implicitly select any).

To choose nothing you can press <kbd>ctrl+c</kbd>

**Comment by maaslalani** [comment]
I do agree that it is slightly strange behaviour that might be worth just ripping out.
