### ISSUE TITLE
Allow gum to work correctly with "gum spin $(...)"

### ISSUE THREAD

**Issue by ppsx** [charmbracelet/gum#94]
**Is your feature request related to a problem? Please describe.**
Currently "gum spin" is quite limited. For example it doesn't work correctly when used like that:
`gum spin VARIABLE=$(...)`

**Describe the solution you'd like**
It should work (should display spinner) when the command is a bit more complicated than simple `command [params]`

Currently there's no working workaround.

**Comment by maaslalani** [comment]
👍 We will try to fix this.

As a workaround you can make a script file and run that with `gum spin ./file.sh`

**Comment by muesli** [comment]
Try and set the environment variable before `gum`, which should pass the entire environment on to the sub-command:

```bash
VARIABLE="foobar" gum spin command
```

**Comment by maaslalani** [comment]
Also if you want to use the output of the command to the variable use `--show-output` and assign that.

```
VARIABLE=$(gum spin --show-output ....)
```

**Comment by ppsx** [comment]
Hi. Thanks for super-quick response.
It's rather a bit different scenario:
`gum spin --title="Getting possible options..." LIST_OF_POSSIBLE_VALUES=$(aws s3 ls ...)`
But the idea with external script is quite useful. Thanks for that :)

**Comment by maaslalani** [comment]
This should work:

```
LIST_OF_POSSIBLE_VALUES=$(gum spin --show-output --title="Getting possible options..." aws s3 ls ...)
```

**Comment by ppsx** [comment]
> This should work:
> 
> ```shell
> LIST_OF_POSSIBLE_VALUES=$(gum spin --show-output --title="Getting possible options..." aws s3 ls ...)
> ```

It's not, sorry :) Tried that before and tried that again.

**Comment by ppsx** [comment]
Ah, one more thing... What if the inner command output has to be processed with grep/sed/whatever?
I think the external script is the right way as otherwise the solution is too complicated (and actually not really required as the quite straightforward workaround is present).

**Comment by maaslalani** [comment]
Can you try that again with the latest code, I pushed a fix that should make it work now:
https://github.com/charmbracelet/gum/pull/95

If it doesn't please reopen the issue

**Comment by maaslalani** [comment]
> Ah, one more thing... What if the inner command output has to be processed with grep/sed/whatever? I think the external script is the right way as otherwise the solution is too complicated (and actually not really required as the quite straightforward workaround is present).

You can write to a file instead of a variable to allow more global state sharing.

```
aws s3 ls > possible_options.txt
```

**Comment by ppsx** [comment]
I've build gum from current sources. You're ritght, it's displaying spinner and gets data in the background. Cool :)
You're awsome, thanks!

**Comment by maaslalani** [comment]
Thank you for using Gum! @ppsx

**Comment by ppsx** [comment]
Nonono :)
Thanks for creating it!

**Comment by okarin001** [comment]
> I've build gum from current sources.

I am looking for a solution to this exact problem. Can you please guide me? I have updated gum to v0.4.0 but this isn't working.

**Comment by ppsx** [comment]
Hi.

You have two options: either wait a bit for next release or build it from sources.
If you want to try to build it by your own, you have to clone the repo and have go lang installed on your system (google this).
Then just cd to the project dir and run go build​. That's it.
Good luck!

Patrick S.
________________________________

Patrick Socha
Office +353 1 4125370
INFLIGHT DUBLIN, UNIT 3, DUNDRUM BUSINESS PARK, DUNDRUM ROAD, DUBLIN 14, IRELAND, D14 E4P8
www.inflightdublin.com
This email and any files transmitted may contain confidential and privileged information to Inflight Dublin. If you are not the named addressee you should not disseminate, distribute or copy this email. Please notify the sender immediately if you have received this email by mistake and delete this email from your system. If you are not the intended recipient you are notified that disclosing, copying distributing or taking action in reliance on the contents of this information is strictly prohibited. Although Inflight Dublin has taken reasonable precautions to ensure no viruses are present in this email, it accepts no liability for any loss or damage arising from the use of this email or its attachments. Furthermore, Inflight Dublin does not guarantee and is not liable for the security of any information electronically transmitted or for the proper and complete transmission of the information contained in this communication, or for any delay in its receipt.
